// P21 Charge mcc-3: Passendes Wort, Bereich Wortschatz (Kollokationen, Verben, Präpositionen). Quellformat wie mcc-1, dazu area 'lex' und lex[] für die Kartenbrücke.
export const meta = { file: 'k2-3' };
const W = (w, cat, text) => [w, cat, text];
export const items = [
  {
    p: 'lx.cause-attribute', area: 'lex', lex: ['attribute sth to sth'], lv: 'C1', dom: 'biz',
    t: 'The delay was largely ___ to a shortage of qualified staff in our warehouse during the holiday season.',
    o: [['attributed'], W('blamed', 'partner', 'blame braucht „on“: blamed on a shortage. || blame takes “on”: blamed on a shortage.'), W('caused', 'grammar', 'Im Passiv folgt „by“: was caused by, nicht „to“. || The passive takes “by”: was caused by, not “to”.'), W('resulted', 'calque', 'Deutsch „resultieren“ führt zu resulted; result hat kein Passiv und braucht from. || German “resultieren” leads to resulted; result has no passive and needs from.')],
    ok: 'attribute sth to sth = etwas auf etwas zurückführen; passt zu „to“. || attribute sth to sth = to say that sth is caused by sth; it fits “to”.',
  },
  {
    p: 'lx.rule-out', area: 'lex', lex: ['rule out'], lv: 'C1', dom: 'life',
    t: 'We cannot rule ___ the possibility of heavy rain on Saturday, so please bring a spare jacket.',
    o: [['out'], W('off', 'meaning', 'rule off heißt „einen Strich unter etwas ziehen“. || rule off means “draw a line under something”.'), W('down', 'grammar', 'rule down gibt es nicht. || rule down does not exist.'), W('away', 'calque', 'Deutsch „ausschließen“ klingt nach „weg“; die Wendung ist rule out. || German “ausschließen” sounds like “away”; the phrase is rule out.')],
    ok: 'etwas ausschließen: rule out. || to exclude something as a possibility: rule out.',
  },
  {
    p: 'lx.close-deal', area: 'lex', lex: ['close a deal'], lv: 'B2+', dom: 'biz',
    t: 'Our sales team managed to ___ the deal with the Swiss distributor just before the end of the quarter.',
    o: [['close'], W('shut', 'calque', 'Deutsch „einen Abschluss schließen“ führt zu shut; shut gilt für Türen und Läden. || German “einen Abschluss schließen” leads to shut; shut is for doors and shops.'), W('lock', 'partner', 'lock heißt „abschließen mit Schlüssel“. || lock means “secure with a key”.'), W('fasten', 'calque', 'Deutsch „festmachen“ führt zu fasten; fasten heißt „befestigen“ (Gurt, Knopf). || German “festmachen” leads to fasten; fasten means “attach” (a belt, a button).')],
    ok: 'Im Vertrieb schließt man ein Geschäft ab: close a deal. || In sales you complete a deal: close a deal.',
  },
  {
    p: 'lx.meet-deadline', area: 'lex', lex: ['meet a deadline'], lv: 'B2', dom: 'biz',
    t: 'We worked all weekend to ___ the deadline for the bid submission, and we made it with minutes to spare.',
    o: [['meet'], W('keep', 'calque', 'Deutsch „eine Frist einhalten“ führt zu keep; die feste Wendung ist meet a deadline. || German “eine Frist einhalten” leads to keep; the fixed phrase is meet a deadline.'), W('hold', 'calque', 'Deutsch „einhalten/halten“ führt zu hold; Fristen werden met. || German “einhalten/halten” leads to hold; deadlines are met.'), W('catch', 'partner', 'catch passt zu Zügen und Bällen, nicht zu Fristen. || catch goes with trains and balls, not deadlines.')],
    ok: 'Feste Verbindung: meet a deadline. || Fixed collocation: meet a deadline.',
  },
  {
    p: 'lx.raise-concern', area: 'lex', lex: ['raise concerns'], lv: 'B2+', dom: 'life',
    t: 'Several neighbors have ___ concerns about the noise from the new construction site during the night shifts.',
    o: [['raised'], W('lifted', 'calque', 'Deutsch „Bedenken äußern/erheben“ führt zu lifted; lift heißt „hochheben“. || German “Bedenken erheben” leads to lifted; lift means “pick up”.'), W('risen', 'grammar', 'rise ist intransitiv und hat kein Objekt; raise ist transitiv. || rise is intransitive and takes no object; raise is transitive.'), W('arisen', 'grammar', 'arise ist intransitiv: concerns have arisen, ohne Objekt. || arise is intransitive: concerns have arisen, with no object.')],
    ok: 'Bedenken äußern: raise concerns (raise braucht ein Objekt). || To voice concerns: raise concerns (raise takes an object).',
  },
  {
    p: 'lx.draw-conclusion', area: 'lex', lex: ['draw a conclusion'], lv: 'B2+', dom: 'life',
    t: 'After talking to both families, the school board can ___ a clear conclusion about what caused the argument.',
    o: [['draw'], W('pull', 'calque', 'Deutsch „einen Schluss ziehen“ führt zu pull; die Wendung ist draw a conclusion. || German “einen Schluss ziehen” leads to pull; the phrase is draw a conclusion.'), W('take', 'calque', 'take a conclusion gibt es nicht; take passt zu Entscheidungen oder Schritten. || take a conclusion does not exist; take goes with decisions or steps.'), W('make', 'partner', 'make a conclusion gilt als unüblich; Standard ist draw. || make a conclusion is considered uncommon; the standard is draw.')],
    ok: 'Feste Verbindung: draw a conclusion. || Fixed collocation: draw a conclusion.',
  },
  {
    p: 'lx.carry-out-review', area: 'lex', lex: ['carry out a review'], lv: 'B2+', dom: 'biz',
    t: 'The audit team will ___ a full review of the document archive next month, so please keep everything in order.',
    o: [['carry out'], W('lead through', 'calque', 'Deutsch „durchführen“ führt zu lead through; die Wendung ist carry out. || German “durchführen” leads to lead through; the phrase is carry out.'), W('make out', 'meaning', 'make out heißt „erkennen“ oder „so tun als ob“. || make out means “see” or “claim”.'), W('bring out', 'meaning', 'bring out heißt „herausbringen“ (ein Produkt). || bring out means “release” (a product).')],
    ok: 'Eine Prüfung durchführen: carry out a review. || To perform a review: carry out a review.',
  },
  {
    p: 'lx.make-profit', area: 'lex', lex: ['make a profit'], lv: 'B2', dom: 'life',
    t: 'In its third season, the small theater ___ a profit of fifty thousand euros for the first time.',
    o: [['made'], W('did', 'calque', 'Deutsch „Gewinn machen“ ist hier nicht do; es heißt make a profit. || German “Gewinn machen” is not do here; it is make a profit.'), W('won', 'calque', 'Deutsch „Gewinn“ führt zu won; Gewinn aus Geschäften wird gemacht (make). || German “Gewinn” leads to won; profit from business is made.'), W('gained', 'partner', 'gain a profit ist ungewöhnlich; üblich ist make a profit. || gain a profit is uncommon; make a profit is usual.')],
    ok: 'Feste Verbindung: make a profit. || Fixed collocation: make a profit.',
  },
  {
    p: 'lx.lodge-complaint', area: 'lex', lex: ['lodge a complaint'], lv: 'C1', dom: 'life',
    t: 'Passengers who wish to ___ a formal complaint about the delay should use the online form of the airline.',
    o: [['lodge'], W('put', 'calque', 'Deutsch „eine Beschwerde einlegen“ führt zu put; die Wendung ist lodge a complaint. || German “eine Beschwerde einlegen” leads to put; the phrase is lodge a complaint.'), W('give', 'calque', 'Deutsch „abgeben“ führt zu give; förmlich heißt es lodge. || German “abgeben” leads to give; formally it is lodge.'), W('do', 'grammar', 'do a complaint gibt es nicht. || do a complaint does not exist.')],
    ok: 'förmlich Beschwerde einlegen: lodge a complaint. || to make a formal complaint: lodge a complaint.',
  },
  {
    p: 'lx.set-targets', area: 'lex', lex: ['set targets'], lv: 'B2', dom: 'biz',
    t: 'Our new manager wants to ___ ambitious targets for the next quarter, but the team thinks they are unrealistic.',
    o: [['set'], W('put', 'calque', 'Deutsch „Ziele setzen“ klingt wie put; die Wendung ist set targets. || German “Ziele setzen” sounds like put; the phrase is set targets.'), W('lay', 'calque', 'Deutsch „Ziele legen“ gibt es nicht; lay passt zu Fundamenten und Plänen. || German has no “Ziele legen”; lay goes with foundations and plans.'), W('place', 'partner', 'place targets ist nicht üblich. || place targets is not usual.')],
    ok: 'Ziele setzen: set targets/goals. || To set goals: set targets/goals.',
  },
  {
    p: 'lx.follow-up-on', area: 'lex', lex: ['follow up on'], lv: 'C1', dom: 'biz',
    t: 'I will ___ up on the open points after the call and send you a short summary by tomorrow.',
    o: [['follow'], W('carry', 'partner', 'carry on heißt „weitermachen“, nicht „nachfassen“. || carry on means “continue”, not “follow up”.'), W('take', 'meaning', 'take up heißt „aufgreifen, anfangen mit“. || take up means “start” or “pick up”.'), W('go', 'calque', 'Deutsch „nachgehen“ führt zu go up; die Wendung ist follow up on. || German “nachgehen” leads to go up; the phrase is follow up on.')],
    ok: 'Nachfassen: follow up on sth. || To pursue sth further: follow up on sth.',
  },
  {
    p: 'lx.subject-to', area: 'lex', lex: ['be subject to'], lv: 'C1', dom: 'life',
    t: 'Our hiking trip on Saturday is ___ to the weather, so please keep your phone nearby.',
    o: [['subject'], W('due', 'partner', 'due to heißt „wegen“; „abhängig von“ heißt subject to. || due to means “because of”; “depending on” is subject to.'), W('bound', 'meaning', 'bound to heißt „ganz sicher“ (bound to happen). || bound to means “certain to” (bound to happen).'), W('dependent', 'calque', 'Deutsch „abhängig“ führt zu dependent; dependent braucht on. || German “abhängig” leads to dependent; dependent needs on.')],
    ok: 'abhängig von, vorbehaltlich: be subject to. || depending on, conditional on: be subject to.',
  },
  {
    p: 'lx.in-the-wake-of', area: 'lex', lex: ['in the wake of'], lv: 'C1', dom: 'life',
    t: '___ the wake of the storm, volunteers cleared the roads and opened the school gym for families.',
    o: [['In'], W('After', 'calque', 'Deutsch „nach dem Sturm“ führt zu After the wake; die Wendung ist In the wake of. || German “nach dem Sturm” leads to After the wake; the phrase is In the wake of.'), W('On', 'grammar', 'On the wake gibt es in dieser Bedeutung nicht. || On the wake does not exist in this meaning.'), W('By', 'grammar', 'By the wake gibt es nicht. || By the wake does not exist.')],
    ok: 'im Gefolge von, nach: in the wake of. || following, as a result of: in the wake of.',
  },
  {
    p: 'lx.shed-light', area: 'lex', lex: ['shed light on'], lv: 'C1', dom: 'life',
    t: 'The investigation may ___ some light on why the bridge was closed without any warning.',
    o: [['shed'], W('make', 'calque', 'Deutsch „Licht machen“ führt zu make; die Wendung ist shed light on. || German “Licht machen” leads to make; the phrase is shed light on.'), W('bring', 'grammar', 'bring some light on gibt es nicht; es heißt bring to light. || bring some light on does not exist; it is bring to light.'), W('give', 'grammar', 'give some light on gibt es nicht. || give some light on does not exist.')],
    ok: 'etwas aufklären: shed light on sth. || to clarify sth: shed light on sth.',
  },
  {
    p: 'lx.mitigate', area: 'lex', lex: ['mitigate the risk'], lv: 'C1', dom: 'life',
    t: 'The city built higher walls along the river to ___ the risk of flooding in the old town.',
    o: [['mitigate'], W('militate', 'meaning', 'militate gibt es nur mit „against“ (sprechen gegen). || militate exists only with “against” (argue against).'), W('mediate', 'meaning', 'mediate heißt „vermitteln“. || mediate means “settle a dispute”.'), W('medicate', 'meaning', 'medicate heißt „medikamentös behandeln“. || medicate means “treat with medicine”.')],
    ok: 'ein Risiko mindern: mitigate a risk. || to reduce a risk: mitigate a risk.',
  },
  {
    p: 'lx.fierce-competition', area: 'lex', lex: ['fierce competition'], lv: 'C1', dom: 'life',
    t: 'Local teams face ___ competition from two new clubs in the youth league, and many parents are worried.',
    o: [['fierce'], W('hard', 'calque', 'Deutsch „harte Konkurrenz“ führt zu hard; üblich ist fierce competition. || German “harte Konkurrenz” leads to hard; fierce competition is usual.'), W('rough', 'calque', 'rough heißt „grob, rau“; für Konkurrenz sagt man fierce. || rough means “coarse”; for competition you say fierce.'), W('thick', 'partner', 'thick passt zu Dicke (thick fog), nicht zu Konkurrenz. || thick goes with thickness (thick fog), not competition.')],
    ok: 'Starke Konkurrenz: fierce competition. || Strong competition: fierce competition.',
  },
  {
    p: 'lx.make-effort', area: 'lex', lex: ['make an effort'], lv: 'B2+', dom: 'life',
    t: 'We have ___ every effort to repair the old bridge on time, but the weather delayed everything.',
    o: [['made'], W('done', 'calque', 'Deutsch „Anstrengungen machen“ führt zu done; die Wendung ist make an effort. || German “Anstrengungen machen” leads to done; the phrase is make an effort.'), W('taken', 'calque', 'Deutsch „Mühe auf sich nehmen“ führt zu taken. || German “Mühe auf sich nehmen” leads to taken.'), W('put', 'grammar', 'put every effort braucht „into“; hier fehlt es. || put every effort needs “into”; it is missing here.')],
    ok: 'Feste Verbindung: make an effort. || Fixed collocation: make an effort.',
  },
  {
    p: 'lx.reach-agreement', area: 'lex', lex: ['reach an agreement'], lv: 'B2+', dom: 'life',
    t: 'After three days of difficult talks, both families finally ___ an agreement on the inheritance of the house.',
    o: [['reached'], W('met', 'calque', 'Deutsch „eine Einigung treffen“ führt zu met; die Wendung ist reach an agreement. || German “eine Einigung treffen” leads to met; the phrase is reach an agreement.'), W('found', 'calque', 'Deutsch „eine Einigung finden“ führt zu found; üblich ist reach. || German “eine Einigung finden” leads to found; reach is usual.'), W('took', 'grammar', 'take an agreement gibt es nicht. || take an agreement does not exist.')],
    ok: 'Feste Verbindung: reach an agreement. || Fixed collocation: reach an agreement.',
  },
  {
    p: 'lx.give-presentation', area: 'lex', lex: ['give a presentation'], lv: 'B2', dom: 'life',
    t: 'She will ___ a presentation on the history of our village at the library next Thursday.',
    o: [['give'], W('hold', 'calque', 'Deutsch „einen Vortrag halten“ führt zu hold; üblicher ist give a presentation. || German “einen Vortrag halten” leads to hold; give a presentation is more usual.'), W('keep', 'calque', 'Deutsch „halten“ führt zu keep; Vorträge werden gegeben (give). || German “halten” leads to keep; talks are given (give).'), W('bring', 'partner', 'bring passt zu Dingen, nicht zu Vorträgen. || bring goes with things, not talks.')],
    ok: 'Feste Verbindung: give a presentation. || Fixed collocation: give a presentation.',
  },
  {
    p: 'lx.run-business', area: 'lex', lex: ['run a business'], lv: 'B2', dom: 'life',
    t: 'He ___ a small bakery from a converted barn near Cologne and has three regular helpers.',
    o: [['runs'], W('carries', 'calque', 'carry heißt „tragen“; ein Geschäft betreibt man mit run (oder carry on). || carry means “bear”; a business is operated with run (or carry on).'), W('drives', 'calque', 'drive heißt „fahren/antreiben“; ein Geschäft wird run. || drive means “steer a vehicle/push”; a business is run.'), W('guides', 'meaning', 'guide heißt „führen, begleiten“ (Menschen). || guide means “lead, accompany” (people).')],
    ok: 'Ein Geschäft betreiben: run a business. || To operate a business: run a business.',
  },
  {
    p: 'lx.hold-accountable', area: 'lex', lex: ['hold sb accountable'], lv: 'C1', dom: 'biz',
    t: 'Managers must be ___ accountable for the results of their teams, not only for their own tasks.',
    o: [['held'], W('pulled', 'calque', 'Deutsch „zur Rechenschaft ziehen“ führt zu pulled; die Wendung ist hold sb accountable. || German “zur Rechenschaft ziehen” leads to pulled; the phrase is hold sb accountable.'), W('taken', 'calque', 'take sb accountable gibt es nicht. || take sb accountable does not exist.'), W('brought', 'grammar', 'brought accountable ist keine Wendung. || brought accountable is not a phrase.')],
    ok: 'jemanden verantwortlich machen: hold sb accountable. || to make sb responsible: hold sb accountable.',
  },
  {
    p: 'lx.hinge-on', area: 'lex', lex: ['hinge on'], lv: 'C1', dom: 'life',
    t: 'Whether we can afford the new apartment hinges ___ whether the bank approves our loan next week.',
    o: [['on'], W('at', 'grammar', 'hinges at gibt es nicht. || hinges at does not exist.'), W('of', 'calque', 'Deutsch „hängt von … ab“ führt zu of; hinge braucht on. || German “hängt von … ab” leads to of; hinge needs on.'), W('in', 'grammar', 'hinges in gibt es nicht. || hinges in does not exist.')],
    ok: 'von etwas abhängen (förmlich): hinge on. || to depend on sth (formal): hinge on.',
  },
  {
    p: 'lx.address-concerns', area: 'lex', lex: ['address concerns'], lv: 'C1', dom: 'life',
    t: 'The mayor ___ the concerns of the residents in a clear and honest speech at the town hall.',
    o: [['addressed'], W('treated', 'calque', 'Deutsch „behandelte die Bedenken“ führt zu treated; Bedenken geht man an: addressed. || German “behandelte die Bedenken” leads to treated; concerns are addressed.'), W('spoke', 'grammar', 'spoke braucht „about“ oder „to“. || spoke needs “about” or “to”.'), W('told', 'grammar', 'told braucht eine Person als Objekt. || told needs a person as its object.')],
    ok: 'auf Bedenken eingehen: address concerns. || to deal with concerns: address concerns.',
  },
  {
    p: 'lx.streamline', area: 'lex', lex: ['streamline'], lv: 'C1', dom: 'biz',
    t: 'We want to ___ the approval process so that contracts are signed within two days instead of two weeks.',
    o: [['streamline'], W('straighten', 'meaning', 'straighten heißt „gerade machen“. || straighten means “make straight”.'), W('slim', 'grammar', 'slim braucht down: slim down the process. || slim needs down: slim down the process.'), W('flow', 'meaning', 'flow heißt „fließen“ und hat kein Objekt. || flow means “run smoothly” and takes no object.')],
    ok: 'Abläufe straffen: streamline a process. || to make a process more efficient: streamline a process.',
  },
  {
    p: 'lx.aware-of', area: 'lex', lex: ['be aware of'], lv: 'B2+', dom: 'biz',
    t: 'Are you ___ of the new data protection rules that come into force in January and apply to all our customers?',
    o: [['aware'], W('known', 'calque', 'Deutsch „bekannt“ (bekannt mit) führt zu known; „sich bewusst sein“ heißt be aware of. || German “bekannt” leads to known; “to be aware” is be aware of.'), W('familiar', 'grammar', 'familiar braucht with: familiar with the rules. || familiar takes with: familiar with the rules.'), W('knowing', 'grammar', 'knowing ist eine -ing-Form; nach Are you steht ein Adjektiv. || knowing is an -ing form; after Are you comes an adjective.')],
    ok: 'Sich bewusst sein: be aware of. || To be conscious of: be aware of.',
  },
  {
    p: 'lx.arrive-at', area: 'lex', lex: ['arrive at'], lv: 'B2', dom: 'biz',
    t: 'We will ___ at the hotel around six o\'clock, so please keep a table in the restaurant for us.',
    o: [['arrive'], W('come', 'calque', 'Deutsch „wir kommen an“ führt zu come at; ankommen heißt arrive at/in. || German “wir kommen an” leads to come at; “ankommen” is arrive at/in.'), W('reach', 'grammar', 'reach braucht kein at: reach the hotel. || reach takes no at: reach the hotel.'), W('get', 'grammar', 'get braucht to: get to the hotel. || get needs to: get to the hotel.')],
    ok: 'Ankommen: arrive at (Ort) / arrive in (Stadt). || To get there: arrive at (a place) / arrive in (a city).',
  },
  {
    p: 'lx.discuss-object', area: 'lex', lex: ['discuss sth'], lv: 'B2', dom: 'biz',
    t: 'We need to ___ the new pricing model with the legal department before we can send it to the customers.',
    o: [['discuss'], W('talk', 'calque', 'Deutsch „sprechen über“ führt zu talk; talk braucht about. || German “sprechen über” leads to talk; talk needs about.'), W('speak', 'calque', 'speak braucht about oder with; direkt vor dem Objekt steht discuss. || speak needs about or with; directly before the object comes discuss.'), W('argue', 'meaning', 'argue heißt „streiten“ oder „argumentieren“. || argue means “quarrel” or “present arguments”.')],
    ok: 'discuss braucht kein „about“: discuss the model. || discuss takes no “about”: discuss the model.',
  },
  {
    p: 'lx.show-explain', area: 'lex', lex: ['show sb how'], lv: 'B2', dom: 'biz',
    t: 'Could you please ___ me how the new approval process works in practice? I have never used it.',
    o: [['show'], W('explain', 'calque', 'Deutsch „erklär mir“ führt zu explain me; es heißt explain to me. || German “erklär mir” leads to explain me; it is explain to me.'), W('say', 'grammar', 'say me gibt es nicht; es heißt tell me oder say to me. || say me does not exist; it is tell me or say to me.'), W('speak', 'grammar', 'speak me gibt es nicht. || speak me does not exist.')],
    ok: 'show sb how: jemandem etwas zeigen; explain braucht „to“ vor der Person. || show sb how: to demonstrate something; explain needs “to” before the person.',
  },
  {
    p: 'lx.remind-sb', area: 'lex', lex: ['remind sb to'], lv: 'B2', dom: 'biz',
    t: 'Please ___ me to send the invoice before the end of the week; otherwise I will probably forget it again.',
    o: [['remind'], W('remember', 'calque', 'Deutsch „erinnere mich“ führt zu remember; remember heißt „sich erinnern“. || German “erinnere mich” leads to remember; remember means “recall”.'), W('recall', 'meaning', 'recall heißt „sich erinnern an“ oder „zurückrufen“. || recall means “remember” or “call back”.'), W('memorize', 'meaning', 'memorize heißt „auswendig lernen“. || memorize means “learn by heart”.')],
    ok: 'Jemanden erinnern: remind sb to + Grundform. || To make sb remember: remind sb to + base form.',
  },
  {
    p: 'lx.bring-take', area: 'lex', lex: ['bring sth with you'], lv: 'B2', dom: 'biz',
    t: 'Could you ___ the signed contract with you when you come to our office tomorrow for the final meeting?',
    o: [['bring'], W('take', 'calque', 'Deutsch „mitnehmen“ führt zu take; bring gilt für die Richtung zum Sprecher hin. || German “mitnehmen” leads to take; bring is for the direction towards the speaker.'), W('carry', 'meaning', 'carry betont das Tragen, nicht die Richtung. || carry stresses the carrying, not the direction.'), W('fetch', 'meaning', 'fetch heißt „holen und zurückbringen“. || fetch means “go and get, then come back”.')],
    ok: 'Zum Sprecher hin: bring; vom Sprecher weg: take. || Towards the speaker: bring; away from the speaker: take.',
  },
];
