// P21 Charge mcc-3: Passendes Wort, Bereich Wortschatz (Kollokationen, Verben, Präpositionen). Quellformat wie mcc-1, dazu area 'lex' und lex[] für die Kartenbrücke.
export const meta = { file: 'k2-3' };
const W = (w, cat, text) => [w, cat, text];
export const items = [
  {
    p: 'lx.cause-attribute', area: 'lex', lex: ['attribute sth to sth'], lv: 'C1', dom: 'biz',
    t: 'The delay was largely ___ to a shortage of qualified staff in our warehouse during the holiday season.',
    o: [['attributed'], W('blamed', 'partner', 'blame braucht „on“: blamed on a shortage. || blame takes “on”: blamed on a shortage.'), W('caused', 'grammar', 'Im Passiv folgt „by“: was caused by, nicht „to“. || The passive takes “by”: was caused by, not “to”.'), W('resulted', 'calque', 'Deutsch „resultieren“ führt zu resulted; result hat kein Passiv und braucht from. || German “resultieren” leads to resulted; result has no passive and needs from.')],
    ok: 'attribute sth to sth = etwas auf etwas zurückführen; passt zu „to“. || attribute sth to sth = to say that sth is caused by sth; it fits “to”.',
  },
  {
    p: 'lx.make-decision', area: 'lex', lex: ['make a decision'], lv: 'B2', dom: 'biz',
    t: 'After weeks of discussion, the board finally ___ a decision about the location of the new data center.',
    o: [['made'], W('met', 'calque', 'Deutsch „eine Entscheidung treffen“ führt zu met; im Englischen heißt es make a decision. || German “eine Entscheidung treffen” leads to met; English says make a decision.'), W('did', 'calque', 'Deutsch „machen“ ist hier nicht do; für Entscheidungen steht make. || German “machen” is not do here; decisions take make.'), W('set', 'partner', 'set passt zu Zielen und Terminen, nicht zu Entscheidungen. || set goes with goals and dates, not with decisions.')],
    ok: 'Feste Verbindung: make a decision (US-Standard). || Fixed collocation: make a decision (US standard).',
  },
  {
    p: 'lx.close-deal', area: 'lex', lex: ['close a deal'], lv: 'B2+', dom: 'biz',
    t: 'Our sales team managed to ___ the deal with the Swiss distributor just before the end of the quarter.',
    o: [['close'], W('shut', 'calque', 'Deutsch „einen Abschluss schließen“ führt zu shut; shut gilt für Türen und Läden. || German “einen Abschluss schließen” leads to shut; shut is for doors and shops.'), W('lock', 'partner', 'lock heißt „abschließen mit Schlüssel“. || lock means “secure with a key”.'), W('fasten', 'calque', 'Deutsch „festmachen“ führt zu fasten; fasten heißt „befestigen“ (Gurt, Knopf). || German “festmachen” leads to fasten; fasten means “attach” (a belt, a button).')],
    ok: 'Im Vertrieb schließt man ein Geschäft ab: close a deal. || In sales you complete a deal: close a deal.',
  },
  {
    p: 'lx.meet-deadline', area: 'lex', lex: ['meet a deadline'], lv: 'B2', dom: 'biz',
    t: 'We worked all weekend to ___ the deadline for the tender submission, and we made it with minutes to spare.',
    o: [['meet'], W('keep', 'calque', 'Deutsch „eine Frist einhalten“ führt zu keep; die feste Wendung ist meet a deadline. || German “eine Frist einhalten” leads to keep; the fixed phrase is meet a deadline.'), W('hold', 'calque', 'Deutsch „einhalten/halten“ führt zu hold; Fristen werden met. || German “einhalten/halten” leads to hold; deadlines are met.'), W('catch', 'partner', 'catch passt zu Zügen und Bällen, nicht zu Fristen. || catch goes with trains and balls, not deadlines.')],
    ok: 'Feste Verbindung: meet a deadline. || Fixed collocation: meet a deadline.',
  },
  {
    p: 'lx.raise-concern', area: 'lex', lex: ['raise concerns'], lv: 'B2+', dom: 'biz',
    t: 'Several customers have ___ concerns about the security of the new cloud platform during the pilot phase.',
    o: [['raised'], W('lifted', 'calque', 'Deutsch „Bedenken äußern/erheben“ führt zu lifted; lift heißt „hochheben“. || German “Bedenken erheben” leads to lifted; lift means “pick up”.'), W('risen', 'grammar', 'rise ist intransitiv und hat kein Objekt; raise ist transitiv. || rise is intransitive and takes no object; raise is transitive.'), W('arisen', 'grammar', 'arise ist intransitiv: concerns have arisen, ohne Objekt. || arise is intransitive: concerns have arisen, with no object.')],
    ok: 'Bedenken äußern: raise concerns (raise braucht ein Objekt). || To voice concerns: raise concerns (raise takes an object).',
  },
  {
    p: 'lx.draw-conclusion', area: 'lex', lex: ['draw a conclusion'], lv: 'B2+', dom: 'biz',
    t: 'Based on the data from the last six months, we can ___ a clear conclusion about the success of the campaign.',
    o: [['draw'], W('pull', 'calque', 'Deutsch „einen Schluss ziehen“ führt zu pull; die Wendung ist draw a conclusion. || German “einen Schluss ziehen” leads to pull; the phrase is draw a conclusion.'), W('take', 'calque', 'take a conclusion gibt es nicht; take passt zu Entscheidungen oder Schritten. || take a conclusion does not exist; take goes with decisions or steps.'), W('make', 'partner', 'make a conclusion gilt als unüblich; Standard ist draw. || make a conclusion is considered uncommon; the standard is draw.')],
    ok: 'Feste Verbindung: draw a conclusion. || Fixed collocation: draw a conclusion.',
  },
  {
    p: 'lx.carry-out-review', area: 'lex', lex: ['carry out a review'], lv: 'B2+', dom: 'biz',
    t: 'The audit team will ___ a full review of the document archive next month, so please keep everything in order.',
    o: [['carry out'], W('lead through', 'calque', 'Deutsch „durchführen“ führt zu lead through; die Wendung ist carry out. || German “durchführen” leads to lead through; the phrase is carry out.'), W('make out', 'meaning', 'make out heißt „erkennen“ oder „so tun als ob“. || make out means “see” or “claim”.'), W('bring out', 'meaning', 'bring out heißt „herausbringen“ (ein Produkt). || bring out means “release” (a product).')],
    ok: 'Eine Prüfung durchführen: carry out a review. || To perform a review: carry out a review.',
  },
  {
    p: 'lx.make-profit', area: 'lex', lex: ['make a profit'], lv: 'B2', dom: 'biz',
    t: 'In the third quarter, the company ___ a profit of two million euros for the first time in four years.',
    o: [['made'], W('did', 'calque', 'Deutsch „Gewinn machen“ ist hier nicht do; es heißt make a profit. || German “Gewinn machen” is not do here; it is make a profit.'), W('won', 'calque', 'Deutsch „Gewinn“ führt zu won; Gewinn aus Geschäften wird gemacht (make). || German “Gewinn” leads to won; profit from business is made.'), W('gained', 'partner', 'gain a profit ist ungewöhnlich; üblich ist make a profit. || gain a profit is uncommon; make a profit is usual.')],
    ok: 'Feste Verbindung: make a profit. || Fixed collocation: make a profit.',
  },
  {
    p: 'lx.file-complaint', area: 'lex', lex: ['file a complaint'], lv: 'B2+', dom: 'biz',
    t: 'Customers can ___ a complaint through the online portal at any time of day, and they get a reference number.',
    o: [['file'], W('put', 'calque', 'Deutsch „eine Beschwerde einlegen“ führt zu put; die Wendung ist file a complaint. || German “eine Beschwerde einlegen” leads to put; the phrase is file a complaint.'), W('give', 'calque', 'Deutsch „eine Beschwerde abgeben“ führt zu give; üblich ist file. || German “eine Beschwerde abgeben” leads to give; file is usual.'), W('do', 'grammar', 'do a complaint gibt es nicht. || do a complaint does not exist.')],
    ok: 'Offizielle Beschwerde einreichen: file a complaint. || To submit an official complaint: file a complaint.',
  },
  {
    p: 'lx.set-targets', area: 'lex', lex: ['set targets'], lv: 'B2', dom: 'biz',
    t: 'Our new manager wants to ___ ambitious targets for the next quarter, but the team thinks they are unrealistic.',
    o: [['set'], W('put', 'calque', 'Deutsch „Ziele setzen“ klingt wie put; die Wendung ist set targets. || German “Ziele setzen” sounds like put; the phrase is set targets.'), W('lay', 'calque', 'Deutsch „Ziele legen“ gibt es nicht; lay passt zu Fundamenten und Plänen. || German has no “Ziele legen”; lay goes with foundations and plans.'), W('place', 'partner', 'place targets ist nicht üblich. || place targets is not usual.')],
    ok: 'Ziele setzen: set targets/goals. || To set goals: set targets/goals.',
  },
  {
    p: 'lx.pay-attention', area: 'lex', lex: ['pay attention to'], lv: 'B2', dom: 'life',
    t: 'Please ___ attention to the small print before you sign the contract, especially the clauses about termination.',
    o: [['pay'], W('present', 'calque', 'Deutsch „Aufmerksamkeit schenken“ führt zu Wörtern wie present oder give; üblich ist pay attention. || German “Aufmerksamkeit schenken” leads to words like present or give; pay attention is usual.'), W('do', 'grammar', 'do attention gibt es nicht. || do attention does not exist.'), W('take', 'partner', 'take attention gibt es nicht; take notice ist eine andere Wendung. || take attention does not exist; take notice is a different phrase.')],
    ok: 'Feste Verbindung: pay attention (to). || Fixed collocation: pay attention (to).',
  },
  {
    p: 'lx.take-place', area: 'lex', lex: ['take place'], lv: 'B2', dom: 'biz',
    t: 'The annual trade fair will ___ place in Hanover from the third to the sixth of March, and we have a booth.',
    o: [['take'], W('have', 'calque', 'Deutsch „findet statt“ führt zu have place; die Wendung ist take place. || German “findet statt” leads to have place; the phrase is take place.'), W('make', 'grammar', 'make place gibt es nicht. || make place does not exist.'), W('hold', 'partner', 'hold passt zu Veranstaltern (hold a fair), nicht zu einer Veranstaltung selbst. || hold goes with organizers (hold a fair), not with the event itself.')],
    ok: 'Veranstaltungen finden statt: take place. || Events happen: take place.',
  },
  {
    p: 'lx.make-sense', area: 'lex', lex: ['make sense'], lv: 'B2', dom: 'biz',
    t: 'Your proposal does not really ___ sense to me, because the numbers in the second table do not add up.',
    o: [['make'], W('have', 'calque', 'Deutsch „hat keinen Sinn“ führt zu have sense; die Wendung ist make sense. || German “hat keinen Sinn” leads to have sense; the phrase is make sense.'), W('give', 'grammar', 'give sense passt hier nicht. || give sense does not fit here.'), W('do', 'grammar', 'do sense gibt es nicht. || do sense does not exist.')],
    ok: 'Feste Verbindung: make sense. || Fixed collocation: make sense.',
  },
  {
    p: 'lx.keep-promise', area: 'lex', lex: ['keep a promise'], lv: 'B2', dom: 'biz',
    t: 'We always ___ our promises, so you can rely on our delivery dates even in the busiest weeks of the year.',
    o: [['keep'], W('hold', 'calque', 'Deutsch „Versprechen halten“ führt zu hold; im Englischen heißt es keep a promise. || German “Versprechen halten” leads to hold; English says keep a promise.'), W('stay', 'grammar', 'stay braucht kein Objekt und passt nicht zu promises. || stay takes no object and does not fit promises.'), W('maintain', 'partner', 'maintain passt zu Systemen und Beziehungen, nicht zu Versprechen. || maintain goes with systems and relationships, not promises.')],
    ok: 'Feste Verbindung: keep a promise. || Fixed collocation: keep a promise.',
  },
  {
    p: 'lx.take-risk', area: 'lex', lex: ['take a risk'], lv: 'B2', dom: 'biz',
    t: 'Nobody on the board wanted to ___ a risk with such an important client, so they chose the safe option.',
    o: [['take'], W('make', 'calque', 'Deutsch „ein Risiko eingehen“ führt zu make; die Wendung ist take a risk. || German “ein Risiko eingehen” leads to make; the phrase is take a risk.'), W('do', 'grammar', 'do a risk gibt es nicht. || do a risk does not exist.'), W('go', 'calque', 'Deutsch „eingehen“ führt zu go; die Wendung ist take a risk. || German “eingehen” leads to go; the phrase is take a risk.')],
    ok: 'Feste Verbindung: take a risk. || Fixed collocation: take a risk.',
  },
  {
    p: 'lx.fierce-competition', area: 'lex', lex: ['fierce competition'], lv: 'C1', dom: 'biz',
    t: 'We are facing ___ competition from two new providers in the Nordic market, and our margins are shrinking.',
    o: [['fierce'], W('hard', 'calque', 'Deutsch „harte Konkurrenz“ führt zu hard; üblich ist fierce competition. || German “harte Konkurrenz” leads to hard; fierce competition is usual.'), W('rough', 'calque', 'rough heißt „grob, rau“; für Konkurrenz sagt man fierce. || rough means “coarse”; for competition you say fierce.'), W('thick', 'partner', 'thick passt zu Dicke (thick fog), nicht zu Konkurrenz. || thick goes with thickness (thick fog), not competition.')],
    ok: 'Starke Konkurrenz: fierce competition. || Strong competition: fierce competition.',
  },
  {
    p: 'lx.make-effort', area: 'lex', lex: ['make an effort'], lv: 'B2+', dom: 'biz',
    t: 'We have ___ every effort to deliver the system on time, but the supplier delayed all the hardware.',
    o: [['made'], W('done', 'calque', 'Deutsch „Anstrengungen machen“ führt zu done; die Wendung ist make an effort. || German “Anstrengungen machen” leads to done; the phrase is make an effort.'), W('taken', 'calque', 'Deutsch „Mühe auf sich nehmen“ führt zu taken. || German “Mühe auf sich nehmen” leads to taken.'), W('put', 'grammar', 'put every effort braucht „into“; hier fehlt es. || put every effort needs “into”; it is missing here.')],
    ok: 'Feste Verbindung: make an effort. || Fixed collocation: make an effort.',
  },
  {
    p: 'lx.reach-agreement', area: 'lex', lex: ['reach an agreement'], lv: 'B2+', dom: 'biz',
    t: 'After three days of difficult talks, both parties finally ___ an agreement on the delivery terms.',
    o: [['reached'], W('met', 'calque', 'Deutsch „eine Einigung treffen“ führt zu met; die Wendung ist reach an agreement. || German “eine Einigung treffen” leads to met; the phrase is reach an agreement.'), W('found', 'calque', 'Deutsch „eine Einigung finden“ führt zu found; üblich ist reach. || German “eine Einigung finden” leads to found; reach is usual.'), W('took', 'grammar', 'take an agreement gibt es nicht. || take an agreement does not exist.')],
    ok: 'Feste Verbindung: reach an agreement. || Fixed collocation: reach an agreement.',
  },
  {
    p: 'lx.give-presentation', area: 'lex', lex: ['give a presentation'], lv: 'B2', dom: 'biz',
    t: 'She will ___ a presentation on the new archiving strategy at the conference in Frankfurt next Thursday.',
    o: [['give'], W('hold', 'calque', 'Deutsch „einen Vortrag halten“ führt zu hold; im Englischen heißt es give a presentation. || German “einen Vortrag halten” leads to hold; English says give a presentation.'), W('keep', 'calque', 'Deutsch „halten“ führt zu keep; Vorträge werden gegeben (give). || German “halten” leads to keep; talks are given (give).'), W('do', 'grammar', 'do a presentation ist ungewöhnlich; Standard ist give. || do a presentation is uncommon; the standard is give.')],
    ok: 'Feste Verbindung: give a presentation. || Fixed collocation: give a presentation.',
  },
  {
    p: 'lx.run-business', area: 'lex', lex: ['run a business'], lv: 'B2', dom: 'life',
    t: 'He ___ a small consulting business from his home office in Cologne and has three regular clients.',
    o: [['runs'], W('leads', 'calque', 'Deutsch „führt ein Geschäft“ führt zu leads; ein Unternehmen betreibt man mit run. || German “führt ein Geschäft” leads to leads; you operate a business with run.'), W('drives', 'calque', 'drive heißt „fahren/antreiben“; ein Geschäft wird run. || drive means “steer a vehicle/push”; a business is run.'), W('guides', 'meaning', 'guide heißt „führen, begleiten“ (Menschen). || guide means “lead, accompany” (people).')],
    ok: 'Ein Geschäft betreiben: run a business. || To operate a business: run a business.',
  },
  {
    p: 'lx.look-forward-to', area: 'lex', lex: ['look forward to'], lv: 'B2', dom: 'biz',
    t: 'We are looking forward ___ meeting you at the trade fair in September and showing you the new platform.',
    o: [['to'], W('for', 'calque', 'Deutsch „sich freuen auf“ führt zu for; die Wendung ist look forward to. || German “sich freuen auf” leads to for; the phrase is look forward to.'), W('at', 'calque', 'Deutsch „auf“ kann zu at führen; hier steht to. || German “auf” can lead to at; here it is to.'), W('on', 'calque', 'Deutsch „auf“ kann zu on führen; hier steht to. || German “auf” can lead to on; here it is to.')],
    ok: 'look forward to + -ing: sich auf etwas freuen. || look forward to + -ing: to be excited about something.',
  },
  {
    p: 'lx.depend-on', area: 'lex', lex: ['depend on'], lv: 'B2', dom: 'biz',
    t: 'Our delivery date ___ on the approval of the final design by the client, so please remind them today.',
    o: [['depends'], W('hangs', 'calque', 'Deutsch „hängt davon ab“ führt zu hangs; die Wendung ist depends on. || German “hängt davon ab” leads to hangs; the phrase is depends on.'), W('stands', 'meaning', 'stands on heißt „steht auf“. || stands on means “is standing on”.'), W('bases', 'grammar', 'bases on gibt es hier nicht; es heißt is based on. || bases on does not exist here; it is is based on.')],
    ok: 'Abhängigkeit: depend on. || Dependence: depend on.',
  },
  {
    p: 'lx.interested-in', area: 'lex', lex: ['interested in'], lv: 'B2', dom: 'biz',
    t: 'Our customers are increasingly interested ___ sustainable and energy-efficient data centers across Europe.',
    o: [['in'], W('for', 'calque', 'Deutsch „interessiert an“ oder „Interesse für“ führt zu for; die Wendung ist interested in. || German “interessiert an” or “Interesse für” leads to for; the phrase is interested in.'), W('at', 'calque', 'Deutsch „an“ führt zu at; die Wendung ist interested in. || German “an” leads to at; the phrase is interested in.'), W('on', 'calque', 'Deutsch „auf/an“ führt zu on; die Wendung ist interested in. || German “auf/an” leads to on; the phrase is interested in.')],
    ok: 'Feste Verbindung: interested in. || Fixed collocation: interested in.',
  },
  {
    p: 'lx.good-at', area: 'lex', lex: ['good at'], lv: 'B2', dom: 'life',
    t: 'I am not very good ___ negotiating prices in a foreign language, so I always prepare my main arguments in advance.',
    o: [['at'], W('in', 'calque', 'Deutsch „gut in“ führt zu in; die Wendung ist good at. || German “gut in” leads to in; the phrase is good at.'), W('for', 'calque', 'Deutsch „gut für“ führt zu for; good for heißt „nützlich für“. || German “gut für” leads to for; good for means “useful for”.'), W('with', 'meaning', 'good with heißt „geschickt im Umgang mit“ (Menschen, Werkzeug). || good with means “skilled in dealing with” (people, tools).')],
    ok: 'Fähigkeit: good at + -ing. || Ability: good at + -ing.',
  },
  {
    p: 'lx.aware-of', area: 'lex', lex: ['be aware of'], lv: 'B2+', dom: 'biz',
    t: 'Are you ___ of the new data protection rules that come into force in January and apply to all our customers?',
    o: [['aware'], W('known', 'calque', 'Deutsch „bekannt“ (bekannt mit) führt zu known; „sich bewusst sein“ heißt be aware of. || German “bekannt” leads to known; “to be aware” is be aware of.'), W('familiar', 'grammar', 'familiar braucht with: familiar with the rules. || familiar takes with: familiar with the rules.'), W('knowing', 'grammar', 'knowing ist eine -ing-Form; nach Are you steht ein Adjektiv. || knowing is an -ing form; after Are you comes an adjective.')],
    ok: 'Sich bewusst sein: be aware of. || To be conscious of: be aware of.',
  },
  {
    p: 'lx.arrive-at', area: 'lex', lex: ['arrive at'], lv: 'B2', dom: 'biz',
    t: 'We will ___ at the hotel around six o\'clock, so please keep a table in the restaurant for us.',
    o: [['arrive'], W('come', 'calque', 'Deutsch „wir kommen an“ führt zu come at; ankommen heißt arrive at/in. || German “wir kommen an” leads to come at; “ankommen” is arrive at/in.'), W('reach', 'grammar', 'reach braucht kein at: reach the hotel. || reach takes no at: reach the hotel.'), W('get', 'grammar', 'get braucht to: get to the hotel. || get needs to: get to the hotel.')],
    ok: 'Ankommen: arrive at (Ort) / arrive in (Stadt). || To get there: arrive at (a place) / arrive in (a city).',
  },
  {
    p: 'lx.discuss-object', area: 'lex', lex: ['discuss sth'], lv: 'B2', dom: 'biz',
    t: 'We need to ___ the new pricing model with the legal department before we can send it to the customers.',
    o: [['discuss'], W('talk', 'calque', 'Deutsch „sprechen über“ führt zu talk; talk braucht about. || German “sprechen über” leads to talk; talk needs about.'), W('speak', 'calque', 'speak braucht about oder with; direkt vor dem Objekt steht discuss. || speak needs about or with; directly before the object comes discuss.'), W('argue', 'meaning', 'argue heißt „streiten“ oder „argumentieren“. || argue means “quarrel” or “present arguments”.')],
    ok: 'discuss braucht kein „about“: discuss the model. || discuss takes no “about”: discuss the model.',
  },
  {
    p: 'lx.show-explain', area: 'lex', lex: ['show sb how'], lv: 'B2', dom: 'biz',
    t: 'Could you please ___ me how the new approval process works in practice? I have never used it.',
    o: [['show'], W('explain', 'calque', 'Deutsch „erklär mir“ führt zu explain me; es heißt explain to me. || German “erklär mir” leads to explain me; it is explain to me.'), W('say', 'grammar', 'say me gibt es nicht; es heißt tell me oder say to me. || say me does not exist; it is tell me or say to me.'), W('speak', 'grammar', 'speak me gibt es nicht. || speak me does not exist.')],
    ok: 'show sb how: jemandem etwas zeigen; explain braucht „to“ vor der Person. || show sb how: to demonstrate something; explain needs “to” before the person.',
  },
  {
    p: 'lx.remind-sb', area: 'lex', lex: ['remind sb to'], lv: 'B2', dom: 'biz',
    t: 'Please ___ me to send the invoice before the end of the week; otherwise I will probably forget it again.',
    o: [['remind'], W('remember', 'calque', 'Deutsch „erinnere mich“ führt zu remember; remember heißt „sich erinnern“. || German “erinnere mich” leads to remember; remember means “recall”.'), W('recall', 'meaning', 'recall heißt „sich erinnern an“ oder „zurückrufen“. || recall means “remember” or “call back”.'), W('memorize', 'meaning', 'memorize heißt „auswendig lernen“. || memorize means “learn by heart”.')],
    ok: 'Jemanden erinnern: remind sb to + Grundform. || To make sb remember: remind sb to + base form.',
  },
  {
    p: 'lx.bring-take', area: 'lex', lex: ['bring sth with you'], lv: 'B2', dom: 'biz',
    t: 'Could you ___ the signed contract with you when you come to our office tomorrow for the final meeting?',
    o: [['bring'], W('take', 'calque', 'Deutsch „mitnehmen“ führt zu take; bring gilt für die Richtung zum Sprecher hin. || German “mitnehmen” leads to take; bring is for the direction towards the speaker.'), W('carry', 'meaning', 'carry betont das Tragen, nicht die Richtung. || carry stresses the carrying, not the direction.'), W('fetch', 'meaning', 'fetch heißt „holen und zurückbringen“. || fetch means “go and get, then come back”.')],
    ok: 'Zum Sprecher hin: bring; vom Sprecher weg: take. || Towards the speaker: bring; away from the speaker: take.',
  },
];
