// P21 Charge mcc-4: Passendes Wort, Bereich Wortschatz (falsche Freunde, Intensivierer, feste Wendungen, Phrasal Verbs). Quellformat wie mcc-3.
export const meta = { file: 'k2-4' };
const W = (w, cat, text) => [w, cat, text];
export const items = [
  {
    p: 'lx.possibly-eventually', area: 'lex', lex: ['possibly'], lv: 'B2+', dom: 'biz',
    t: 'We could ___ move the meeting to Friday if the client agrees, but I need to check with the team first.',
    o: [['possibly'], W('eventually', 'calque', 'Deutsch „eventuell“ heißt possibly; eventually bedeutet „schließlich“ (false friend). || German “eventuell” means possibly; eventually means “in the end” (a false friend).'), W('finally', 'meaning', 'finally heißt „endlich, zum Schluss“. || finally means “at last, in the end”.'), W('lastly', 'meaning', 'lastly leitet den letzten Punkt einer Aufzählung ein. || lastly introduces the last point in a list.')],
    ok: 'possibly = eventuell, vielleicht; eventually = schließlich. || possibly = perhaps; eventually = in the end.',
  },
  {
    p: 'lx.sensitive-data', area: 'lex', lex: ['sensitive data'], lv: 'B2+', dom: 'biz',
    t: 'Our customer data is highly ___ and must be encrypted at all times, both in transit and in storage.',
    o: [['sensitive'], W('sensible', 'calque', 'Deutsch „sensibel“ heißt sensitive; sensible bedeutet „vernünftig“ (false friend). || German “sensibel” means sensitive; sensible means “reasonable” (a false friend).'), W('sensual', 'meaning', 'sensual heißt „sinnlich“. || sensual means “relating to the senses, erotic”.'), W('senseless', 'meaning', 'senseless heißt „sinnlos“ oder „bewusstlos“. || senseless means “pointless” or “unconscious”.')],
    ok: 'Sensible Daten: sensitive data. || Delicate data: sensitive data.',
  },
  {
    p: 'lx.current-actual', area: 'lex', lex: ['current version'], lv: 'B2', dom: 'biz',
    t: 'The ___ version of the software has several security problems that we need to fix before the audit.',
    o: [['current'], W('actual', 'calque', 'Deutsch „aktuell“ heißt current; actual bedeutet „tatsächlich“ (false friend). || German “aktuell” means current; actual means “real” (a false friend).'), W('topical', 'meaning', 'topical heißt „zum Thema passend, tagesaktuell“. || topical means “relating to current events”.'), W('modern', 'meaning', 'modern heißt „zeitgemäß“, nicht „derzeit gültig“. || modern means “up to date in style”, not “in use now”.')],
    ok: 'Die derzeit gültige Version: current version. || The version in use now: current version.',
  },
  {
    p: 'lx.check-control', area: 'lex', lex: ['check the figures'], lv: 'B2', dom: 'biz',
    t: 'Please ___ the figures again before you send the report to the board; last time there were two mistakes.',
    o: [['check'], W('control', 'calque', 'Deutsch „kontrollieren“ heißt check; control bedeutet „steuern, beherrschen“ (false friend). || German “kontrollieren” means check; control means “steer, have power over” (a false friend).'), W('steer', 'meaning', 'steer heißt „lenken“. || steer means “guide a vehicle”.'), W('command', 'meaning', 'command heißt „befehlen“. || command means “give orders”.')],
    ok: 'Zahlen prüfen: check the figures (oder review). || To verify figures: check the figures (or review).',
  },
  {
    p: 'lx.back-up', area: 'lex', lex: ['back up'], lv: 'B2', dom: 'biz',
    t: 'Please make sure that all important files are ___ every night, because the old server has failed twice this month.',
    o: [['backed up'], W('backed', 'grammar', 'backed braucht up: backed up (zwei Wörter). || backed needs up: backed up (two words).'), W('saved up', 'calque', 'save up heißt „Geld ansparen“. || save up means “put money aside”.'), W('backup', 'grammar', 'backup ist ein Nomen; das Verb heißt back up (zwei Wörter). || backup is a noun; the verb is back up (two words).')],
    ok: 'Daten sichern: back up (Verb), backup (Nomen). || To save data safely: back up (verb), backup (noun).',
  },
  {
    p: 'lx.give-up-hope', area: 'lex', lex: ['give up hope'], lv: 'B2+', dom: 'biz',
    t: 'We lost the tender, but nobody is ready to ___ up hope just yet, because the client may still reopen it.',
    o: [['give'], W('let', 'meaning', 'let up heißt „nachlassen“ und steht ohne Objekt. || let up means “become weaker” and takes no object.'), W('take', 'meaning', 'take up heißt „anfangen mit“ (a hobby). || take up means “start” (a hobby).'), W('throw', 'calque', 'Deutsch „die Hoffnung wegwerfen“ führt zu throw; die Wendung ist give up hope. || German “die Hoffnung wegwerfen” leads to throw; the phrase is give up hope.')],
    ok: 'Die ganze Wendung lernen: give up hope. || Learn the whole phrase: give up hope.',
  },
  {
    p: 'lx.intensify-better', area: 'lex', lex: ['considerably better'], lv: 'B2+', dom: 'biz',
    t: 'Our sales figures for the third quarter are ___ better than we expected, thanks to the new product line.',
    o: [['considerably'], W('highly', 'partner', 'highly steht vor Grundformen (highly effective), nie vor einem Komparativ. || highly goes with base adjectives (highly effective), never with a comparative.'), W('strongly', 'calque', '„Stark besser“ ist Deutsch gedacht; strongly passt zu Verben (strongly recommend). || “Stark besser” is German thinking; strongly goes with verbs (strongly recommend).'), W('heavily', 'partner', 'heavily passt zu Menge oder Last (heavily invested), nicht zu Vergleichen. || heavily goes with amount or weight (heavily invested), not comparisons.')],
    ok: 'Komparative verstärkt man mit much/far/considerably. || Comparatives are intensified with much/far/considerably.',
  },
  {
    p: 'lx.intensify-adj', area: 'lex', lex: ['highly intuitive'], lv: 'B2+', dom: 'biz',
    t: 'The new interface is ___ intuitive, and our employees learned it within an hour without any training.',
    o: [['highly'], W('strongly', 'calque', '„Stark intuitiv“ ist Deutsch gedacht; strongly passt zu Verben und Meinungen. || “Stark intuitiv” is German thinking; strongly goes with verbs and opinions.'), W('heavily', 'partner', 'heavily passt zu Menge oder Last, nicht zu Eigenschaften. || heavily goes with amount or weight, not with qualities.'), W('deeply', 'partner', 'deeply passt zu Gefühlen (deeply grateful), nicht zu intuitive. || deeply goes with feelings (deeply grateful), not with intuitive.')],
    ok: 'highly + Adjektiv wie effective, intuitive, skilled. || highly + adjectives such as effective, intuitive, skilled.',
  },
  {
    p: 'lx.highly-recommend', area: 'lex', lex: ['highly recommend'], lv: 'B2+', dom: 'biz',
    t: 'I can ___ recommend the new archiving solution to anyone who still struggles with paper files and shared folders.',
    o: [['highly'], W('heavily', 'partner', 'heavily passt zu Menge oder Last, nicht zu recommend. || heavily goes with amount or weight, not with recommend.'), W('hardly', 'calque', 'hardly heißt „kaum“, nicht „hart“ (false friend). || hardly means “barely”, not “hard” (a false friend).'), W('firmly', 'partner', 'firmly passt zu Überzeugungen (firmly believe), recommend verbindet sich mit highly. || firmly goes with convictions (firmly believe), while recommend pairs with highly.')],
    ok: 'Feste Verbindung: highly recommend. || Fixed collocation: highly recommend.',
  },
  {
    p: 'lx.deeply-regret', area: 'lex', lex: ['deeply regret'], lv: 'C1', dom: 'biz',
    t: 'We ___ regret that we are unable to deliver your order on the agreed date because of the strike at the port.',
    o: [['deeply'], W('highly', 'partner', 'highly steht nicht vor regret. || highly does not go before regret.'), W('heavily', 'partner', 'heavily passt zu Menge oder Last, nicht zu Gefühlen. || heavily goes with amount or weight, not with feelings.'), W('strongly', 'calque', '„Stark bedauern“ ist Deutsch gedacht; im Englischen sagt man deeply regret. || “Stark bedauern” is German thinking; English says deeply regret.')],
    ok: 'Feste Verbindung: deeply regret (förmlich). || Fixed collocation: deeply regret (formal).',
  },
  {
    p: 'lx.depend-heavily', area: 'lex', lex: ['depend heavily on'], lv: 'C1', dom: 'biz',
    t: 'Our business depends ___ on a handful of key accounts in the automotive sector, which is a real risk.',
    o: [['heavily'], W('highly', 'partner', 'highly steht vor Adjektiven (highly dependent), nicht nach depends. || highly goes before adjectives (highly dependent), not after depends.'), W('hardly', 'calque', 'hardly heißt „kaum“, nicht „hart“ (false friend). || hardly means “barely”, not “hard” (a false friend).'), W('fiercely', 'partner', 'fiercely passt zu Konkurrenz oder Verteidigung. || fiercely goes with competition or defense.')],
    ok: 'Feste Verbindung: depend heavily on. || Fixed collocation: depend heavily on.',
  },
  {
    p: 'lx.make-impression', area: 'lex', lex: ['make an impression'], lv: 'B2+', dom: 'biz',
    t: 'The new account manager made a very good ___ on our largest customer at the first meeting last week.',
    o: [['impression'], W('print', 'calque', 'Deutsch „Eindruck“ klingt wie Abdruck (print); im Englischen heißt es impression. || German “Eindruck” sounds like imprint (print); English says impression.'), W('impress', 'grammar', 'impress ist ein Verb; nach „a very good“ steht ein Nomen. || impress is a verb; a noun follows “a very good”.'), W('effect', 'meaning', 'effect heißt „Wirkung“; make a good effect gibt es so nicht. || effect means “result”; make a good effect does not exist like this.')],
    ok: 'Feste Verbindung: make a good impression on sb. || Fixed collocation: make a good impression on sb.',
  },
  {
    p: 'lx.in-charge-of', area: 'lex', lex: ['in charge of'], lv: 'B2+', dom: 'biz',
    t: 'Who is in ___ of the migration project while the director is on vacation for the next two weeks?',
    o: [['charge'], W('lead', 'calque', 'Deutsch „Leitung“ führt zu lead; die Wendung ist in charge of. || German “Leitung” leads to lead; the phrase is in charge of.'), W('head', 'calque', 'Deutsch „Chef“ führt zu head; die Wendung ist in charge of. || German “Chef” leads to head; the phrase is in charge of.'), W('guidance', 'partner', 'in guidance of ist keine Wendung. || in guidance of is not a phrase.')],
    ok: 'Verantwortlich sein: be in charge of. || To be responsible: be in charge of.',
  },
  {
    p: 'lx.on-behalf-of', area: 'lex', lex: ['on behalf of'], lv: 'B2+', dom: 'biz',
    t: 'I am writing ___ behalf of the sales department to thank you for your cooperation during the last quarter.',
    o: [['on'], W('at', 'calque', 'Deutsch „im Namen von“ führt zu at; die Wendung ist on behalf of. || German “im Namen von” leads to at; the phrase is on behalf of.'), W('for', 'calque', 'Deutsch „für“ führt zu for; die Wendung ist on behalf of. || German “für” leads to for; the phrase is on behalf of.'), W('by', 'grammar', 'by behalf of gibt es nicht. || by behalf of does not exist.')],
    ok: 'Feste Wendung: on behalf of = im Namen von. || Fixed phrase: on behalf of = representing.',
  },
  {
    p: 'lx.in-addition', area: 'lex', lex: ['in addition to'], lv: 'B2', dom: 'biz',
    t: '___ addition to the license fee, there will be a one-time setup cost for each regional office.',
    o: [['In'], W('At', 'calque', 'Deutsch „zusätzlich zu“ führt zu At; die Wendung ist In addition to. || German “zusätzlich zu” leads to At; the phrase is In addition to.'), W('On', 'grammar', 'On addition gibt es nicht. || On addition does not exist.'), W('By', 'grammar', 'By addition gibt es nicht. || By addition does not exist.')],
    ok: 'Feste Wendung: in addition to. || Fixed phrase: in addition to.',
  },
  {
    p: 'lx.as-a-result', area: 'lex', lex: ['as a result'], lv: 'B2', dom: 'biz',
    t: 'The server crashed twice last week. ___ a result, we lost almost two hours of work on the quarterly report.',
    o: [['As'], W('In', 'calque', 'Deutsch „in der Folge“ führt zu In; die Wendung ist As a result. || German “in der Folge” leads to In; the phrase is As a result.'), W('At', 'calque', 'Deutsch „am Ergebnis“ führt zu At; die Wendung ist As a result. || German “am Ergebnis” leads to At; the phrase is As a result.'), W('With', 'grammar', 'With a result passt nicht für eine Folge. || With a result does not work for a consequence.')],
    ok: 'Folge ausdrücken: as a result. || Expressing a consequence: as a result.',
  },
  {
    p: 'lx.by-mistake', area: 'lex', lex: ['by mistake'], lv: 'B2', dom: 'biz',
    t: 'I sent the offer to the wrong customer ___ mistake and had to apologize immediately to both parties.',
    o: [['by'], W('with', 'calque', 'Deutsch „mit einem Fehler“ führt zu with; „aus Versehen“ heißt by mistake. || German “mit einem Fehler” leads to with; “aus Versehen” is by mistake.'), W('in', 'calque', 'Deutsch „im Irrtum“ führt zu in; die Wendung ist by mistake. || German “im Irrtum” leads to in; the phrase is by mistake.'), W('on', 'grammar', 'on mistake gibt es nicht. || on mistake does not exist.')],
    ok: 'Aus Versehen: by mistake. || Not on purpose: by mistake.',
  },
  {
    p: 'lx.in-fact', area: 'lex', lex: ['in fact'], lv: 'B2', dom: 'biz',
    t: 'Everyone expected a delay, but ___ fact the project was finished two days early and under budget.',
    o: [['in'], W('by', 'calque', 'Deutsch „tatsächlich“ führt nicht zu by fact; die Wendung ist in fact. || German “tatsächlich” does not lead to by fact; the phrase is in fact.'), W('at', 'grammar', 'at fact gibt es nicht. || at fact does not exist.'), W('on', 'grammar', 'on fact gibt es nicht. || on fact does not exist.')],
    ok: 'Feste Wendung: in fact = tatsächlich. || Fixed phrase: in fact = actually.',
  },
  {
    p: 'lx.run-out-of', area: 'lex', lex: ['run out of'], lv: 'B2', dom: 'life',
    t: 'We have ___ out of printer paper again; could you please order some more before the audit on Monday?',
    o: [['run'], W('gone', 'calque', 'Deutsch „ist uns ausgegangen“ führt zu gone out of; die Wendung ist run out of. || German “ist uns ausgegangen” leads to gone out of; the phrase is run out of.'), W('got', 'meaning', 'get out of heißt „herauskommen aus, sich drücken vor“. || get out of means “escape from, avoid”.'), W('come', 'meaning', 'come out of heißt „herauskommen aus“. || come out of means “emerge from”.')],
    ok: 'Etwas ist aufgebraucht: run out of. || Something is used up: run out of.',
  },
  {
    p: 'lx.find-out', area: 'lex', lex: ['find out'], lv: 'B2', dom: 'life',
    t: 'Could you please ___ out when the next shuttle bus to the airport leaves and send me the time?',
    o: [['find'], W('look', 'meaning', 'look out heißt „aufpassen“. || look out means “be careful”.'), W('search', 'calque', 'Deutsch „herausfinden/suchen“ führt zu search out; für Informationen heißt es find out. || German “herausfinden/suchen” leads to search out; for information it is find out.'), W('seek', 'partner', 'seek out heißt „gezielt aufsuchen“ (Personen, Orte). || seek out means “look for deliberately” (people, places).')],
    ok: 'Informationen herausfinden: find out. || To learn information: find out.',
  },
  {
    p: 'lx.turn-down', area: 'lex', lex: ['turn down'], lv: 'B2+', dom: 'biz',
    t: 'The customer decided to ___ down our offer because the delivery time was too long for their project.',
    o: [['turn'], W('put', 'meaning', 'put down heißt „ablegen“ oder „kritisieren“. || put down means “place” or “criticize”.'), W('take', 'meaning', 'take down heißt „abbauen, notieren“. || take down means “dismantle, write down”.'), W('lay', 'calque', 'Deutsch „niederlegen/ablehnen“ führt zu lay down; das heißt „festlegen“. || German “niederlegen” leads to lay down; that means “set out” (rules).')],
    ok: 'Ein Angebot ablehnen: turn down an offer. || To reject an offer: turn down an offer.',
  },
  {
    p: 'lx.carry-on', area: 'lex', lex: ['carry on with'], lv: 'B2+', dom: 'biz',
    t: 'We need to ___ on with the project even though the budget has been cut by a third.',
    o: [['carry'], W('take', 'partner', 'take on heißt „übernehmen“ (eine Aufgabe). || take on means “accept” (a task).'), W('follow', 'calque', 'Deutsch „fortfahren, weiterverfolgen“ führt zu follow on; die Wendung ist carry on with. || German “fortfahren, weiterverfolgen” leads to follow on; the phrase is carry on with.'), W('hold', 'partner', 'hold on heißt „warten“. || hold on means “wait”.')],
    ok: 'Weitermachen: carry on with sth. || To continue: carry on with sth.',
  },
  {
    p: 'lx.come-to-nothing', area: 'lex', lex: ['come to nothing'], lv: 'C1', dom: 'biz',
    t: 'The negotiations ___ to nothing because neither side was willing to compromise on the price.',
    o: [['came'], W('ended', 'calque', 'Deutsch „endeten im Nichts“ führt zu ended; die Wendung ist came to nothing. || German “endeten im Nichts” leads to ended; the phrase is came to nothing.'), W('went', 'partner', 'went to nothing gibt es nicht. || went to nothing does not exist.'), W('ran', 'meaning', 'ran to heißt „lief zu“ oder „betrug“. || ran to means “went to” or “amounted to”.')],
    ok: 'Feste Wendung: come to nothing = zu nichts führen. || Fixed phrase: come to nothing = have no result.',
  },
  {
    p: 'lx.tight-schedule', area: 'lex', lex: ['tight schedule'], lv: 'B2+', dom: 'biz',
    t: 'We are working to a very ___ schedule this month because of the product launch and two customer events.',
    o: [['tight'], W('narrow', 'calque', 'Deutsch „enger Zeitplan“ führt zu narrow; üblich ist tight schedule. || German “enger Zeitplan” leads to narrow; tight schedule is usual.'), W('close', 'calque', 'close heißt „nah“; ein Zeitplan ist tight. || close means “near”; a schedule is tight.'), W('thin', 'partner', 'thin passt zu Dingen mit wenig Dicke, nicht zu Zeitplänen. || thin goes with things of little thickness, not schedules.')],
    ok: 'Feste Verbindung: a tight schedule. || Fixed collocation: a tight schedule.',
  },
  {
    p: 'lx.heavy-workload', area: 'lex', lex: ['heavy workload'], lv: 'B2+', dom: 'biz',
    t: 'Our support team has a very ___ workload before the holidays, so replies may take a little longer.',
    o: [['heavy'], W('strong', 'calque', 'Deutsch „starke Arbeitsbelastung“ führt zu strong; üblich ist heavy workload. || German “starke Arbeitsbelastung” leads to strong; heavy workload is usual.'), W('hard', 'calque', 'Deutsch „harte Arbeit“ führt zu hard; eine Arbeitsmenge ist heavy. || German “harte Arbeit” leads to hard; an amount of work is heavy.'), W('thick', 'partner', 'thick passt zu Dicke, nicht zu Arbeitsmenge. || thick goes with thickness, not an amount of work.')],
    ok: 'Feste Verbindung: a heavy workload. || Fixed collocation: a heavy workload.',
  },
  {
    p: 'lx.agree-with', area: 'lex', lex: ['agree with'], lv: 'B2', dom: 'biz',
    t: 'I fully agree ___ you that we should postpone the release until the security tests are finished.',
    o: [['with'], W('to', 'meaning', 'agree to heißt „zustimmen“ bei Vorschlägen und Bedingungen, nicht bei Personen. || agree to means “consent” to proposals and terms, not to people.'), W('on', 'meaning', 'agree on heißt „sich einigen auf“ (ein Thema). || agree on means “reach agreement about” (a topic).'), W('in', 'calque', 'Deutsch „einverstanden in“ gibt es nicht; mit Personen steht agree with. || German has no “einverstanden in”; with people it is agree with.')],
    ok: 'Zustimmen (einer Person): agree with sb. || To share sb\'s view: agree with sb.',
  },
  {
    p: 'lx.raise-prices', area: 'lex', lex: ['raise prices'], lv: 'B2', dom: 'biz',
    t: 'The company plans to ___ its prices by three percent from January because of higher energy costs.',
    o: [['raise'], W('rise', 'grammar', 'rise ist intransitiv und hat kein Objekt (prices rise). || rise is intransitive and takes no object (prices rise).'), W('lift', 'calque', 'Deutsch „Preise anheben“ führt zu lift; üblich ist raise prices. || German “Preise anheben” leads to lift; raise prices is usual.'), W('grow', 'calque', 'Deutsch „wachsen lassen“ führt zu grow; grow ist hier intransitiv. || German “wachsen lassen” leads to grow; grow is intransitive here.')],
    ok: 'Preise erhöhen: raise prices (Preise steigen: prices rise). || To increase prices: raise prices (prices go up: prices rise).',
  },
  {
    p: 'lx.earn-deserve', area: 'lex', lex: ['earn'], lv: 'B2', dom: 'life',
    t: 'She ___ about eighty thousand euros a year as a senior account manager in the cloud division.',
    o: [['earns'], W('deserves', 'calque', 'Deutsch „verdient“ kann auch „verdient haben“ heißen; deserve bedeutet nur „verdienen im Sinn von wert sein“. || German “verdient” can also mean “deserves”; deserve means only “be worthy of”.'), W('wins', 'calque', 'Deutsch „gewinnt“ führt zu wins; Gehalt wird earned. || German “gewinnt” leads to wins; salary is earned.'), W('gains', 'partner', 'gain passt zu Erfahrung oder Vorteilen, nicht zu Gehalt. || gain goes with experience or advantages, not salary.')],
    ok: 'Geld verdienen: earn money. || Making money: earn money.',
  },
  {
    p: 'lx.borrow-lend', area: 'lex', lex: ['borrow'], lv: 'B2', dom: 'biz',
    t: 'Could I ___ your laptop for the demo this afternoon? Mine is being repaired and I need it back tomorrow.',
    o: [['borrow'], W('lend', 'grammar', 'lend heißt „verleihen“; der Besitzer lendet, du borgst. || lend means to give someone something; the owner lends, you borrow.'), W('rent', 'calque', 'Deutsch „ausleihen“ führt zu rent; rent bedeutet „gegen Gebühr mieten“. || German “ausleihen” leads to rent; rent means “hire for a fee”.'), W('lease', 'meaning', 'lease heißt „leasen, längerfristig mieten“. || lease means to rent for a longer period.')],
    ok: 'Von jemandem leihen: borrow from sb. || To get sth from sb for a while: borrow from sb.',
  },
  {
    p: 'lx.make-appointment', area: 'lex', lex: ['make an appointment'], lv: 'B2', dom: 'biz',
    t: 'I would like to ___ an appointment with your sales manager for next Tuesday afternoon, if she is available.',
    o: [['make'], W('agree', 'calque', 'Deutsch „einen Termin vereinbaren“ führt zu agree; die Wendung ist make an appointment. || German “einen Termin vereinbaren” leads to agree; the phrase is make an appointment.'), W('take', 'partner', 'take an appointment ist unüblich. || take an appointment is uncommon.'), W('hold', 'partner', 'hold an appointment gibt es nicht. || hold an appointment does not exist.')],
    ok: 'Einen Termin vereinbaren: make an appointment. || To arrange a date: make an appointment.',
  },
];
