// P18 Charge 3 (err 1): Kapitel 1 – pres-simple-cont, past-simple-perfect, pres-perf-cont. 18 mit Fehler, 9 fehlerfrei.
// bad: span = Fehlerstelle im Satz, fix = alle richtigen Korrekturen, ch = zwei falsche Wahlmöglichkeiten.
// ok = Begründung (DE, EN) · c1/c2 = warum die falsche Wahl nicht passt · fa = [Wort, DE, EN] Fehlalarm-Begründung (fehlerfreie Sätze).
export const meta = { file: 'k1-1', start: 1 };
export const items = [
  // ---- pres-simple-cont ----
  {
    p: 'psc.habit', lv: 'B2', dom: 'biz',
    text: 'Every Monday, our sales team is reviewing the pipeline together.',
    bad: { span: 'is reviewing', fix: ['reviews'], ch: ['does reviews', 'reviewing'] },
    ok: ['„Every Monday“ nennt eine Gewohnheit, also Present Simple: reviews. -ing zeigt nur einen Moment, den Deutsch („prüft“) nicht trennt.', '“Every Monday” names a habit, so the present simple: reviews. -ing would show a single moment, which German “prüft” does not distinguish.'],
    c1: ['Nach does steht die Grundform ohne -s: does review. „does reviews“ ist doppelt markiert.', 'After does comes the base form without -s: does review.'],
    c2: ['„reviewing“ allein ist kein vollständiges Verb. Es fehlt das Hilfsverb.', '“reviewing” alone is not a complete verb. The auxiliary is missing.'],
  },
  {
    p: 'psc.habit', lv: 'B2', dom: 'biz',
    text: 'Our CEO never take notes during board meetings, she just listens.',
    bad: { span: 'take', fix: ['takes'], ch: ['taking', 'have take'] },
    ok: ['Bei he/she/it (our CEO = she) braucht das Present Simple ein -s: takes. Deutsch hat „nimmt“ mit -t, im Englischen fällt das -s leicht weg.', 'With he/she/it (our CEO = she) the present simple needs -s: takes. German speakers often drop the -s.'],
    c1: ['„never taking“ ohne Hilfsverb ist kein vollständiges Prädikat.', '“never taking” without an auxiliary is no complete predicate.'],
    c2: ['„have take“ ist keine gültige Zeitform.', '“have take” is not a valid tense.'],
  },
  {
    p: 'psc.habit', lv: 'B2', dom: 'biz',
    text: 'Our deployment pipeline runs automatically every night at two a.m.',
    bad: null,
    ok: ['Kein Fehler: Ein fester, wiederkehrender Ablauf („every night“) steht im Present Simple: runs.', 'No mistake: a fixed recurring process (“every night”) takes the present simple: runs.'],
    fa: [['runs', 'Gewohnheiten und feste Abläufe brauchen kein -ing. „is running“ wäre hier der Fehler.', 'Habits and fixed processes need no -ing. “is running” would be the mistake here.']],
  },
  {
    p: 'psc.now', lv: 'B2', dom: 'biz',
    text: 'Please be quiet, the CEO talks to a major customer on the phone right now.',
    bad: { span: 'talks', fix: ['is talking'], ch: ['talk', 'talked'] },
    ok: ['„Right now“ meint den Moment: Present Continuous, is talking. Deutsch sagt auch hier nur „spricht“.', '“Right now” means this moment: present continuous, is talking. German also says only “spricht”.'],
    c1: ['„talk“ ohne -s passt nicht zu he/she/it und wäre trotzdem ein Gewohnheits-Präsens.', '“talk” without -s does not fit he/she/it and would still be a habit form.'],
    c2: ['„talked“ ist Vergangenheit, aber „right now“ verlangt die Gegenwart.', '“talked” is past, but “right now” needs the present.'],
  },
  {
    p: 'psc.now', lv: 'B2', dom: 'biz',
    text: 'We are testing the new login flow with three pilot customers this month.',
    bad: null,
    ok: ['Kein Fehler: Ein zeitlich begrenztes Projekt („this month“) steht im Present Continuous: are testing.', 'No mistake: a temporary project (“this month”) takes the present continuous: are testing.'],
    fa: [['are', 'Vorübergehende Lage = be + -ing. „We test“ würde eine feste Gewohnheit behaupten.', 'A temporary situation = be + -ing. “We test” would claim a fixed habit.']],
  },
  {
    p: 'psc.state', lv: 'B2', dom: 'biz', h: 1,
    text: 'I am knowing the answer to your question about the invoice.',
    bad: { span: 'am knowing', fix: ['know'], ch: ['knowing', 'do knowing'] },
    ok: ['know ist ein Zustandsverb und steht nicht in der Verlaufsform (be + -ing). Deutsch kennt den Unterschied nicht, daher passiert der Fehler leicht.', 'Know is a state verb and does not take the continuous (be + -ing). German does not make the distinction, so the mistake is easy to make.'],
    c1: ['„knowing“ allein ist kein Prädikat.', '“knowing” alone is no predicate.'],
    c2: ['Nach do steht die Grundform: do know. „do knowing“ gibt es nicht.', 'After do comes the base form: do know. “do knowing” does not exist.'],
  },
  {
    p: 'psc.always', lv: 'B2+', dom: 'biz',
    text: 'Our vendor is changing always the delivery dates without any warning.',
    bad: { span: 'changing always', fix: ['always changing'], ch: ['always changes', 'always changed'] },
    ok: ['Bei Ärger über Wiederholung steht always zwischen is und -ing: is always changing. Deutsch „ändert immer“ stellt „immer“ gern ans Ende.', 'To show annoyance at repetition always goes between is and -ing: is always changing. German often puts “immer” last.'],
    c1: ['Nach „is“ steht kein Verb mit -s: „is always changes“ ist ungrammatisch.', 'After “is” a verb with -s is impossible: “is always changes”.'],
    c2: ['„is always changed“ wäre Passiv und passt nicht zum Objekt „the delivery dates“.', '“is always changed” would be passive and does not fit the object.'],
  },
  {
    p: 'psc.state', lv: 'B2+', dom: 'life',
    text: 'I am believing this price is too high for our budget, to be honest.',
    bad: { span: 'am believing', fix: ['believe'], ch: ['believing', 'do believing'] },
    ok: ['believe ist ein Zustandsverb (Meinung) und hat keine -ing-Form: I believe. Deutsch „ich glaube“ kennt nur eine Präsensform.', 'Believe is a state verb (opinion) and has no -ing form: I believe. German “ich glaube” has only one present form.'],
    c1: ['„believing“ allein ist kein Prädikat.', '“believing” alone is no predicate.'],
    c2: ['Nach do steht die Grundform: do believe. „do believing“ gibt es nicht.', 'After do comes the base form: do believe. “do believing” does not exist.'],
  },
  {
    p: 'psc.dual', lv: 'B2+', dom: 'life',
    text: 'I am having lunch with a client at one, so I cannot join the call.',
    bad: null,
    ok: ['Kein Fehler: have meint hier „essen“, eine Handlung. Dann ist -ing richtig: am having lunch.', 'No mistake: have means “eat” here, an action. Then -ing is right: am having lunch.'],
    fa: [['having', 'Als Handlung („lunch haben = essen“) steht have im Continuous. Nur als Besitz („have a car“) nicht.', 'As an action (“have lunch = eat”) have takes the continuous. Only as possession (“have a car”) it does not.']],
  },
  // ---- past-simple-perfect ----
  {
    p: 'psp.finished-time', lv: 'B2', dom: 'biz', trapId: 'f22',
    text: 'We have signed the framework agreement in March last year.',
    bad: { span: 'have signed', fix: ['signed', 'did sign'], ch: ['are signing', 'have been signing'] },
    ok: ['„In March last year“ ist abgeschlossene Zeit: Past Simple, signed. Das deutsche Perfekt („haben unterschrieben“) verleitet zum Present Perfect.', '“In March last year” is finished time: past simple, signed. The German perfect (“haben unterschrieben”) invites the present perfect.'],
    c1: ['„are signing“ beschreibt etwas, das gerade läuft, nicht etwas vom letzten Jahr.', '“are signing” describes something happening now, not last year.'],
    c2: ['„have been signing“ betont eine andauernde Handlung bis jetzt und passt nicht zu einem Zeitpunkt.', '“have been signing” stresses an action lasting until now and does not fit a point in time.'],
  },
  {
    p: 'psp.finished-time', lv: 'B2', dom: 'biz', trapId: 'f22',
    text: 'When have you received the corrected invoice from the supplier?',
    bad: { span: 'have you received', fix: ['did you receive'], ch: ['have you receive', 'did you received'] },
    ok: ['„When“ fragt nach einem Zeitpunkt: Past Simple, did you receive. Deutsch „Wann hast du bekommen?“ nutzt das Perfekt.', '“When” asks for a point in time: past simple, did you receive. German “Wann hast du bekommen?” uses the perfect.'],
    c1: ['Nach have steht die 3. Form: have you received. „have you receive“ mischt zwei Formen.', 'After have comes the participle: have you received. “have you receive” mixes forms.'],
    c2: ['Nach did steht die Grundform: did you receive, nicht received.', 'After did comes the base form: did you receive, not received.'],
  },
  {
    p: 'psp.since-for', lv: 'B2', dom: 'biz', trapId: 'f12',
    text: 'We are partners with Rhein Logistics since 2019 and plan to extend it.',
    bad: { span: 'are', fix: ['have been'], ch: ['were', 'have'] },
    ok: ['Bei „since 2019“ gilt der Zustand bis heute: have been. Deutsch nutzt dafür das Präsens („wir sind Partner seit 2019“).', 'With “since 2019” the state lasts until now: have been. German uses the present for it (“wir sind Partner seit 2019”).'],
    c1: ['„were“ wäre abgeschlossen und passt nicht zu since und „plan to extend“.', '“were” would be finished and does not fit since and “plan to extend”.'],
    c2: ['Mit have allein entstünde „We have partners …“ mit anderer Bedeutung. Gemeint ist der Zustand: have been.', 'With have alone it would read “We have partners …” with another meaning. The state is meant: have been.'],
  },
  {
    p: 'psp.since-for', lv: 'B2', dom: 'biz', trapId: 'f12',
    text: 'The client has been silent since three weeks, so we should call.',
    bad: { span: 'since', fix: ['for'], ch: ['from', 'during'] },
    ok: ['Since nennt einen Startpunkt („since March“), for eine Zeitspanne („for three weeks“). Deutsch „seit“ deckt beides ab.', 'Since names a starting point (“since March”), for a length of time (“for three weeks”). German “seit” covers both.'],
    c1: ['„from three weeks“ gibt es für diese Bedeutung nicht.', '“from three weeks” does not exist in this meaning.'],
    c2: ['„during“ nennt einen Zeitraum, in dem etwas geschieht, nicht die Dauer bis jetzt.', '“during” names a period in which something happens, not the duration until now.'],
  },
  {
    p: 'psp.result-now', lv: 'B2', dom: 'biz',
    text: 'I have yet not sent the invoice, but I will do it today.',
    bad: { span: 'yet not', fix: ['not yet'], ch: ['yet no', 'no yet'] },
    ok: ['Im Deutschen steht „noch“ vor „nicht“, im Englischen kommt not vor yet: have not yet sent.', 'German puts “noch” before “nicht”; English puts not before yet: have not yet sent.'],
    c1: ['„yet no“ verneint das Verb nicht: Mit have steht not, danach yet.', '“yet no” does not negate the verb: with have it is not, then yet.'],
    c2: ['„no yet“ gibt es nicht: Zur Verneinung mit have steht not.', '“no yet” does not exist: negation with have uses not.'],
  },
  {
    p: 'psp.experience', lv: 'B2', dom: 'biz',
    text: 'Have you ever went to a customer workshop in Munich?',
    bad: { span: 'went', fix: ['gone', 'been'], ch: ['go', 'going'] },
    ok: ['Nach have steht die 3. Form (gone/been), nicht das Past Simple went. Deutsch „bist du je gefahren“ hat nur ein Partizip, die Formen sind ähnlich.', 'After have comes the participle (gone/been), not the past simple went. The two forms look similar to German learners.'],
    c1: ['Nach have steht keine Grundform: have gone.', 'No base form after have: have gone.'],
    c2: ['„going“ ist keine 3. Form; have going ist ungrammatisch.', '“going” is not a participle; “have going” is ungrammatical.'],
  },
  {
    p: 'psp.since-for', lv: 'B2', dom: 'biz',
    text: 'I have worked with this vendor since 2018, and they have never missed a deadline.',
    bad: null,
    ok: ['Kein Fehler: Zustand bis heute (since 2018) und Erfahrung (never): beides Present Perfect.', 'No mistake: a state until now (since 2018) and experience (never): both present perfect.'],
    fa: [['have', 'have + worked: Mit since 2018 braucht der Satz das Present Perfect. „I worked … since 2018“ wäre falsch.', 'have + worked: with since 2018 the sentence needs the present perfect. “I worked … since 2018” would be wrong.']],
  },
  {
    p: 'psp.finished-time', lv: 'B2', dom: 'biz', trapId: 'f22',
    text: 'We signed the contract last Tuesday, and the client paid the deposit yesterday.',
    bad: null,
    ok: ['Kein Fehler: „last Tuesday“ und „yesterday“ sind abgeschlossene Zeitpunkte, deshalb Past Simple.', 'No mistake: “last Tuesday” and “yesterday” are finished points in time, so the past simple.'],
    fa: [['signed', 'Mit einer festen Zeitangabe steht das Past Simple. „have signed“ wäre hier der Fehler.', 'With a fixed time expression the past simple is right. “have signed” would be the mistake.']],
  },
  {
    p: 'psp.experience', lv: 'B2', dom: 'life',
    text: 'Have you ever presented to a board of directors in German?',
    bad: null,
    ok: ['Kein Fehler: Erfahrung bis jetzt, ohne Zeitpunkt, braucht das Present Perfect: Have you ever presented.', 'No mistake: experience up to now, with no point in time, takes the present perfect: Have you ever presented.'],
    fa: [['Have', 'Present Perfect betont die Erfahrung bis jetzt. „Did you ever …“ geht im US-Alltag auch, aber nicht mit fester Zeitangabe.', 'The present perfect stresses experience up to now. “Did you ever …” also works in casual US English, but not with a fixed time.']],
  },
  // ---- pres-perf-cont ----
  {
    p: 'pc.duration', lv: 'B2', dom: 'biz', trapId: 'f12',
    text: 'Our sales team is using the new CRM since January and likes it.',
    bad: { span: 'is using', fix: ['has been using', 'has used'], ch: ['uses', 'used'] },
    ok: ['Mit „since January“ gilt die Tätigkeit bis jetzt: has been using. Deutsch nutzt dafür das Präsens („nutzt seit Januar“).', 'With “since January” the activity lasts until now: has been using. German uses the present for it (“nutzt seit Januar”).'],
    c1: ['„uses“ ist Gewohnheits-Präsens und trägt die Dauer seit Januar nicht.', '“uses” is a habit present and does not carry the duration since January.'],
    c2: ['„used“ wäre abgeschlossen, aber das Team nutzt es noch.', '“used” would be finished, but the team still uses it.'],
  },
  {
    p: 'pc.since-for', lv: 'B2', dom: 'biz', trapId: 'f12',
    text: 'I have been waiting since twenty minutes for the client’s reply.',
    bad: { span: 'since', fix: ['for'], ch: ['from', 'during'] },
    ok: ['„Twenty minutes“ ist eine Zeitspanne, also for. Since braucht einen Startpunkt wie „since nine o’clock“.', '“Twenty minutes” is a length of time, so for. Since needs a starting point such as “since nine o’clock”.'],
    c1: ['„from twenty minutes“ gibt es in dieser Bedeutung nicht.', '“from twenty minutes” does not exist in this meaning.'],
    c2: ['„during“ passt nicht zu einer Dauer bis jetzt.', '“during” does not fit a duration up to now.'],
  },
  {
    p: 'pc.form', lv: 'B2', dom: 'biz',
    text: 'She have been reviewing the contract since nine o’clock this morning.',
    bad: { span: 'have', fix: ['has'], ch: ['is', 'having'] },
    ok: ['Das Hilfsverb richtet sich nach she: has been reviewing. Bei he/she/it heißt es has, nie have.', 'The auxiliary agrees with she: has been reviewing. With he/she/it it is has, never have.'],
    c1: ['„is been“ gibt es nicht: has/have + been, nie is + been.', '“is been” does not exist: has/have + been, never is + been.'],
    c2: ['„having been“ ist keine vollständige Verbform im Satz.', '“having been” is no complete verb form in the sentence.'],
  },
  {
    p: 'pc.recent', lv: 'B2', dom: 'biz',
    text: 'We don’t hear from the client lately, which worries me a little.',
    bad: { span: 'don’t hear', fix: ['haven’t heard', 'have not heard', 'haven’t been hearing', 'have not been hearing'], ch: ['haven’t hear', 'don’t heard'] },
    ok: ['„Lately“ blickt vom Heute aus zurück: Present Perfect, haven’t heard. Deutsch „in letzter Zeit hören wir nichts“ nutzt das Präsens.', '“Lately” looks back from today: present perfect, haven’t heard. German “in letzter Zeit hören wir nichts” uses the present.'],
    c1: ['„haven’t hear“ mischt Hilfsverb und Grundform: have braucht die 3. Form (heard).', '“haven’t hear” mixes auxiliary and base form: have needs the participle (heard).'],
    c2: ['Nach don’t steht die Grundform, nicht heard.', 'After don’t comes the base form, not heard.'],
  },
  {
    p: 'pc.state-verbs', lv: 'B2', dom: 'biz', h: 1,
    text: 'We have been knowing this supplier since 2017 and trust them.',
    bad: { span: 'have been knowing', fix: ['have known'], ch: ['have knowing', 'are knowing'] },
    ok: ['know ist ein Zustandsverb und steht nicht in der Verlaufsform (be/been + -ing), auch nicht im Present Perfect: have known.', 'Know is a state verb and does not take the continuous (be/been + -ing), not even in the present perfect: have known.'],
    c1: ['Nach have steht die 3. Form (known), nicht -ing.', 'After have comes the participle (known), not -ing.'],
    c2: ['„are knowing“ ist Continuous, hier fehlt dazu die Dauer seit 2017.', '“are knowing” is continuous and ignores the duration since 2017.'],
  },
  {
    p: 'pc.cont-simple', lv: 'B2+', dom: 'biz',
    text: 'She has been sending twelve proposals, and all twelve are already signed.',
    bad: { span: 'has been sending', fix: ['has sent'], ch: ['has send', 'have sent'] },
    ok: ['Bei einer Zahl rückt das Ergebnis in den Vordergrund: has sent. -ing betont die Tätigkeit, nicht die Menge.', 'With a number the result moves to the front: has sent. -ing stresses the activity, not the amount.'],
    c1: ['„has send“ mischt Hilfsverb und Grundform: has braucht die 3. Form (sent).', '“has send” mixes auxiliary and base form: has needs the participle (sent).'],
    c2: ['Zu she passt has, nicht have.', 'With she the form is has, not have.'],
  },
  {
    p: 'pc.duration', lv: 'B2', dom: 'biz',
    text: 'We have been migrating the archive to the cloud for six weeks now.',
    bad: null,
    ok: ['Kein Fehler: Eine laufende Tätigkeit mit Dauer (for six weeks) steht im Present Perfect Continuous.', 'No mistake: an ongoing activity with a duration (for six weeks) takes the present perfect continuous.'],
    fa: [['migrating', 'Hier ist -ing richtig, weil die Migration noch läuft und die Dauer zählt.', '-ing is right here because the migration is still running and the duration counts.']],
  },
  {
    p: 'pc.cont-simple', lv: 'B2', dom: 'biz',
    text: 'I have written three reports since Monday, and the fourth is nearly ready.',
    bad: null,
    ok: ['Kein Fehler: Bei einer Zahl (three reports) steht das Ergebnis im Present Perfect: have written.', 'No mistake: with a number (three reports) the result takes the present perfect: have written.'],
    fa: [['written', '„have been writing three reports“ wäre hier unpassend: Mit Zahl zählt das Ergebnis.', '“have been writing three reports” would be unsuitable here: with a number the result counts.']],
  },
  {
    p: 'pc.duration', lv: 'B2', dom: 'life',
    text: 'How long have you been working with the finance team in Cologne?',
    bad: null,
    ok: ['Kein Fehler: „How long“ fragt nach der Dauer bis jetzt: have you been working.', 'No mistake: “How long” asks for the duration up to now: have you been working.'],
    fa: [['have', 'Dauer bis jetzt = Present Perfect. „How long are you working“ wäre das Präsens-Deutsch.', 'Duration up to now = present perfect. “How long are you working” would be the German-style present.']],
  },
];
