// P18 Charge 4 (err 2): Kapitel 1 und 2 – future-forms, time-clauses, c1-hedging. 18 mit Fehler, 9 fehlerfrei.
export const meta = { file: 'k1-2', start: 28 };
export const items = [
  // ---- future-forms ----
  {
    p: 'ff.will-now', lv: 'B2', dom: 'biz',
    text: 'The printer is out of paper, so I order some more right away.',
    bad: { span: 'I order', fix: ['I will order', 'I’ll order', 'I am going to order', 'I’m going to order'], ch: ['I am order', 'I will ordered'] },
    ok: ['Ein spontaner Entschluss im Moment des Sprechens braucht will: I’ll order. Deutsch „ich bestelle“ nutzt das Präsens.', 'A spontaneous decision made while speaking needs will: I’ll order. German “ich bestelle” uses the present.'],
    c1: ['Nach am steht -ing, nicht die Grundform: „am order“ ist falsch.', 'After am comes -ing, not the base form: “am order” is wrong.'],
    c2: ['Nach will steht die Grundform: will order, nicht ordered.', 'After will comes the base form: will order, not ordered.'],
  },
  {
    p: 'ff.going-to', lv: 'B2', dom: 'biz', h: 1,
    text: 'We’re going to launching the new app in May, so please hold the date.',
    bad: { span: 'launching', fix: ['launch'], ch: ['launched', 'to launch'] },
    ok: ['Nach going to steht die Grundform: going to launch. Das -ing von „going“ rutscht oft ins nächste Verb.', 'After going to comes the base form: going to launch. The -ing of “going” often slips into the next verb.'],
    c1: ['Nach going to steht keine Vergangenheitsform: launch.', 'No past form follows going to: launch.'],
    c2: ['„to launch“ wäre doppelt: Das to steht schon in going to.', '“to launch” would double the to that is already in going to.'],
  },
  {
    p: 'ff.was-going-to', lv: 'B2', dom: 'biz',
    text: 'I am going to call the supplier yesterday, but I got pulled into a meeting.',
    bad: { span: 'am', fix: ['was'], ch: ['were', 'be'] },
    ok: ['Ein Plan, der in der Vergangenheit nicht zustande kam, braucht was going to. „Yesterday“ und „but“ zeigen es. Deutsch sagt „wollte anrufen“.', 'A plan that did not happen in the past needs was going to. “Yesterday” and “but” show it. German says “wollte anrufen”.'],
    c1: ['Zu I passt was, nicht were.', 'With I the form is was, not were.'],
    c2: ['„I be going to“ ist keine gültige Zeitform.', '“I be going to” is not a valid tense.'],
  },
  {
    p: 'ff.no-will-after', lv: 'B2', dom: 'biz', h: 1,
    text: 'I will send you the draft as soon as I will finish the summary.',
    bad: { span: 'will finish', fix: ['finish', 'have finished'], ch: ['am finishing', 'would finish'] },
    ok: ['Nach as soon as steht das Present, nie will, auch wenn es um die Zukunft geht. Das will gehört in den Hauptsatz.', 'After as soon as comes the present, never will, even for the future. The will belongs in the main clause.'],
    c1: ['„am finishing“ beschreibt etwas, das gerade läuft, nicht den Zeitpunkt danach.', '“am finishing” describes something in progress, not the moment afterwards.'],
    c2: ['„would finish“ verschiebt den Satz in eine Vergangenheit.', '“would finish” moves the sentence into a past frame.'],
  },
  {
    p: 'ff.about-to', lv: 'B2+', dom: 'biz', h: 1,
    text: 'Please take your seats, the keynote is about starting now.',
    bad: { span: 'about starting', fix: ['about to start', 'about to begin'], ch: ['about start', 'about starts'] },
    ok: ['Be about verlangt to + Grundform: is about to start. Deutsch „im Begriff sein, anzufangen“ wird mit about + Nomen verwechselt, deshalb folgt -ing.', 'Be about needs to + base form: is about to start. Learners confuse it with about + noun, so -ing follows.'],
    c1: ['Hinter about fehlt to.', 'to is missing after about.'],
    c2: ['Nach „is about“ steht to + Grundform, kein -s.', 'After “is about” comes to + base form, no -s.'],
  },
  {
    p: 'ff.no-will-after', lv: 'B2', dom: 'biz',
    text: 'Please don’t deploy before QA will give the green light.',
    bad: { span: 'will give', fix: ['gives', 'has given', '’s given'], ch: ['will have given', 'giving'] },
    ok: ['Nach before steht das Present (oder Present Perfect), nie will. Der Zeitsatz nennt nur den Moment, nicht die Zukunft.', 'After before comes the present (or present perfect), never will. The time clause only names the moment.'],
    c1: ['„will have given“ ist Futur II und passt nicht nach before.', '“will have given” is future perfect and does not fit after before.'],
    c2: ['„giving“ allein ist kein Prädikat.', '“giving” alone is no predicate.'],
  },
  {
    p: 'ff.will-now', lv: 'B2', dom: 'biz',
    text: 'I’ll call the client right now and confirm the new date.',
    bad: null,
    ok: ['Kein Fehler: Ein spontaner Entschluss im Moment des Sprechens steht mit will: I’ll call.', 'No mistake: a spontaneous decision made while speaking uses will: I’ll call.'],
    fa: [['I’ll', 'Hier ist will richtig, denn der Entschluss fällt jetzt. „I am going to call“ wäre ein schon geplanter Anruf.', 'Will is right here because the decision is made now. “I am going to call” would be a call already planned.']],
  },
  {
    p: 'ff.fixed-times', lv: 'B2', dom: 'biz',
    text: 'We’re meeting the board in Lisbon on Tuesday, and the flights are already booked.',
    bad: null,
    ok: ['Kein Fehler: Ein fest vereinbarter Termin mit schon gebuchten Flügen steht im Present Continuous: We’re meeting.', 'No mistake: a firmly arranged event with flights already booked takes the present continuous: We’re meeting.'],
    fa: [['meeting', 'Der Termin ist abgemacht, deshalb ist -ing richtig. „We will meet“ wäre auch möglich, aber weniger fest.', 'The event is arranged, so -ing is right. “We will meet” would be possible but less firm.']],
  },
  {
    p: 'ff.fixed-times', lv: 'B2', dom: 'biz',
    text: 'The train leaves at 6:15 tomorrow morning, so we should meet at the station by six.',
    bad: null,
    ok: ['Kein Fehler: Ein Fahrplan steht im Present Simple: The train leaves. Für Fahrpläne ist -ing nicht nötig.', 'No mistake: a timetable takes the present simple: The train leaves. No -ing is needed for timetables.'],
    fa: [['leaves', 'Fahrpläne und feste Programme nutzen das Present Simple. „is leaving“ wäre hier eher eine persönliche Absprache.', 'Timetables and fixed schedules use the present simple. “is leaving” would be more of a personal arrangement.']],
  },
  // ---- time-clauses ----
  {
    p: 'tc.present-for-future', lv: 'B2', dom: 'biz', h: 1,
    text: 'I will call you when I will arrive at the airport tomorrow.',
    bad: { span: 'will arrive', fix: ['arrive'], ch: ['arrived', 'arrives'] },
    ok: ['Nach when steht das Present, auch für die Zukunft. Das will gehört nur in den Hauptsatz (I will call).', 'After when comes the present, even for the future. The will belongs only in the main clause (I will call).'],
    c1: ['„arrived“ ist Vergangenheit, aber der Satz spricht von morgen.', '“arrived” is past, but the sentence talks about tomorrow.'],
    c2: ['Zu I passt arrive, nicht arrives.', 'With I the form is arrive, not arrives.'],
  },
  {
    p: 'tc.present-for-future', lv: 'B2', dom: 'biz', h: 1,
    text: 'We will start the demo as soon as the meeting will be over.',
    bad: { span: 'will be', fix: ['is', '’s'], ch: ['be', 'would be'] },
    ok: ['Nach as soon as steht das Present: as soon as the meeting is over. Deutsch „sobald es vorbei sein wird“ zieht das Futur in den Nebensatz.', 'After as soon as comes the present: as soon as the meeting is over. German pulls the future into the clause.'],
    c1: ['„be over“ ist keine finite Form: es fehlt is.', '“be over” is not a finite form: is is missing.'],
    c2: ['„would be“ verschiebt den Satz in die Vergangenheit.', '“would be” moves the sentence to the past.'],
  },
  {
    p: 'tc.present-perfect', lv: 'B2+', dom: 'biz', h: 1,
    text: 'Please don’t deploy until QA signed off on the release candidate.',
    bad: { span: 'signed off', fix: ['has signed off', '’s signed off', 'signs off'], ch: ['will sign off', 'signing off'] },
    ok: ['Nach until steht für etwas, das vorher fertig sein muss, das Present Perfect: has signed off. Auch das Present Simple (signs off) geht. Past Simple („signed off“) blickt auf einen Zeitpunkt in der Vergangenheit.', 'After until, something that must be finished first takes the present perfect: has signed off. The present simple (signs off) also works. The past simple points to a past moment.'],
    c1: ['Nach until steht nie will.', 'Never will after until.'],
    c2: ['„signing off“ allein ist kein Prädikat.', '“signing off” alone is no predicate.'],
  },
  {
    p: 'tc.by-the-time', lv: 'B2+', dom: 'biz', h: 1,
    text: 'Until our CFO joins the call, we will have finished the first agenda items.',
    bad: { span: 'Until', fix: ['By the time', 'Before'], ch: ['Since', 'Before then'] },
    ok: ['Bei einer Frist („bis dahin fertig“) steht by the time, nicht until. Until bedeutet „die ganze Zeit bis dahin“.', 'For a deadline (“done by then”) it is by the time, not until. Until means “all the time up to then”.'],
    c1: ['Since nennt einen Startpunkt, nicht eine Frist.', 'Since names a starting point, not a deadline.'],
    c2: ['„Before then“ lässt keinen Zeitsatz mit joins folgen.', '“Before then” cannot introduce a clause with joins.'],
  },
  {
    p: 'tc.noun-clause', lv: 'B2+', dom: 'biz', trapId: 'f20',
    text: 'I wonder when will the audit start next week.',
    bad: { span: 'will the audit', fix: ['the audit will'], ch: ['does the audit', 'the audit is'] },
    ok: ['In der indirekten Frage steht normale Satzstellung: when the audit will start. Die Frage-Umstellung gilt nur in der direkten Frage. Deutsch hat im Nebensatz das Verb am Ende, das verwirrt die Stellung.', 'In an indirect question the word order is normal: when the audit will start. Question order is only for direct questions.'],
    c1: ['„does the audit start“ bleibt in der Frage-Umstellung, die hier nicht gilt.', '“does the audit start” keeps the question order, which does not apply here.'],
    c2: ['„the audit is start“ mischt Hilfsverb und Grundform.', '“the audit is start” mixes auxiliary and base form.'],
  },
  {
    p: 'tc.present-for-future', lv: 'B2', dom: 'biz',
    text: 'When the audit will start next week, we will have everything ready.',
    bad: { span: 'will start', fix: ['starts'], ch: ['start', 'starting'] },
    ok: ['Nach when steht das Present: When the audit starts. Das zweite will gehört nur in den Hauptsatz.', 'After when comes the present: When the audit starts. The second will belongs only in the main clause.'],
    c1: ['Zu „the audit“ passt starts mit -s.', 'With “the audit” the form needs -s: starts.'],
    c2: ['„starting“ allein ist kein Prädikat.', '“starting” alone is no predicate.'],
  },
  {
    p: 'tc.present-for-future', lv: 'B2', dom: 'biz',
    text: 'I will forward the file as soon as I get the final numbers from finance.',
    bad: null,
    ok: ['Kein Fehler: Nach as soon as steht das Present: as soon as I get. will gehört nur in den Hauptsatz.', 'No mistake: after as soon as comes the present: as soon as I get. will belongs only in the main clause.'],
    fa: [['get', 'Hier ist das Present richtig. „as soon as I will get“ wäre der Fehler.', 'The present is right here. “as soon as I will get” would be the mistake.']],
  },
  {
    p: 'tc.present-perfect', lv: 'B2+', dom: 'biz',
    text: 'We will start the migration once the legal team has approved the contract.',
    bad: null,
    ok: ['Kein Fehler: Nach once steht das Present Perfect für das, was vorher erledigt sein muss.', 'No mistake: after once the present perfect marks what must be done first.'],
    fa: [['has', 'Present Perfect ist hier richtig: die Freigabe muss vor dem Start fertig sein. „will have approved“ wäre falsch.', 'The present perfect is right here: the approval must be done before the start. “will have approved” would be wrong.']],
  },
  {
    p: 'tc.noun-clause', lv: 'B2+', dom: 'biz',
    text: 'I wonder whether the client will accept our revised offer.',
    bad: null,
    ok: ['Kein Fehler: In einer indirekten ob-Frage bleibt will stehen: wonder whether … will accept.', 'No mistake: in an indirect whether-question will stays: wonder whether … will accept.'],
    fa: [['will', 'Hier gehört will hin, denn es ist eine Frage, keine Bedingung. Nach if als Bedingung wäre es falsch.', 'Will belongs here because this is a question, not a condition. After a conditional if it would be wrong.']],
  },
  // ---- c1-hedging ----
  {
    p: 'hg.modal', lv: 'B2+', dom: 'biz', h: 1,
    text: 'The new release will maybe be late because of the holiday freeze.',
    bad: { span: 'will maybe be', fix: ['might be', 'may be', 'could be', 'will probably be', 'will possibly be', 'may well be', 'might well be'], ch: ['maybe be', 'will might be'] },
    ok: ['„will maybe be“ klingt unidiomatisch. Zum Abschwächen nimmt man ein Modalverb: might be. Deutsch „wird vielleicht sein“ legt will + maybe nahe.', '“will maybe be” sounds unidiomatic. To soften, use a modal verb: might be. German “wird vielleicht sein” suggests will + maybe.'],
    c1: ['„maybe be“ ohne Modalverb ist ungrammatisch.', '“maybe be” without a modal is ungrammatical.'],
    c2: ['Zwei Modalverben (will might) gehen nicht zusammen.', 'Two modals (will might) cannot go together.'],
  },
  {
    p: 'hg.worth', lv: 'C1', dom: 'biz', h: 1,
    text: 'It might be worth to wait until Q3 before we sign the new contract.',
    bad: { span: 'to wait', fix: ['waiting', 'it to wait'], ch: ['wait', 'waited'] },
    ok: ['Direkt nach worth steht die -ing-Form: worth waiting (mit it: worth it to wait). Deutsch „es lohnt sich zu warten“ nutzt zu + Infinitiv.', 'Directly after worth comes the -ing form: worth waiting (with it: worth it to wait). German “es lohnt sich zu warten” uses zu + infinitive.'],
    c1: ['Nach worth steht nicht die Grundform.', 'The base form does not follow worth.'],
    c2: ['„waited“ ist Vergangenheit und passt nicht zu worth.', '“waited” is past and does not fit worth.'],
  },
  {
    p: 'hg.inclined', lv: 'C1', dom: 'biz', h: 1,
    text: 'I would be inclined choosing the cheaper vendor for the pilot.',
    bad: { span: 'choosing', fix: ['to choose', 'to go with'], ch: ['choose', 'to choosing'] },
    ok: ['Nach be inclined steht to + Grundform: inclined to choose. Das -ing wird nach Wendungen mit Adjektiv + Präposition oft übergeneralisiert.', 'After be inclined comes to + base form: inclined to choose. The -ing is often overgeneralized from adjective + preposition phrases.'],
    c1: ['Hinter inclined fehlt to.', 'to is missing after inclined.'],
    c2: ['Nach to steht die Grundform, nicht -ing.', 'After to comes the base form here, not -ing.'],
  },
  {
    p: 'hg.seems', lv: 'B2+', dom: 'biz', h: 1,
    text: 'It seems me that the timeline is too aggressive for a pilot.',
    bad: { span: 'seems me', fix: ['seems to me', 'appears to me'], ch: ['seems of me', 'seem me'] },
    ok: ['Die Person braucht im Englischen to: seems to me. Deutsch „es scheint mir“ nutzt den Dativ ohne Präposition.', 'The person needs to in English: seems to me. German “es scheint mir” uses the dative without a preposition.'],
    c1: ['„seems of me“ gibt es nicht.', '“seems of me” does not exist.'],
    c2: ['It braucht seems mit -s, nicht seem.', 'It needs seems with -s, not seem.'],
  },
  {
    p: 'hg.downtoner', lv: 'B2+', dom: 'biz',
    text: 'Your quote is a bit of high for our current budget, I am afraid.',
    bad: { span: 'a bit of high', fix: ['a bit high', 'a bit too high', 'a little high', 'a little too high', 'a touch too high', 'a bit on the high side'], ch: ['bit too high', 'a bit of too high'] },
    ok: ['a bit of gilt nur vor einem Nomen (a bit of a problem). Vor einem Adjektiv steht a bit direkt: a bit high.', 'A bit of only works before a noun (a bit of a problem). Before an adjective a bit stands directly: a bit high.'],
    c1: ['Ohne a fehlt der Artikel der Wendung.', 'Without a the phrase lacks its article.'],
    c2: ['„a bit of too high“ ist falsch, of bleibt weg.', '“a bit of too high” is wrong, of must go.'],
  },
  {
    p: 'hg.modal', lv: 'B2+', dom: 'biz',
    text: 'Our competitor could to lower its prices next quarter.',
    bad: { span: 'could to lower', fix: ['could lower', 'might lower', 'may lower'], ch: ['could lowering', 'could lowered'] },
    ok: ['Nach einem Modalverb steht die Grundform ohne to: could lower. Deutsch nutzt oft „zu“ nach Verben (versuchen zu, hoffen zu). Das wird auf Modalverben übertragen.', 'After a modal verb comes the base form without to: could lower. German often uses zu after verbs (versuchen zu, hoffen zu), and this is carried over to modals.'],
    c1: ['Nach could steht keine -ing-Form.', 'After could no -ing form follows.'],
    c2: ['Nach could steht keine Vergangenheitsform.', 'After could no past form follows.'],
  },
  {
    p: 'hg.worth', lv: 'C1', dom: 'biz',
    text: 'It might be worth involving legal before we sign the contract.',
    bad: null,
    ok: ['Kein Fehler: Nach worth steht -ing, also worth involving. Mit might wird die Empfehlung höflicher.', 'No mistake: worth is followed by -ing, so worth involving. With might the suggestion sounds more polite.'],
    fa: [['involving', 'Hier ist -ing richtig. „worth to involve“ wäre der Fehler.', '-ing is right here. “worth to involve” would be the mistake.']],
  },
  {
    p: 'hg.inclined', lv: 'C1', dom: 'biz',
    text: 'I would be inclined to wait until the audit is finished.',
    bad: null,
    ok: ['Kein Fehler: be inclined + to + Grundform: would be inclined to wait. Eine höfliche Abschwächung der eigenen Meinung.', 'No mistake: be inclined + to + base form: would be inclined to wait. A polite softening of your own view.'],
    fa: [['wait', 'Nach to steht hier die Grundform. „to waiting“ wäre der Fehler.', 'The base form follows to here. “to waiting” would be the mistake.']],
  },
  {
    p: 'hg.seems', lv: 'B2+', dom: 'biz',
    text: 'It seems that the budget is a little tight this year.',
    bad: null,
    ok: ['Kein Fehler: It seems that + Satz ist eine vorsichtige Einschätzung, und a little schwächt tight ab.', 'No mistake: It seems that + clause is a cautious assessment, and a little softens tight.'],
    fa: [['seems', 'Auch ohne to me ist seems that richtig: to steht nur, wenn eine Person genannt wird (seems to me / to John).', 'Seems that is also right without to me: to appears only when a person is named (seems to me / to John).']],
  },
];
