// P18 Charge 5 (err 3): Kapitel 2 – future-perf-cont, past-perfect, used-to. 18 mit Fehler, 9 fehlerfrei.
export const meta = { file: 'k1-3', start: 55 };
export const items = [
  // ---- future-perf-cont ----
  {
    p: 'fut.continuous', lv: 'B2+', dom: 'biz',
    text: 'This time tomorrow, I will be sit in the board meeting in Hamburg.',
    bad: { span: 'will be sit', fix: ['will be sitting'], ch: ['will sitting', 'be sitting'] },
    ok: ['Etwas, das zu einem künftigen Zeitpunkt gerade läuft, braucht will be + -ing: will be sitting. Deutsch „ich sitze dann“ hat keine Verlaufsform.', 'Something in progress at a future moment needs will be + -ing: will be sitting. German “ich sitze dann” has no continuous form.'],
    c1: ['Nach will fehlt be: will be sitting.', 'After will the be is missing: will be sitting.'],
    c2: ['„be sitting“ allein hat kein will, also keine Zukunft.', '“be sitting” alone has no will, so no future.'],
  },
  {
    p: 'fut.perfect', lv: 'C1', dom: 'biz',
    text: 'By Friday, we will already completed the migration to the new DMS.',
    bad: { span: 'will already completed', fix: ['will already have completed', 'will have already completed'], ch: ['will already completing', 'will already be completed'] },
    ok: ['Fertig bis zu einem künftigen Zeitpunkt: will have + 3. Form. Es fehlt have: will already have completed. Ein Futur II gibt es im Deutschen kaum („bis Freitag sind wir fertig“), deshalb fehlt das have.', 'Done by a future point: will have + participle. The have is missing: will already have completed. German hardly uses a future perfect, so the have is forgotten.'],
    c1: ['Nach will steht die Grundform (have), nicht -ing.', 'After will comes the base form (have), not -ing.'],
    c2: ['„will be completed“ wäre Passiv und passt nicht zu we.', '“will be completed” would be passive and does not fit we.'],
  },
  {
    p: 'fut.perfect', lv: 'C1', dom: 'biz',
    text: 'By the end of the quarter, the team will had closed forty new deals.',
    bad: { span: 'will had closed', fix: ['will have closed'], ch: ['will has closed', 'would had closed'] },
    ok: ['Nach will steht have, nicht had: will have closed. Das had rutscht aus der Vergangenheitsform hinein.', 'After will comes have, not had: will have closed. The had slips in from the past form.'],
    c1: ['Nach will steht have, nie has.', 'After will comes have, never has.'],
    c2: ['„would had“ mischt zwei Hilfsverben.', '“would had” mixes two auxiliaries.'],
  },
  {
    p: 'fut.perf-cont', lv: 'C1', dom: 'biz',
    text: 'By June, our team uses the new CRM for two years without any major outage.',
    bad: { span: 'uses', fix: ['will have been using'], ch: ['will been using', 'will have being using'] },
    ok: ['Dauer bis zu einem künftigen Zeitpunkt: will have been + -ing. Deutsch „im Juni nutzt unser Team es seit zwei Jahren“ nutzt dafür das Präsens.', 'Duration up to a future point: will have been + -ing. German “im Juni nutzt unser Team es seit zwei Jahren” uses the present.'],
    c1: ['„will been“ lässt have aus: will have been using.', '“will been” drops have: will have been using.'],
    c2: ['„having being“ ist keine gültige Form: nach have steht been.', '“have being” is not a valid form: have takes been.'],
  },
  {
    p: 'fut.perf-cont', lv: 'C1', dom: 'biz',
    text: 'By next April, I will have work at this company for ten years.',
    bad: { span: 'have work', fix: ['have worked', 'have been working'], ch: ['has worked', 'having work'] },
    ok: ['Nach will have steht die 3. Form (worked) oder been + -ing. Die Grundform work gehört nicht dahin.', 'After will have comes the participle (worked) or been + -ing. The base form work does not belong there.'],
    c1: ['Nach will steht have, nie has.', 'After will comes have, never has.'],
    c2: ['„will having“ gibt es nicht.', '“will having” does not exist.'],
  },
  {
    p: 'fut.continuous', lv: 'B2+', dom: 'biz',
    text: 'At 3 p.m., I’ll be present the roadmap to the board in the main conference room.',
    bad: { span: 'be present', fix: ['be presenting'], ch: ['be presented', 'presenting'] },
    ok: ['Die Handlung läuft um 3 Uhr: will be + -ing, also be presenting. „Präsentieren“ sieht wie „present“ aus, aber „be present“ heißt „anwesend sein“, und danach folgt kein Objekt.', 'The action is in progress at 3 p.m.: will be + -ing, so be presenting. “Be present” means “be there”, and no object follows.'],
    c1: ['„be presented“ wäre Passiv („wird präsentiert“), aber das Subjekt I präsentiert selbst.', '“be presented” would be passive, but the subject I presents itself.'],
    c2: ['„I’ll presenting“ lässt be aus.', '“I’ll presenting” drops be.'],
  },
  {
    p: 'fut.continuous', lv: 'B2+', dom: 'biz',
    text: 'This time next week, I will be sitting on a plane to Singapore.',
    bad: null,
    ok: ['Kein Fehler: Eine Handlung, die zu einem künftigen Zeitpunkt gerade läuft, steht mit will be + -ing.', 'No mistake: an action in progress at a future moment takes will be + -ing.'],
    fa: [['sitting', 'Hier ist -ing gewollt: zu diesem Zeitpunkt läuft der Flug. „will sit“ wäre eine einfache Zukunft ohne den Moment.', '-ing is intended here: the flight is in progress then. “will sit” would be a plain future without that moment.']],
  },
  {
    p: 'fut.perfect', lv: 'C1', dom: 'biz',
    text: 'By the time you land, I will have set up the demo environment.',
    bad: null,
    ok: ['Kein Fehler: Fertig bis zu einem Zeitpunkt (by the time you land) braucht will have + 3. Form.', 'No mistake: done by a point in time (by the time you land) takes will have + participle.'],
    fa: [['have', 'Hier gehört have hin: will have set up. „will set up“ würde keine Frist ausdrücken.', 'Have belongs here: will have set up. “will set up” would not express a deadline.']],
  },
  {
    p: 'fut.cont-plan', lv: 'B2+', dom: 'biz',
    text: 'Will you be attending the kickoff in Vienna next Wednesday?',
    bad: null,
    ok: ['Kein Fehler: Will you be + -ing ist die höfliche Frage nach Plänen.', 'No mistake: Will you be + -ing is the polite question about plans.'],
    fa: [['attending', 'Die -ing-Form macht die Frage freundlich. „Will you attend“ klingt direkter.', 'The -ing form makes the question friendly. “Will you attend” sounds more direct.']],
  },
  // ---- past-perfect ----
  {
    p: 'pp.duration', lv: 'B2+', dom: 'biz',
    text: 'When the inspector arrived, we have been waiting for two hours already.',
    bad: { span: 'have been waiting', fix: ['had been waiting'], ch: ['has been waiting', 'are waiting'] },
    ok: ['Die Erzählzeit ist Vergangenheit, also had been waiting. Have wäre die Gegenwart. Deutsch erzählt oft im Perfekt („wir haben schon zwei Stunden gewartet“), das lockt zu have.', 'The narrative is past, so had been waiting. Have would be the present. German often narrates in the perfect, which lures to have.'],
    c1: ['Zu we passt have/had, nicht has.', 'With we the auxiliary is have/had, not has.'],
    c2: ['„are waiting“ ist Gegenwart und passt nicht zu „arrived“.', '“are waiting” is present and does not fit “arrived”.'],
  },
  {
    p: 'pp.reported', lv: 'B2+', dom: 'biz',
    text: 'The client said that he would to confirm the order the following Monday.',
    bad: { span: 'would to confirm', fix: ['would confirm'], ch: ['would confirming', 'would confirmed'] },
    ok: ['Nach would steht die Grundform ohne to: would confirm. Das to kommt von Verben wie want oder need.', 'After would comes the base form without to: would confirm. The to comes from verbs like want or need.'],
    c1: ['Nach would steht keine -ing-Form.', 'After would no -ing form follows.'],
    c2: ['Nach would steht keine Vergangenheitsform.', 'After would no past form follows.'],
  },
  {
    p: 'pp.first-time', lv: 'C1', dom: 'biz',
    text: 'That was the first time our CEO has presented in Spanish to a client.',
    bad: { span: 'has presented', fix: ['had presented', 'presented'], ch: ['have presented', 'has present'] },
    ok: ['Nach „That was the first time“ in der Vergangenheit steht das Past Perfect: had presented (Past Simple geht im Alltag auch). Has wäre die Gegenwart.', 'After “That was the first time” in the past comes the past perfect: had presented (the past simple also works in everyday use). Has would be the present.'],
    c1: ['Zu our CEO passt has/had, nicht have.', 'With our CEO the auxiliary is has/had, not have.'],
    c2: ['Nach has steht die 3. Form (presented), nicht present.', 'After has comes the participle (presented), not present.'],
  },
  {
    p: 'pp.inversion', lv: 'C1', dom: 'biz',
    text: 'No sooner the CFO had left than the fire alarm went off.',
    bad: { span: 'the CFO had', fix: ['had the CFO'], ch: ['did the CFO', 'has the CFO'] },
    ok: ['Nach No sooner steht die Inversion: had vor dem Subjekt, also had the CFO left. Deutsch („Kaum war der CFO gegangen“) stellt ebenfalls um, im Englischen vergisst man es leicht.', 'After No sooner comes inversion: had before the subject, so had the CFO left. German also inverts (“Kaum war der CFO gegangen”), but it is easy to forget in English.'],
    c1: ['„did the CFO left“ mischt did mit der 3. Form.', '“did the CFO left” mixes did with the participle.'],
    c2: ['„has the CFO left“ ist Present Perfect, der Satz erzählt aber in der Vergangenheit.', '“has the CFO left” is present perfect, but the sentence narrates in the past.'],
  },
  {
    p: 'pp.duration', lv: 'B2+', dom: 'biz',
    text: 'We were waiting since eight when the inspector finally arrived.',
    bad: { span: 'were waiting', fix: ['had been waiting'], ch: ['have been waiting', 'had waiting'] },
    ok: ['Dauer vor einem Zeitpunkt in der Vergangenheit (since eight … arrived): had been waiting. Deutsch „wir warteten seit acht“ nutzt das Präteritum.', 'Duration before a past moment (since eight … arrived): had been waiting. German “wir warteten seit acht” uses the simple past.'],
    c1: ['„have been“ ist Gegenwartsbezug und passt nicht zu „arrived“.', '“have been” refers to the present and does not fit “arrived”.'],
    c2: ['„had waiting“ lässt been aus.', '“had waiting” drops been.'],
  },
  {
    p: 'pp.earlier', lv: 'B2', dom: 'biz',
    text: 'By the time we noticed the error, the invoice has already been sent.',
    bad: { span: 'has already been sent', fix: ['had already been sent', 'was already sent'], ch: ['was already been sent', 'have already been sent'] },
    ok: ['Was vor einem Moment in der Vergangenheit schon geschehen war, steht im Past Perfect: had already been sent. Has würde die Gegenwart betreffen.', 'What had already happened before a past moment takes the past perfect: had already been sent. Has would refer to the present.'],
    c1: ['„was … been“ mischt zwei Hilfsverben: entweder was sent oder had been sent.', '“was … been” mixes two auxiliaries: either was sent or had been sent.'],
    c2: ['Zu the invoice passt has/had, nicht have.', 'With the invoice the auxiliary is has/had, not have.'],
  },
  {
    p: 'pp.earlier', lv: 'B2', dom: 'biz',
    text: 'We had never worked with a German bank before that project started.',
    bad: null,
    ok: ['Kein Fehler: „Before that project started“ ist ein vergangener Zeitpunkt, davor steht had never worked im Past Perfect.', 'No mistake: “before that project started” is a past moment, and before it had never worked takes the past perfect.'],
    fa: [['had', 'Past Perfect ist hier richtig. „We never worked“ wäre auch möglich, hebt aber das „davor“ nicht hervor.', 'The past perfect is right here. “We never worked” would also be possible but does not stress the “before”.']],
  },
  {
    p: 'pp.reported', lv: 'B2+', dom: 'biz',
    text: 'I told her that I had already sent the invoice on Monday.',
    bad: null,
    ok: ['Kein Fehler: In der indirekten Rede rückt „I sent“ eine Stufe zurück zu had sent.', 'No mistake: in reported speech “I sent” moves one step back to had sent.'],
    fa: [['had', 'Hier gehört had hin, weil die Rede über etwas Vorvergangenes berichtet.', 'Had belongs here because the report is about something earlier than the telling.']],
  },
  {
    p: 'pp.inversion', lv: 'C1', dom: 'biz',
    text: 'Hardly had we signed the contract when the client asked for changes.',
    bad: null,
    ok: ['Kein Fehler: Hardly had we signed … when ist die förmliche Inversion, genau wie No sooner … than.', 'No mistake: Hardly had we signed … when is the formal inversion, just like No sooner … than.'],
    fa: [['had', 'Nach Hardly steht die Inversion (had we). „Hardly we had“ wäre falsch.', 'After Hardly comes inversion (had we). “Hardly we had” would be wrong.']],
  },
  // ---- used-to ----
  {
    p: 'ut.used-to', lv: 'B2', dom: 'biz', h: 1,
    text: 'We used to holding weekly all-hands meetings in the Cologne office.',
    bad: { span: 'used to holding', fix: ['used to hold'], ch: ['use to holding', 'used to held'] },
    ok: ['Nach used to steht die Grundform: used to hold. -ing gehört zu be used to. Das -ing kommt von be used to („ich bin es gewohnt, … zu halten“), das man mit used to verwechselt.', 'After used to comes the base form: used to hold. -ing belongs to be used to, which is easily confused.'],
    c1: ['„use to holding“ ist doppelt falsch: In der Bejahung heißt es used to, und danach steht die Grundform.', '“use to holding” is wrong twice: affirmative needs used to, then the base form.'],
    c2: ['Nach to steht die Grundform, keine Vergangenheit.', 'After to comes the base form, no past form.'],
  },
  {
    p: 'ut.would', lv: 'B2+', dom: 'biz',
    text: 'Back then, we would own a small office in Chicago and rent desks by the hour.',
    bad: { span: 'would own', fix: ['used to own'], ch: ['would owning', 'was own'] },
    ok: ['would geht nur mit Handlungen, die sich wiederholen. own als Besitz ist ein Zustand, dafür used to.', 'Would only works with repeated actions. Own is a state, so used to.'],
    c1: ['Nach would steht die Grundform, nicht -ing.', 'After would comes the base form, not -ing.'],
    c2: ['„was own“ ist keine Zeitform.', '“was own” is not a tense.'],
  },
  {
    p: 'ut.did-use-to', lv: 'B2+', dom: 'biz',
    text: 'Our CEO didn’t used to attend the weekly pipeline call before the merger.',
    bad: { span: 'didn’t used', fix: ['didn’t use', 'did not use'], ch: ['didn’t using', 'doesn’t use'] },
    ok: ['Nach didn’t steckt die Vergangenheit schon im Hilfsverb: didn’t use to, ohne -d. Die Vergangenheit wird doppelt markiert (didn’t + used).', 'After didn’t the past is already in the auxiliary: didn’t use to, without -d. The past is marked twice.'],
    c1: ['Nach didn’t steht die Grundform, nicht -ing.', 'After didn’t comes the base form, not -ing.'],
    c2: ['„doesn’t use“ ist Gegenwart und passt nicht zu „before the merger“.', '“doesn’t use” is present and does not fit “before the merger”.'],
  },
  {
    p: 'ut.be-used-to', lv: 'B2+', dom: 'biz',
    text: 'I am used to work across several time zones at the same time.',
    bad: { span: 'to work', fix: ['to working'], ch: ['to worked', 'working'] },
    ok: ['Nach be used to steht -ing, weil to hier eine Präposition ist: used to working. Deutsch „gewohnt zu arbeiten“ nutzt zu + Infinitiv.', 'After be used to comes -ing because to is a preposition here: used to working. German “gewohnt zu arbeiten” uses zu + infinitive.'],
    c1: ['Nach to steht hier keine Vergangenheit.', 'No past form after to here.'],
    c2: ['Ohne to fehlt die Wendung: be used to working.', 'Without to the phrase is incomplete: be used to working.'],
  },
  {
    p: 'ut.get-used-to', lv: 'B2+', dom: 'biz',
    text: 'It took the whole team months to be used to the new CRM.',
    bad: { span: 'to be used to', fix: ['to get used to', 'to become used to'], ch: ['to get use to', 'to be use to'] },
    ok: ['Der Vorgang des Gewöhnens heißt get used to, der Zustand be used to. „It took months“ zeigt den Vorgang. Deutsch „sich gewöhnen“ und „gewohnt sein“ sind verschiedene Wörter.', 'The process of getting accustomed is get used to, the state is be used to. “It took months” shows the process.'],
    c1: ['„use to“ ohne -d gibt es nur nach did(n’t).', '“use to” without -d exists only after did(n’t).'],
    c2: ['„use to“ ohne -d gibt es nur nach did(n’t).', '“use to” without -d exists only after did(n’t).'],
  },
  {
    p: 'ut.get-used-to', lv: 'B2+', dom: 'biz',
    text: 'After a few weeks I got used to use the new ticket system.',
    bad: { span: 'to use', fix: ['to using'], ch: ['to used', 'using'] },
    ok: ['Nach get used to steht -ing, weil to eine Präposition ist: got used to using.', 'After get used to comes -ing because to is a preposition: got used to using.'],
    c1: ['Nach to steht keine Vergangenheitsform.', 'No past form after to.'],
    c2: ['Ohne to fehlt die Wendung: got used to using.', 'Without to the phrase is incomplete: got used to using.'],
  },
  {
    p: 'ut.used-to', lv: 'B2', dom: 'biz',
    text: 'We used to hold weekly all-hands meetings, but now we meet once a month.',
    bad: null,
    ok: ['Kein Fehler: used to + Grundform beschreibt eine frühere Gewohnheit, die heute nicht mehr gilt.', 'No mistake: used to + base form describes a past habit that no longer applies.'],
    fa: [['hold', 'Nach used to steht die Grundform. „used to holding“ wäre der Fehler.', 'The base form follows used to. “used to holding” would be the mistake.']],
  },
  {
    p: 'ut.be-used-to', lv: 'B2+', dom: 'biz',
    text: 'I’m used to working under pressure, so tight deadlines don’t bother me.',
    bad: null,
    ok: ['Kein Fehler: be used to + -ing heißt „gewohnt sein“. -ing ist richtig, weil to hier eine Präposition ist.', 'No mistake: be used to + -ing means “be accustomed”. -ing is right because to is a preposition here.'],
    fa: [['working', 'Hier ist -ing richtig. „used to work“ wäre die Vergangenheitsgewohnheit mit anderer Bedeutung.', '-ing is right here. “used to work” would be the past habit with a different meaning.']],
  },
  {
    p: 'ut.did-use-to', lv: 'B2+', dom: 'biz',
    text: 'Did you use to work at a bank before you joined us?',
    bad: null,
    ok: ['Kein Fehler: In Fragen steht use ohne -d, weil did die Vergangenheit trägt: Did you use to work.', 'No mistake: in questions use has no -d because did carries the past: Did you use to work.'],
    fa: [['use', 'Nach Did steht use, nicht used. „Did you used to“ wäre der Fehler.', 'After Did comes use, not used. “Did you used to” would be the mistake.']],
  },
];
