// P18 Charge 6 (err 4): Kapitel 2 (c1-diplomacy) und Kapitel 3 – conditionals, cond-alt, mixed-cond. 27 mit Fehler, 12 fehlerfrei.
export const meta = { file: 'k1-4', start: 82 };
export const items = [
  // ---- c1-diplomacy ----
  {
    p: 'dip.wondering', lv: 'C1', dom: 'biz',
    text: 'I was wondering if could you confirm the venue by Friday.',
    bad: { span: 'could you confirm', fix: ['you could confirm', 'you can confirm'], ch: ['you could confirmed', 'could you confirmed'] },
    ok: ['Nach wondering if steht normale Satzstellung: you could confirm, keine Frage-Umstellung. Deutsch „ob du bestätigen könntest“ hat Verb am Ende, das verwirrt die Stellung.', 'After wondering if comes normal word order: you could confirm, not question order.'],
    c1: ['Nach could steht die Grundform: could confirm.', 'After could comes the base form: could confirm.'],
    c2: ['Mit could vorn bleibt die Frage-Umstellung, und confirmed ist falsch.', 'Question order stays with could first, and confirmed is wrong.'],
  },
  {
    p: 'dip.wondering', lv: 'C1', dom: 'biz',
    text: 'I was wondering whether you would be able sending me the agenda before Monday.',
    bad: { span: 'able sending', fix: ['able to send'], ch: ['able send', 'able to sending'] },
    ok: ['Be able braucht to + Grundform: able to send. Deutsch „in der Lage sein zu senden“ nutzt zu + Infinitiv, das -ing drängt sich von anderen Wendungen auf.', 'Be able needs to + base form: able to send. German uses zu + infinitive; the -ing comes from other phrases.'],
    c1: ['Hinter able fehlt to.', 'to is missing after able.'],
    c2: ['Nach to steht die Grundform, nicht -ing.', 'After to comes the base form, not -ing.'],
  },
  {
    p: 'dip.hoping', lv: 'B2+', dom: 'biz',
    text: 'We were hoping getting your feedback by the end of the day.',
    bad: { span: 'getting', fix: ['to get', 'to receive'], ch: ['get', 'to getting'] },
    ok: ['Nach hope steht to + Grundform: hoping to get. Deutsch „hofften, zu bekommen“ nutzt zu + Infinitiv. -ing kommt von Verben wie enjoy.', 'After hope comes to + base form: hoping to get. -ing comes from verbs like enjoy.'],
    c1: ['Hinter hoping fehlt to.', 'to is missing after hoping.'],
    c2: ['Nach to steht die Grundform, nicht -ing.', 'After to comes the base form, not -ing.'],
  },
  {
    p: 'dip.hoping', lv: 'B2+', dom: 'biz',
    text: 'We were hoping for to hear from you before the end of the week.',
    bad: { span: 'for to hear', fix: ['to hear'], ch: ['for hearing', 'for hear'] },
    ok: ['Entweder hoping to hear oder hoping for a reply. „For to“ geht im Englischen nicht. Deutsch „hoffen auf“ und „hoffen, zu“ werden hier vermischt.', 'Either hoping to hear or hoping for a reply. “For to” is not possible in English.'],
    c1: ['Nach hoping steht für etwas Konkretes „for + Nomen“, hier fehlt das Nomen.', '“for + noun” names something concrete, but here the noun is missing.'],
    c2: ['Nach for steht ein Nomen oder -ing, aber hier ist die Wendung hoping to hear gemeint.', 'After for comes a noun; the intended phrase is hoping to hear.'],
  },
  {
    p: 'dip.possible', lv: 'B2+', dom: 'biz',
    text: 'Would it possible to move the demo to Thursday morning?',
    bad: { span: 'it possible', fix: ['it be possible'], ch: ['be possible', 'it is possible'] },
    ok: ['Nach would fehlt das be: Would it be possible. Deutsch „Wäre es möglich“ trägt das „sein“ im Wort „wäre“.', 'After would the be is missing: Would it be possible. German carries “sein” inside “wäre”.'],
    c1: ['Ohne it fehlt das Subjekt.', 'Without it the subject is missing.'],
    c2: ['Nach would steht die Grundform be, nicht is.', 'After would comes the base form be, not is.'],
  },
  {
    p: 'dip.understate', lv: 'B2+', dom: 'biz', h: 1,
    text: 'That deadline would be a bit challenge for our small team.',
    bad: { span: 'a bit challenge', fix: ['a bit of a challenge', 'a bit challenging', 'a little challenging', 'a little bit of a challenge', 'a little bit challenging'], ch: ['a bit of challenge', 'bit a challenge'] },
    ok: ['Mit Nomen heißt es a bit of a challenge, mit Adjektiv a bit challenging. „A bit challenge“ mischt beides.', 'With a noun it is a bit of a challenge, with an adjective a bit challenging. “A bit challenge” mixes both.'],
    c1: ['Nach a bit of braucht das Nomen einen Artikel: a challenge.', 'After a bit of the noun needs an article: a challenge.'],
    c2: ['Die Reihenfolge ist a bit, nicht bit a.', 'The order is a bit, not bit a.'],
  },
  {
    p: 'dip.understate', lv: 'C1', dom: 'biz',
    text: 'That would be bit of stretch for our team in the current quarter.',
    bad: { span: 'bit of stretch', fix: ['a bit of a stretch', 'a little bit of a stretch'], ch: ['a bit of stretch', 'bit a stretch'] },
    ok: ['Die höfliche Abschwächung ist das Idiom a bit of a stretch, mit beiden Artikeln. Deutsch „ein bisschen Anstrengung“ hat keine Artikel, deshalb fallen sie weg.', 'The polite softener is the idiom a bit of a stretch, with both articles. German “ein bisschen Anstrengung” has no articles, so they get dropped.'],
    c1: ['Vor stretch fehlt der zweite Artikel: a bit of a stretch.', 'The second article is missing before stretch: a bit of a stretch.'],
    c2: ['Die Reihenfolge ist a bit of a, nicht bit a.', 'The order is a bit of a, not bit a.'],
  },
  {
    p: 'dip.wondering', lv: 'C1', dom: 'biz',
    text: 'I was wondering if you could confirm the venue before Friday.',
    bad: null,
    ok: ['Kein Fehler: was wondering if you could … ist die höfliche Bitte mit Abstand durch die Vergangenheitsform.', 'No mistake: was wondering if you could … is the polite request, with distance from the past tense.'],
    fa: [['could', 'Hier ist could richtig, weil nach if keine Frageform folgt. „could you“ wäre der Fehler.', 'Could is right here because no question order follows if. “could you” would be the mistake.']],
  },
  {
    p: 'dip.hoping', lv: 'B2+', dom: 'biz',
    text: 'We were hoping to get your feedback before the end of the week.',
    bad: null,
    ok: ['Kein Fehler: were hoping to + Grundform ist die höfliche Form eines Wunsches.', 'No mistake: were hoping to + base form is the polite form of a wish.'],
    fa: [['hoping', 'Die Vergangenheit macht den Wunsch höflicher. „We hope“ klingt direkter.', 'The past tense makes the wish more polite. “We hope” sounds more direct.']],
  },
  {
    p: 'dip.possible', lv: 'B2+', dom: 'biz',
    text: 'Would it be possible to share the slides before the meeting starts?',
    bad: null,
    ok: ['Kein Fehler: Would it be possible + to + Grundform ist die höfliche Frage nach einer Möglichkeit.', 'No mistake: Would it be possible + to + base form is the polite question about a possibility.'],
    fa: [['possible', 'Hier ist possible richtig. „possibly“ wäre das falsche Wort.', 'Possible is right here. “possibly” would be the wrong word.']],
  },
  // ---- conditionals ----
  {
    p: 'cn.zero', lv: 'B2', dom: 'biz',
    text: 'Under our policy, if an invoice arrives after the cutoff, it would be processed on the next working day.',
    bad: { span: 'would be processed', fix: ['is processed', 'will be processed', 'gets processed', 'will get processed', '’ll be processed'], ch: ['are processed', 'would processed'] },
    ok: ['Eine feste Regel oder echte Möglichkeit braucht im Hauptsatz das Present oder will: is processed. would passt zu unwirklichen Fällen.', 'A fixed rule or real possibility takes the present or will in the main clause: is processed. Would fits unreal cases.'],
    c1: ['Zu it passt is, nicht are.', 'With it the form is is, not are.'],
    c2: ['„would processed“ lässt be aus.', '“would processed” drops be.'],
  },
  {
    p: 'cn.first', lv: 'B2', dom: 'biz', h: 1,
    text: 'If the client will sign the quote today, we will start next week.',
    bad: { span: 'will sign', fix: ['signs', 'has signed'], ch: ['is sign', 'signing'] },
    ok: ['Nach if steht bei echter Zukunft das Present: If the client signs. Das will gehört in den Hauptsatz. Deutsch „wenn der Kunde unterschreiben wird“ zieht will in den if-Satz.', 'After if comes the present for a real future: If the client signs. The will belongs in the main clause.'],
    c1: ['„is sign“ mischt Hilfsverb und Grundform.', '“is sign” mixes auxiliary and base form.'],
    c2: ['„signing“ allein ist kein Prädikat.', '“signing” alone is no predicate.'],
  },
  {
    p: 'cn.second', lv: 'B2+', dom: 'biz', h: 1,
    text: 'If our team would have more capacity, we would take on the new client.',
    bad: { span: 'would have', fix: ['had'], ch: ['having', 'would had'] },
    ok: ['Im if-Teil steht die Past-Form, kein would: If our team had. Deutsch „wenn wir mehr hätten“ klingt nach „würden haben“.', 'The if-clause takes the past form, no would: If our team had. German “wenn wir mehr hätten” sounds like “würden haben”.'],
    c1: ['„having“ allein ist kein Prädikat.', '“having” alone is no predicate.'],
    c2: ['„would had“ mischt zwei Formen.', '“would had” mixes two forms.'],
  },
  {
    p: 'cn.were', lv: 'B2+', dom: 'biz', h: 1,
    text: 'If I would be in your position, I would ask for a raise.',
    bad: { span: 'would be', fix: ['were', 'was'], ch: ['being', 'would being'] },
    ok: ['Für Rat und Annahme steht nach if were, nicht would be. Deutsch „wenn ich wäre“ klingt nach „würde sein“.', 'For advice and assumptions were follows if, not would be. German “wenn ich wäre” sounds like “würde sein”.'],
    c1: ['„being“ allein ist kein Prädikat.', '“being” alone is no predicate.'],
    c2: ['„would being“ gibt es nicht.', '“would being” does not exist.'],
  },
  {
    p: 'cn.third', lv: 'B2+', dom: 'biz',
    text: 'If the vendor would have warned us, we would have changed the order.',
    bad: { span: 'would have warned', fix: ['had warned'], ch: ['would warned', 'has warned'] },
    ok: ['Im if-Teil steht had + 3. Form, nicht would have: If the vendor had warned. Would have gehört in den Hauptsatz.', 'The if-clause takes had + participle, not would have: If the vendor had warned. Would have belongs in the main clause.'],
    c1: ['„would warned“ lässt have aus.', '“would warned” drops have.'],
    c2: ['Has passt nicht zu einer Vergangenheit mit would have im Hauptsatz.', 'Has does not fit a past reference with would have in the main clause.'],
  },
  {
    p: 'cn.if-words', lv: 'B2+', dom: 'biz', h: 1,
    text: 'We will agree to the discount provided that you will order at least 500 units.',
    bad: { span: 'will order', fix: ['order'], ch: ['ordering', 'would order'] },
    ok: ['Nach provided that steht das Present, nicht will. Deutsch „vorausgesetzt, Sie werden bestellen“ zieht will in den Nebensatz.', 'After provided that comes the present, not will. German “vorausgesetzt, Sie werden bestellen” pulls will in.'],
    c1: ['„ordering“ allein ist kein Prädikat.', '“ordering” alone is no predicate.'],
    c2: ['„would order“ ist hypothetisch; nach provided that steht das Present.', '“would order” is hypothetical; the present follows provided that.'],
  },
  {
    p: 'cn.third', lv: 'B2+', dom: 'biz',
    text: 'If we had tested earlier, we would caught the bug before the release.',
    bad: { span: 'would caught', fix: ['would have caught', 'would’ve caught'], ch: ['would catching', 'would have catch'] },
    ok: ['Im Hauptsatz einer unerfüllten Vergangenheit steht would have + 3. Form. Es fehlt have: would have caught.', 'In the main clause of an unreal past comes would have + participle. The have is missing: would have caught.'],
    c1: ['Nach would steht die Grundform, nicht -ing.', 'After would comes the base form, not -ing.'],
    c2: ['Nach would have steht die 3. Form (caught), nicht catch.', 'After would have comes the participle (caught), not catch.'],
  },
  {
    p: 'cn.zero', lv: 'B2', dom: 'biz',
    text: 'If an order arrives after 5 p.m., it ships the next working day.',
    bad: null,
    ok: ['Kein Fehler: Eine feste Regel steht im Present Simple in beiden Teilen: arrives … ships.', 'No mistake: a fixed rule takes the present simple in both parts: arrives … ships.'],
    fa: [['ships', 'Das Present ist hier richtig, es ist eine Regel. „would ship“ wäre der Fehler.', 'The present is right here because it is a rule. “would ship” would be the mistake.']],
  },
  {
    p: 'cn.were', lv: 'B2+', dom: 'biz',
    text: 'If I were you, I would ask for a raise before the review.',
    bad: null,
    ok: ['Kein Fehler: If I were you ist die feste Wendung für einen Rat.', 'No mistake: If I were you is the set phrase for advice.'],
    fa: [['were', 'Nach if steht bei I formal were. „was“ wäre in dieser Wendung unüblich.', 'After if with I the formal form is were. “was” would be unusual in this phrase.']],
  },
  {
    p: 'cn.if-words', lv: 'B2+', dom: 'biz',
    text: 'We will accept the revised terms provided that you pay within thirty days.',
    bad: null,
    ok: ['Kein Fehler: Nach provided that steht das Present: provided that you pay.', 'No mistake: after provided that comes the present: provided that you pay.'],
    fa: [['pay', 'Das Present ist hier richtig. „will pay“ wäre der Fehler.', 'The present is right here. “will pay” would be the mistake.']],
  },
  // ---- cond-alt ----
  {
    p: 'ca.unless', lv: 'B2+', dom: 'biz', h: 1,
    text: 'Unless you don’t sign the contract today, the offer will expire tonight.',
    bad: { span: 'don’t sign', fix: ['sign'], ch: ['didn’t sign', 'won’t sign'] },
    ok: ['Unless bedeutet schon „wenn nicht“. Eine zweite Verneinung dreht den Sinn um: Unless you sign. Deutsch „wenn du nicht unterschreibst“ legt die Verneinung nahe, aber unless enthält sie schon.', 'Unless already means “if not”. A second negation reverses the meaning: Unless you sign.'],
    c1: ['„didn’t sign“ verneint ein zweites Mal und ist Vergangenheit.', '“didn’t sign” negates a second time and is past.'],
    c2: ['„won’t sign“ ist ebenfalls verneint.', '“won’t sign” is also negated.'],
  },
  {
    p: 'ca.as-long-as', lv: 'B2+', dom: 'biz', h: 1,
    text: 'As long as it will not rain, we will hold the client event outside.',
    bad: { span: 'will not rain', fix: ['doesn’t rain', 'does not rain', 'isn’t raining', 'is not raining'], ch: ['not rain', 'no rain'] },
    ok: ['Nach as long as steht das Present, nicht will. Deutsch „solange es nicht regnen wird“ zieht das Futur nach.', 'After as long as comes the present, not will. German pulls the future in.'],
    c1: ['Das Verb braucht ein Hilfsverb: does not rain.', 'The verb needs an auxiliary: does not rain.'],
    c2: ['„no rain“ ist ein Nomen und kein Verb.', '“no rain” is a noun and no verb.'],
  },
  {
    p: 'ca.otherwise', lv: 'B2+', dom: 'biz',
    text: 'Otherwise you confirm the venue this week, we can’t hold the event.',
    bad: { span: 'Otherwise you confirm', fix: ['Unless you confirm', 'If you don’t confirm'], ch: ['Unless you don’t confirm', 'If you confirm'] },
    ok: ['Otherwise steht allein als Satzanfang („sonst“), nicht als Bindewort. Hier passt Unless oder If … don’t.', 'Otherwise stands alone as a sentence opening (“or else”), not as a conjunction. Here Unless or If … don’t fits.'],
    c1: ['„Unless you don’t“ verneint doppelt.', '“Unless you don’t” negates twice.'],
    c2: ['„If you confirm“ kehrt den Sinn um: dann könnte man die Veranstaltung halten.', '“If you confirm” reverses the meaning: then the event could be held.'],
  },
  {
    p: 'ca.but-for', lv: 'C1', dom: 'biz',
    text: 'But for your help last week, we would miss yesterday’s launch.',
    bad: { span: 'would miss', fix: ['would have missed', 'would’ve missed'], ch: ['would missed', 'had missed'] },
    ok: ['Das Ereignis (yesterday’s launch) liegt in der Vergangenheit, also would have + 3. Form: would have missed. But for ersetzt If it had not been for.', 'The event (yesterday’s launch) lies in the past, so would have + participle: would have missed. But for replaces If it had not been for.'],
    c1: ['„would missed“ lässt have aus.', '“would missed” drops have.'],
    c2: ['„had missed“ gibt es hier nicht: nach But for steht would have.', '“had missed” is not possible here: But for takes would have.'],
  },
  {
    p: 'ca.inversion', lv: 'C1', dom: 'biz',
    text: 'Had we known about the audit, we had planned the release differently.',
    bad: { span: 'we had planned', fix: ['we would have planned', 'we would’ve planned'], ch: ['we planned', 'we would planned'] },
    ok: ['Nach der Inversion (Had we known) steht im Hauptsatz would have + 3. Form: we would have planned.', 'After the inversion (Had we known) the main clause takes would have + participle: we would have planned.'],
    c1: ['Past Simple trägt keinen Konditional-Sinn.', 'The past simple carries no conditional meaning.'],
    c2: ['„would planned“ lässt have aus.', '“would planned” drops have.'],
  },
  {
    p: 'ca.inversion', lv: 'C1', dom: 'biz',
    text: 'Should you will have any questions, please call me directly.',
    bad: { span: 'will have', fix: ['have'], ch: ['to have', 'having'] },
    ok: ['Nach Should you steht die Grundform: Should you have. Das will ist doppelt, die Inversion ersetzt schon das if.', 'After Should you comes the base form: Should you have. The will is redundant because the inversion already replaces if.'],
    c1: ['Nach should steht kein to.', 'After should no to follows.'],
    c2: ['„having“ allein ist kein Prädikat.', '“having” alone is no predicate.'],
  },
  {
    p: 'ca.in-case', lv: 'B2+', dom: 'biz', h: 1,
    text: 'I will bring a printed copy in case the projector will fail.',
    bad: { span: 'will fail', fix: ['fails', 'should fail', 'were to fail'], ch: ['fail', 'to fail'] },
    ok: ['Nach in case steht das Present (oder should): in case the projector fails. Das will gehört nicht in den Nebensatz.', 'After in case comes the present (or should): in case the projector fails. The will does not belong in the clause.'],
    c1: ['Nach in case steht ein finites Verb mit -s: fails.', 'After in case comes a finite verb with -s: fails.'],
    c2: ['„to fail“ gibt es nach in case nicht.', '“to fail” is not possible after in case.'],
  },
  {
    p: 'ca.unless', lv: 'B2+', dom: 'biz',
    text: 'We will ship on Monday unless the client objects to the date.',
    bad: null,
    ok: ['Kein Fehler: Unless steht mit der bejahten Form: unless the client objects.', 'No mistake: unless takes the affirmative form: unless the client objects.'],
    fa: [['objects', 'Hier ist objects richtig, weil unless schon „wenn nicht“ enthält. „doesn’t object“ wäre doppelt verneint.', 'Objects is right because unless already holds “if not”. “doesn’t object” would be double negation.']],
  },
  {
    p: 'ca.as-long-as', lv: 'B2+', dom: 'biz',
    text: 'Staff may work remotely as long as they attend the Monday team sync.',
    bad: null,
    ok: ['Kein Fehler: Nach as long as steht das Present: as long as they attend.', 'No mistake: after as long as comes the present: as long as they attend.'],
    fa: [['attend', 'Das Present ist hier richtig. „will attend“ wäre der Fehler.', 'The present is right here. “will attend” would be the mistake.']],
  },
  {
    p: 'ca.inversion', lv: 'C1', dom: 'biz',
    text: 'Had we known about the delay earlier, we would have rescheduled the launch.',
    bad: null,
    ok: ['Kein Fehler: Had we known ist die förmliche Inversion von If we had known, danach would have + 3. Form.', 'No mistake: Had we known is the formal inversion of If we had known, followed by would have + participle.'],
    fa: [['Had', 'Hier steht Had zuerst, ohne if: genau die richtige Inversion.', 'Had comes first without if: exactly the right inversion.']],
  },
  // ---- mixed-cond ----
  {
    p: 'mc.wish-past', lv: 'C1', dom: 'biz', h: 1,
    text: 'I wish I would have asked for a written quote before the call.',
    bad: { span: 'would have asked', fix: ['had asked'], ch: ['would asked', 'have asked'] },
    ok: ['Nach wish steht für die Vergangenheit had + 3. Form: had asked. Deutsch „ich wünschte, ich hätte gefragt“ verleitet zu would have.', 'After wish the past takes had + participle: had asked. German “ich wünschte, ich hätte gefragt” invites would have.'],
    c1: ['„would asked“ lässt have aus.', '“would asked” drops have.'],
    c2: ['Nach wish I steht had, nicht have.', 'After wish I comes had, not have.'],
  },
  {
    p: 'mc.wish-now', lv: 'B2+', dom: 'biz',
    text: 'I wish I have more capacity for another client right now.',
    bad: { span: 'have', fix: ['had'], ch: ['having', 'would have'] },
    ok: ['Nach wish geht die Zeit eine Stufe zurück: have wird zu had. Ein Wunsch für jetzt braucht die Past-Form.', 'After wish the tense moves one step back: have becomes had. A wish about now takes the past form.'],
    c1: ['„having“ allein ist kein Prädikat.', '“having” alone is no predicate.'],
    c2: ['Nach wish steht für jetzt kein would have.', 'After wish, would have is wrong for a wish about now.'],
  },
  {
    p: 'mc.wish-would', lv: 'B2+', dom: 'biz',
    text: 'I wish our colleagues will update the shared calendar every day.',
    bad: { span: 'will update', fix: ['would update', 'updated'], ch: ['updating', 'would updating'] },
    ok: ['Nach wish steht would, nie will: wish + would + Grundform drückt Ärger über eine Gewohnheit aus (auch wish + Past ist möglich).', 'After wish comes would, never will: wish + would + base form expresses annoyance at a habit.'],
    c1: ['„updating“ allein ist kein Prädikat.', '“updating” alone is no predicate.'],
    c2: ['Nach would steht die Grundform, nicht -ing.', 'After would comes the base form, not -ing.'],
  },
  {
    p: 'mc.past-cond', lv: 'C1', dom: 'biz', h: 1,
    text: 'If we would have automated the invoicing, we would spend less time on it now.',
    bad: { span: 'would have automated', fix: ['had automated'], ch: ['would automated', 'have automated'] },
    ok: ['Im if-Teil steht had + 3. Form, would have gehört nicht dorthin: If we had automated. Das „now“ im Hauptsatz passt zu would spend.', 'The if-clause takes had + participle, not would have: If we had automated. The “now” in the main clause fits would spend.'],
    c1: ['„would automated“ lässt have aus.', '“would automated” drops have.'],
    c2: ['Nach if steht hier had, nicht have.', 'After if comes had here, not have.'],
  },
  {
    p: 'mc.present-cond', lv: 'C1', dom: 'biz',
    text: 'If our team would be larger, we would have won the bid last quarter.',
    bad: { span: 'would be', fix: ['were', 'was'], ch: ['be', 'being'] },
    ok: ['Im if-Teil steht kein would: If our team were larger. Das would have won im Hauptsatz erklärt die Folge in der Vergangenheit.', 'The if-clause takes no would: If our team were larger. The would have won in the main clause gives the past result.'],
    c1: ['„be“ gibt es nur in festen Formeln (If that be the case). Hier steht nach if were.', '“be” only occurs in set phrases (If that be the case). Here were follows if.'],
    c2: ['„being“ allein ist kein Prädikat.', '“being” alone is no predicate.'],
  },
  {
    p: 'mc.high-time', lv: 'C1', dom: 'biz', h: 1,
    text: 'It’s high time we replace the old server before it fails again.',
    bad: { span: 'replace', fix: ['replaced'], ch: ['replacing', 'will replace'] },
    ok: ['Nach It’s high time steht die Past-Form, obwohl es um jetzt geht: we replaced. Deutsch „es ist höchste Zeit, dass wir ersetzen“ nutzt das Präsens.', 'After It’s high time comes the past form, although it is about now: we replaced. German uses the present.'],
    c1: ['„replacing“ allein ist kein Prädikat.', '“replacing” alone is no predicate.'],
    c2: ['„will replace“ ist Zukunft, aber die Wendung verlangt die Past-Form.', '“will replace” is future, but the phrase takes the past form.'],
  },
  {
    p: 'mc.wish-past', lv: 'C1', dom: 'biz',
    text: 'I wish I had asked for a written quote before the call.',
    bad: null,
    ok: ['Kein Fehler: Bedauern über die Vergangenheit steht nach wish mit had + 3. Form.', 'No mistake: regret about the past takes had + participle after wish.'],
    fa: [['had', 'Hier ist had richtig. „would have asked“ wäre der Fehler.', 'Had is right here. “would have asked” would be the mistake.']],
  },
  {
    p: 'mc.present-cond', lv: 'C1', dom: 'biz',
    text: 'If our team were bigger, we would have won the bid last quarter.',
    bad: null,
    ok: ['Kein Fehler: Der Zustand jetzt steht im if-Teil mit were, die Folge in der Vergangenheit im Hauptsatz mit would have won.', 'No mistake: the state now takes were in the if-clause, the past result takes would have won in the main clause.'],
    fa: [['were', 'Hier ist were richtig. „would be“ im if-Teil wäre der Fehler.', 'Were is right here. “would be” in the if-clause would be the mistake.']],
  },
  {
    p: 'mc.high-time', lv: 'C1', dom: 'biz',
    text: 'It’s high time we replaced the old server before it fails again.',
    bad: null,
    ok: ['Kein Fehler: Nach It’s high time steht die Past-Form: we replaced, obwohl es um jetzt geht.', 'No mistake: after It’s high time comes the past form: we replaced, although it is about now.'],
    fa: [['replaced', 'Hier ist die Past-Form gewollt. „we replace“ wäre der Fehler.', 'The past form is intended here. “we replace” would be the mistake.']],
  },
];
