// P18 Charge 1: kwt, Kapitel 1 (Zeiten) und hedging. Felder: p Muster · lead Satz A · key · before/after Satz B ·
// a/b Teil A/B (v = weitere ganze Varianten) · x Ablenker · traps [Text, DE, EN] · ok [DE, EN] (Teil 1 · Teil 2).
export const meta = { file: 'k1-1', start: 1 };
export const items = [
  // ---- pres-simple-cont ----
  {
    p: 'psc.always', lv: 'B2+', dom: 'biz',
    lead: 'It annoys me that our vendor keeps changing the delivery dates.', key: 'ALWAYS',
    before: 'Our vendor', after: 'the delivery dates.', a: ['is always'], b: ['changing'], x: ['changes', 'has', 'keeps'],
    traps: [['is changing always', 'Im Deutschen steht „immer“ oft hinten. Englisch: always steht zwischen is und -ing.', 'German often puts “immer” last. In English always goes between is and -ing.']],
    ok: ['Teil 1: always steht nach is und vor dem Verb. Teil 2: -ing drückt den Ärger über die ständige Wiederholung aus.', 'Part 1: always sits between is and the verb. Part 2: -ing shows annoyance at the constant repetition.'],
  },
  {
    p: 'psc.state', lv: 'B2', dom: 'biz',
    lead: 'A quick decision from the client is essential for us.', key: 'REALLY',
    before: 'We', after: 'a quick decision from the client.', a: ['really need', 'really want'], b: ['to get', 'to have', 'to receive'], x: ['wanting', 'are', 'much'],
    traps: [['are really needing to get', 'Deutsch hat nur eine Präsensform. Englisch: need und want sind Zustandsverben und haben kein -ing.', 'German has only one present form. In English need and want are state verbs and take no -ing.']],
    ok: ['Teil 1: really need/want, Zustandsverben stehen im Present Simple, nie in der -ing-Form. Teil 2: to get, danach to + Grundform.', 'Part 1: really need/want, state verbs take the present simple, never -ing. Part 2: to get, to + base form follows.'],
  },
  {
    p: 'psc.now', lv: 'B2', dom: 'biz',
    lead: 'Our team is normally based in Cork, but this week it is in the Dublin office.', key: 'TEMPORARILY',
    before: 'This week our team', after: 'from the Dublin office.', a: ['is temporarily'], b: ['working'],
    v: [{ a: ['is'], b: ['working temporarily'] }], x: ['works', 'was', 'usually'],
    traps: [['works here temporarily', 'Deutsch sagt „arbeitet“ auch für Vorübergehendes. Englisch: vorübergehend = is working.', 'German uses “arbeitet” for temporary things too. In English temporary means is working.']],
    ok: ['Teil 1: temporarily passt zu einer vorübergehenden Lage. Teil 2: is working (Continuous), weil es nur diese Woche gilt, nicht dauerhaft.', 'Part 1: temporarily fits a short-term situation. Part 2: is working (continuous) because it only applies this week, not permanently.'],
  },
  {
    p: 'psc.habit', lv: 'B2', dom: 'biz',
    lead: 'In meetings, our CEO does not take notes at any time.', key: 'NEVER',
    before: 'Our CEO', after: 'in meetings.', a: ['never'], b: ['takes notes', 'takes any notes'], x: ['is', 'take', 'taking'],
    traps: [['is never taking notes', 'Deutsch hat nur eine Präsensform. Gewohnheit heißt im Englischen Present Simple; -ing wäre nur dieser Moment.', 'German has one present form. A habit takes the present simple in English; -ing would be this one moment only.']],
    ok: ['Teil 1: never steht vor dem Verb. Teil 2: Gewohnheit = Present Simple, bei he/she/it mit -s: takes notes.', 'Part 1: never goes before the verb. Part 2: a habit takes the present simple, with -s for he/she/it: takes notes.'],
  },
  // ---- past-simple-perfect ----
  {
    p: 'psp.finished-time', lv: 'B2', dom: 'biz', trapId: 'f22',
    lead: 'When was the contract signed by the client?', key: 'DID',
    before: 'When', after: 'the contract?', a: ['did'], b: ['the client sign', 'the customer sign'], x: ['has', 'signed', 'does'],
    traps: [['did the client signed', 'Nach did steht die Grundform: did … sign. Deutsch „hat unterschrieben“ trägt die Vergangenheit im Verb.', 'After did comes the base form: did … sign. German “hat unterschrieben” carries the past in the verb.']],
    ok: ['Teil 1: did + Grundform fragt im Past Simple. Teil 2: sign (Grundform), nicht signed. „When“ fragt nach einem Zeitpunkt.', 'Part 1: did + base form asks in the past simple. Part 2: sign (base form), not signed. “When” asks for a point in time.'],
  },
  {
    p: 'psp.since-for', lv: 'B2', dom: 'biz', trapId: 'f12',
    lead: 'We began working with Rhein Logistics in 2019, and we still work with them.', key: 'SINCE',
    before: 'We', after: '2019.', a: ['have worked'], b: ['with them since', 'together since', 'with Rhein since'],
    v: [{ a: ['have been working'], b: ['with them since', 'together since'] }], x: ['for', 'are', 'work'],
    traps: [['worked with them since', 'Past Simple endet in der Vergangenheit. Dauer bis heute (seit 2019) braucht have worked.', 'The past simple ends in the past. Duration up to now (since 2019) needs have worked.'], ['are working with them since', 'Deutsch: „seit 2019 arbeiten wir“ (Präsens). Englisch: Dauer bis jetzt = have worked / have been working.', 'German: “seit 2019 arbeiten wir” (present). English: duration up to now = have worked / have been working.']],
    ok: ['Teil 1: have worked / have been working, weil es bis heute dauert. Teil 2: since + Jahreszahl, since nennt den Startpunkt.', 'Part 1: have worked / have been working because it lasts until now. Part 2: since + year, since names the starting point.'],
  },
  {
    p: 'psp.experience', lv: 'B2+', dom: 'biz',
    lead: 'I have never seen a smoother DMS migration.', key: 'EVER',
    before: 'It is the smoothest DMS migration I', after: '.', a: ['have ever'], b: ['seen', 'experienced', 'encountered'], x: ['saw', 'did', 'never'],
    traps: [['have seen ever', 'ever steht zwischen have und der 3. Form. Deutsch stellt „je“ gern ans Ende.', 'Ever goes between have and the participle. German likes “je” at the end.']],
    ok: ['Teil 1: have ever, denn Superlativ + ever blickt auf das ganze bisherige Leben. Teil 2: die 3. Form (seen).', 'Part 1: have ever, because superlative + ever looks at your whole experience so far. Part 2: the past participle (seen).'],
  },
  {
    p: 'psp.result-now', lv: 'B2', dom: 'biz',
    lead: 'I sent the invoice a few minutes ago.', key: 'JUST',
    before: 'I', after: 'the invoice.', a: ['have just'], b: ['sent'], x: ['send', 'did', 'was'],
    traps: [['have sent just', 'Hinter dem Verb hieße just „nur“. „Gerade eben“ steht zwischen have und der 3. Form.', 'After the verb just would mean “only”. “A moment ago” goes between have and the participle.']],
    ok: ['Teil 1: have just zeigt: gerade eben passiert, Folge jetzt. Teil 2: sent als 3. Form.', 'Part 1: have just shows it happened a moment ago with a result now. Part 2: sent as the past participle.'],
  },
  {
    p: 'psp.experience', lv: 'B2+', dom: 'life',
    lead: 'I have never given a talk in English before today.', key: 'FIRST',
    before: 'This is the', after: 'a talk in English.', a: ['first time'], b: ['I have given', 'I have ever given', 'that I have given'], x: ['I give', 'I gave', 'before'],
    traps: [['first time I give', 'Deutsch: „das erste Mal, dass ich halte“ im Präsens. Englisch: the first time + Present Perfect.', 'German: “das erste Mal, dass ich halte” in the present. English: the first time + present perfect.']],
    ok: ['Teil 1: first time. Teil 2: I have given, denn nach „the first time“ steht das Present Perfect.', 'Part 1: first time. Part 2: I have given, because the present perfect follows “the first time”.'],
  },
  // ---- pres-perf-cont ----
  {
    p: 'pc.duration', lv: 'B2', dom: 'biz', trapId: 'f12',
    lead: 'We started testing the beta module in March and are still testing it.', key: 'BEEN',
    before: 'We', after: 'the beta module since March.', a: ['have been'], b: ['testing'], x: ['tested', 'are', 'test'],
    traps: [['have been tested', 'Mit -ed wäre es Passiv („wurde getestet“). Die laufende Tätigkeit seit März braucht -ing.', 'With -ed it would be passive (“was tested”). The activity running since March needs -ing.']],
    ok: ['Teil 1: have been, weil es seit März bis jetzt läuft. Teil 2: testing, die -ing-Form betont die Dauer der Tätigkeit.', 'Part 1: have been, because it has run from March until now. Part 2: testing, the -ing form stresses the ongoing activity.'],
  },
  {
    p: 'pc.since-for', lv: 'B2', dom: 'biz',
    lead: 'When did you start using the DMS?', key: 'LONG',
    before: 'How', after: 'the DMS?', a: ['long have you'], b: ['been using', 'used'], x: ['did', 'since', 'for'],
    traps: [['long do you use', 'Deutsch: „Wie lange benutzt du …?“ im Präsens. Englisch fragt dafür mit have you been using oder used.', 'German: “Wie lange benutzt du …?” in the present. English asks it with have you been using or used.']],
    ok: ['Teil 1: long have you, weil „how long“ bis jetzt gilt. Teil 2: been using oder used (3. Form), nicht using allein.', 'Part 1: long have you, since “how long” runs up to now. Part 2: been using or used (participle), not using alone.'],
  },
  {
    p: 'pc.duration', lv: 'B2', dom: 'biz',
    lead: 'I have spent the whole afternoon on the contract.', key: 'ALL',
    before: 'I', after: 'on the contract.', a: ['have been working'], b: ['all afternoon'], v: [{ a: ['have worked'], b: ['all afternoon'] }, { a: ['have spent'], b: ['all afternoon working'] }], x: ['whole', 'is', 'am'],
    traps: [['am working all afternoon', 'Deutsch „ich arbeite den ganzen Nachmittag“ ist Präsens. Wenn der Nachmittag schon vergangen ist, braucht Englisch have been working.', 'German “ich arbeite den ganzen Nachmittag” is present. If the afternoon is already over, English needs have been working.']],
    ok: ['Teil 1: have been working, die Arbeit begann früher und ist gerade vorbei oder läuft noch. Teil 2: all afternoon nennt die Dauer.', 'Part 1: have been working, the work started earlier and has just stopped or continues. Part 2: all afternoon names the duration.'],
  },
  {
    p: 'pc.state-verbs', lv: 'B2', dom: 'life',
    lead: 'I met her ten years ago and we are still in touch.', key: 'FOR',
    before: 'I', after: 'ten years.', a: ['have known'], b: ['her for'], x: ['know', 'knew', 'since'],
    traps: [['have been knowing her for', 'Deutsch „ich kenne sie seit zehn Jahren“ ist Präsens. Englisch: know ist ein Zustandsverb, also have known, nie have been knowing.', 'German “ich kenne sie seit zehn Jahren” is present. English: know is a state verb, so have known, never have been knowing.']],
    ok: ['Teil 1: have known, Zustandsverben haben keine -ing-Form. Teil 2: her for, for + Zeitraum nennt die Dauer bis heute.', 'Part 1: have known, state verbs take no -ing form. Part 2: her for, for + period names the duration up to now.'],
  },
  {
    p: 'pc.recent', lv: 'B2', dom: 'life',
    lead: 'I have been feeling unwell over the past few days.', key: 'LATELY',
    before: 'I', after: '.', a: ['have not felt'], b: ['well lately'], v: [{ a: ['have not been'], b: ['feeling well lately'] }, { a: ['have felt'], b: ['unwell lately'] }, { a: ['have been'], b: ['feeling unwell lately'] }], x: ['recently', 'feel', 'sick'],
    traps: [['do not feel well lately', 'Deutsch: „In letzter Zeit fühle ich mich nicht gut“ im Präsens. Englisch: lately + Present Perfect.', 'German: “In letzter Zeit fühle ich mich nicht gut” in the present. English: lately + present perfect.']],
    ok: ['Teil 1: have not felt / have not been feeling, weil die Zeit bis jetzt reicht. Teil 2: well lately, lately passt nur zum Present Perfect.', 'Part 1: have not felt / have not been feeling, since the period runs up to now. Part 2: well lately, lately only goes with the present perfect.'],
  },
  // ---- future-forms ----
  {
    p: 'ff.will-now', lv: 'B2', dom: 'biz',
    lead: 'Do you want me to book the conference room for Thursday?', key: 'SHOULD',
    before: '', after: 'the conference room for Thursday?', a: ['Should I'], b: ['book', 'reserve'], x: ['Will', 'Do', 'Am'],
    traps: [['Should I booked', 'Nach Should I steht die Grundform: book, nicht booked. Deutsch „Soll ich gebucht“ gibt es nicht, die Form hängt am Hilfsverb.', 'After Should I comes the base form: book, not booked.']],
    ok: ['Teil 1: Should I bietet etwas an („soll ich?“). Teil 2: book steht in der Grundform, nach Should I folgt nie to.', 'Part 1: Should I makes an offer (“soll ich?”). Part 2: book is the base form, to never follows Should I.'],
  },
  {
    p: 'ff.going-to', lv: 'B2', dom: 'biz',
    lead: 'We plan to roll out the new CRM in September.', key: 'GOING',
    before: 'We', after: 'out the new CRM in September.', a: ['are going to'], b: ['roll'], x: ['will', 'plan', 'rolling'],
    traps: [['are going roll', 'Vor der Grundform fehlt to: going to roll. Deutsch „werden … ausrollen“ hat kein Wort dafür.', 'To is missing before the base form: going to roll. German “werden … ausrollen” has no word for it.']],
    ok: ['Teil 1: are going to drückt einen festen Plan aus. Teil 2: roll als Grundform (going to + Grundform).', 'Part 1: are going to expresses a firm plan. Part 2: roll as base form (going to + base form).'],
  },
  {
    p: 'ff.was-going-to', lv: 'B2', dom: 'biz',
    lead: 'I planned to call the supplier yesterday, but I ran out of time.', key: 'WAS',
    before: 'I', after: 'the supplier yesterday, but I ran out of time.', a: ['was going to', 'was planning to', 'was intending to'], b: ['call', 'phone'], x: ['am', 'would', 'did'],
    traps: [['was going call', 'Vor der Grundform fehlt to. Deutsch „ich wollte anrufen“ kennt kein Wort dafür.', 'To is missing before the base form. German “ich wollte anrufen” has no word for it.']],
    ok: ['Teil 1: was going to, weil der Plan in der Vergangenheit lag und nicht zustande kam. Teil 2: call als Grundform.', 'Part 1: was going to, because the plan lay in the past and did not happen. Part 2: call as base form.'],
  },
  {
    p: 'ff.fixed-times', lv: 'B2', dom: 'biz',
    lead: 'I have agreed to meet the client in Lisbon on Tuesday.', key: 'MEETING',
    before: 'I', after: 'in Lisbon on Tuesday.', a: ['am meeting'], b: ['the client', 'with the client'], x: ['will', 'meet', 'going'],
    traps: [['meeting the client', 'Das Hilfsverb fehlt: am meeting. Deutsch „ich treffe“ braucht keins.', 'The auxiliary is missing: am meeting. German “ich treffe” needs none.']],
    ok: ['Teil 1: am meeting, die -ing-Form beschreibt einen vereinbarten Termin. Teil 2: the client als Objekt.', 'Part 1: am meeting, the -ing form describes an agreed arrangement. Part 2: the client as the object.'],
  },
  {
    p: 'ff.about-to', lv: 'B2+', dom: 'biz',
    lead: 'The CEO will begin her keynote any second.', key: 'ABOUT',
    before: 'The CEO', after: 'her keynote.', a: ['is about', 'is just about'], b: ['to begin', 'to start'], x: ['will', 'going', 'soon'],
    traps: [['is about begin', 'Nach about braucht Englisch to + Grundform. Deutsch hat dafür „gleich … beginnen“ ohne Wörtchen dazwischen.', 'English needs to + base form after about. German just says “gleich … beginnen”.']],
    ok: ['Teil 1: is about, die Wendung steht für „gleich“. Teil 2: to begin, nach be about steht immer to + Grundform.', 'Part 1: is about, the phrase stands for “right away”. Part 2: to begin, be about is always followed by to + base form.'],
  },
  // ---- time-clauses ----
  {
    p: 'tc.present-for-future', lv: 'B2', dom: 'biz', trapId: 'f11',
    lead: 'I will not forward the file before I get the final numbers.', key: 'UNTIL',
    before: 'I will not forward the file', after: 'the final numbers.', a: ['until'], b: ['I get', 'I have', 'I receive', 'I have got', 'I have received', 'I have gotten'], x: ['by', 'will', 'when'],
    traps: [['until I will get', 'Im Hauptsatz steht will, und es rutscht in den until-Satz. Nach until steht das Präsens.', 'Will from the main clause slips into the until-clause. The present follows until.']],
    ok: ['Teil 1: until bis zu einem Ereignis (bei by wäre es eine Frist). Teil 2: I get, nach until steht das Present, nie will.', 'Part 1: until runs up to an event (by would mean a deadline). Part 2: I get, the present follows until, never will.'],
  },
  {
    p: 'tc.present-perfect', lv: 'B2+', dom: 'biz',
    lead: 'We can start the migration after the legal team has approved the contract.', key: 'ONCE',
    before: 'We can start the migration', after: 'the contract.', a: ['once'], b: ['the legal team has approved', 'legal has approved', 'the legal team approves', 'legal approves'], x: ['when', 'will', 'after'],
    traps: [['once the legal team will approve', 'Das will des Hauptsatzes rutscht in den once-Satz. Nach once steht kein will.', 'The will of the main clause slips into the once-clause. No will after once.']],
    ok: ['Teil 1: once heißt „sobald“. Teil 2: has approved (oder approves): nach once steht Present Perfect oder Present, nie will.', 'Part 1: once means “as soon as”. Part 2: has approved (or approves): present perfect or present follows once, never will.'],
  },
  {
    p: 'tc.by-the-time', lv: 'B2+', dom: 'biz',
    lead: 'We will have completed the migration before the audit starts.', key: 'TIME',
    before: 'We will have completed the migration', after: 'the audit starts.', a: ['by the'], b: ['time'], x: ['until', 'when', 'moment'],
    traps: [['until the time', 'Mit until würde die Handlung bis dahin laufen. „Bis dahin fertig“ ist im Englischen by the time.', 'Until would mean the action lasts up to then. “Done by then” is by the time in English.']],
    ok: ['Teil 1: by the markiert eine Frist („bis dahin fertig“). Teil 2: time, danach steht das Present (starts).', 'Part 1: by the marks a deadline (“done by then”). Part 2: time, the present (starts) follows.'],
  },
  {
    p: 'tc.noun-clause', lv: 'B2+', dom: 'biz',
    lead: 'Will the client sign before Friday? I am not sure.', key: 'WONDER',
    before: 'I', after: 'before Friday.', a: ['wonder if', 'wonder whether'], b: ['the client will sign'], x: ['wondering', 'signs', 'asked'],
    traps: [['wonder if the client signs', 'Deutsch nutzt im ob-Satz das Präsens: „ob der Kunde unterschreibt“. Englisch: nach wonder if bleibt will, wenn es um die Zukunft geht.', 'German uses the present in an ob-clause. In English will stays after wonder if when the future is meant.']],
    ok: ['Teil 1: wonder if/whether, eine indirekte Frage. Teil 2: will sign, in einer ob-Frage bleibt will, anders als nach when oder if im Bedingungssatz.', 'Part 1: wonder if/whether, an indirect question. Part 2: will accept, will stays in an if-question, unlike in an if-condition.'],
  },
  // ---- c1-hedging ----
  {
    p: 'hg.modal', lv: 'B2+', dom: 'biz',
    lead: 'It is possible that our competitor will lower its prices soon.', key: 'MIGHT',
    before: 'Our competitor', after: 'prices soon.', a: ['might', 'might well'], b: ['lower its', 'cut its', 'reduce its', 'lower their', 'cut their', 'reduce their'], x: ['will', 'maybe', 'possible'],
    traps: [['might lowering its', 'Nach might steht die Grundform: might lower. Das -ing passt hier nicht.', 'The base form follows might: might lower. The -ing form does not fit.']],
    ok: ['Teil 1: might macht die Aussage vorsichtig. Teil 2: lower its (Grundform + Besitz), will fällt weg.', 'Part 1: might makes the statement cautious. Part 2: lower its (base form + possessive), will drops out.'],
  },
  {
    p: 'hg.worth', lv: 'C1', dom: 'biz',
    lead: 'I suggest that we talk to the security team before the launch.', key: 'WORTH',
    before: 'It might', after: 'to the security team before the launch.', a: ['be worth'], b: ['talking', 'speaking', 'reaching out'], x: ['worthy', 'to talk', 'valuable'],
    traps: [['be worth to talk', 'Deutsch: „es lohnt sich, mit dem Team zu sprechen“ mit zu + Infinitiv. Nach worth steht im Englischen immer -ing.', 'German: “es lohnt sich, mit dem Team zu sprechen” with zu + infinitive. After worth English always takes -ing.']],
    ok: ['Teil 1: be worth, höflicher Vorschlag mit might. Teil 2: talking, nach worth immer die -ing-Form.', 'Part 1: be worth, a polite suggestion with might. Part 2: talking, worth is always followed by the -ing form.'],
  },
  {
    p: 'hg.inclined', lv: 'C1', dom: 'biz',
    lead: 'I lean towards postponing the rollout until January.', key: 'INCLINED',
    before: 'I', after: 'the rollout until January.', a: ['would be inclined', 'am inclined'], b: ['to postpone', 'to delay', 'to push back', 'to put off'], x: ['inclining', 'postponing', 'will'],
    traps: [['would be inclined postponing', 'Nach be inclined steht to + Grundform. Das -ing wird oft von „worth“ übertragen.', 'Be inclined takes to + base form. The -ing is often carried over from “worth”.']],
    ok: ['Teil 1: would be inclined, die höfliche Abschwächung der eigenen Meinung. Teil 2: to postpone, danach steht to + Grundform.', 'Part 1: would be inclined, the polite softening of your own view. Part 2: to postpone, to + base form follows.'],
  },
  {
    p: 'hg.seems', lv: 'B2+', dom: 'biz',
    lead: 'In my view, the timeline is unrealistic.', key: 'SEEMS',
    before: 'It', after: 'the timeline is unrealistic.', a: ['seems'], b: ['to me that', 'to me', 'to me as if'], x: ['seem', 'seeming', 'looks'],
    traps: [['seems me that', 'Deutsch: „es scheint mir“ ohne Präposition (Dativ). Englisch: seems to me, mit to.', 'German “es scheint mir” takes the dative without a preposition. English: seems to me, with to.']],
    ok: ['Teil 1: seems, ein vorsichtiger Eindruck. Teil 2: to me (that), die Person braucht im Englischen to.', 'Part 1: seems, a cautious impression. Part 2: to me (that), the person needs to in English.'],
  },
  {
    p: 'hg.downtoner', lv: 'B2+', dom: 'biz',
    lead: 'The offer is slightly above what we can pay.', key: 'BIT',
    before: 'The offer is', after: 'what we can pay.', a: ['a bit', 'just a bit', 'a little bit'], b: ['above', 'over', 'higher than', 'more than', 'beyond'], x: ['slightly', 'somewhat', 'pretty'],
    traps: [['a bit above of', 'Nach above folgt direkt der Vergleichswert, kein of. Deutsch „ein bisschen über von“ verleitet zu of.', 'The compared value follows above directly, no of. German habits invite an extra of.']],
    ok: ['Teil 1: a bit macht die Kritik weicher. Teil 2: above (oder over/higher than) nennt den Vergleich.', 'Part 1: a bit softens the criticism. Part 2: above (or over/higher than) names the comparison.'],
  },
];
