// P18 Charge 2: kwt, Kapitel 2 (future-perf-cont, past-perfect, used-to, c1-diplomacy) und Kapitel 3 (Bedingungen).
export const meta = { file: 'k1-2', start: 29 };
export const items = [
  // ---- future-perf-cont ----
  {
    p: 'fut.continuous', lv: 'B2+', dom: 'biz',
    lead: 'My presentation of the quarterly numbers to the board runs from eight to ten tomorrow.', key: 'BE',
    before: 'At nine tomorrow, I', after: 'the quarterly numbers to the board.', a: ['will be'], b: ['presenting', 'showing'], v: [{ a: ['am going to be'], b: ['presenting'] }], x: ['being', 'presented', 'present'],
    traps: [['will be present', 'Ohne -ing hieße es „anwesend sein“. Mitten in einer Handlung zu einem künftigen Zeitpunkt braucht Englisch will be + -ing.', 'Without -ing it would mean “be there”. An action in progress at a future time needs will be + -ing.']],
    ok: ['Teil 1: will be, Handlung in der Zukunft. Teil 2: presenting (-ing), denn um neun ist die Präsentation gerade im Gang.', 'Part 1: will be, a future action. Part 2: presenting (-ing), because at nine the presentation is in progress.'],
  },
  {
    p: 'fut.cont-plan', lv: 'B2+', dom: 'biz',
    lead: 'Do you intend to come to the client workshop in May?', key: 'WILL',
    before: '', after: 'the client workshop in May?', a: ['Will you'], b: ['be attending', 'be joining', 'be coming to', 'be going to', 'attend', 'come to', 'be taking part in'], x: ['Are', 'Do', 'Shall'],
    traps: [['Will you attending', 'Nach will fehlt be: Will you be attending. Deutsch „wirst du teilnehmen“ hat kein Hilfsverb be.', 'After will the be is missing: Will you be attending. German “wirst du teilnehmen” has no be.']],
    ok: ['Teil 1: Will you fragt nach der Zukunft. Teil 2: be attending (oder attend), be + -ing fragt freundlich nach dem Plan.', 'Part 1: Will you asks about the future. Part 2: be attending (or attend), be + -ing asks about plans in a friendly way.'],
  },
  {
    p: 'fut.perfect', lv: 'C1', dom: 'biz',
    lead: 'I will set up the demo environment before the client lands.', key: 'ALREADY',
    before: 'By the time the client lands, I', after: 'the demo environment.', a: ['will already'], b: ['have set up', 'have prepared', 'have built'], v: [{ a: ['will have already'], b: ['set up', 'prepared', 'built'] }], x: ['am', 'did', 'finished'],
    traps: [['will already set up', 'Deutsch: „bis dahin richte ich es ein“ im Präsens oder Futur. Fertig bis zu einem Zeitpunkt braucht Englisch will have + 3. Form.', 'German uses the present or future for “done by then”. English needs will have + past participle.']],
    ok: ['Teil 1: will already, die Handlung ist vorher erledigt. Teil 2: have set up (will have + 3. Form), by the time zeigt eine Frist.', 'Part 1: will already, the action is finished beforehand. Part 2: have set up (will have + past participle), by the time marks a deadline.'],
  },
  {
    p: 'fut.perf-cont', lv: 'C1', dom: 'biz',
    lead: 'In March it will be three years since we signed with this client.', key: 'BEEN',
    before: 'In March, I', after: 'with this client for three years.', a: ['will have been'], b: ['working', 'dealing', 'doing business', 'collaborating', 'partnering'], x: ['was', 'having', 'worked'],
    traps: [['will have been work', 'Nach been steht -ing, nicht die Grundform. Deutsch „gearbeitet haben“ kennt nur ein Partizip.', 'After been comes -ing, not the base form. German “gearbeitet haben” has only one participle.']],
    ok: ['Teil 1: will have been, die Zeit läuft bis zu einem künftigen Punkt. Teil 2: working (-ing), for three years nennt die Dauer.', 'Part 1: will have been, the time runs up to a future point. Part 2: working (-ing), for three years names the duration.'],
  },
  // ---- past-perfect ----
  {
    p: 'pp.earlier', lv: 'B2', dom: 'biz',
    lead: 'The client signed off on the budget before our CFO joined the call.', key: 'ALREADY',
    before: 'When our CFO joined the call, the client', after: 'the budget.', a: ['had already'], b: ['approved', 'accepted', 'signed off on', 'agreed to'], x: ['has', 'was', 'did'],
    traps: [['has already approved', 'Deutsch: „der Kunde hat schon genehmigt“ mit Perfekt. In einer Vergangenheitserzählung braucht Englisch had, nicht has.', 'German uses its perfect. In a past narrative English needs had, not has.']],
    ok: ['Teil 1: had already, die Handlung geschah vor dem Anruf. Teil 2: approved (3. Form), so entsteht das Past Perfect.', 'Part 1: had already, the action happened before the call. Part 2: approved (participle), which forms the past perfect.'],
  },
  {
    p: 'pp.duration', lv: 'B2+', dom: 'biz',
    lead: 'We started waiting at eight, and the inspector arrived at ten.', key: 'BEEN',
    before: 'When the inspector arrived, we', after: 'for two hours.', a: ['had been'], b: ['waiting'], x: ['were', 'waited', 'have'],
    traps: [['have been waiting', 'Die Erzählzeit ist Vergangenheit: had been, nicht have been. Deutsch „wir warteten seit zwei Stunden“ lockt zu have.', 'The narrative is in the past: had been, not have been. German “wir warteten seit zwei Stunden” lures to have.']],
    ok: ['Teil 1: had been, das Warten begann vor der Ankunft. Teil 2: waiting (-ing), for two hours nennt die Dauer.', 'Part 1: had been, the waiting began before the arrival. Part 2: waiting (-ing), for two hours names the duration.'],
  },
  {
    p: 'pp.first-time', lv: 'C1', dom: 'biz',
    lead: 'I had never negotiated a contract in German before that meeting.', key: 'FIRST',
    before: 'That meeting was the', after: 'a contract in German.', a: ['first time'], b: ['I had negotiated', 'I had ever negotiated', 'I negotiated'], v: [{ a: ['first time that'], b: ['I had negotiated', 'I negotiated'] }], x: ['I have', 'I was', 'before'],
    traps: [['first time I have negotiated', 'Die Erzählzeit bleibt in der Vergangenheit: nach „was“ passt have nicht. Deutsch „das erste Mal, dass ich verhandelt habe“ lockt.', 'The narrative stays in the past: have does not fit after “was”. German “das erste Mal, dass ich verhandelt habe” lures.']],
    ok: ['Teil 1: first time. Teil 2: I had negotiated (einfaches I negotiated geht auch): Past Perfect betont das Davor.', 'Part 1: first time. Part 2: I had negotiated (plain I negotiated also works): the past perfect stresses the earlier event.'],
  },
  {
    p: 'pp.reported', lv: 'B2+', dom: 'biz',
    lead: 'My manager told me: “I will send the report tomorrow.”', key: 'WOULD',
    before: 'My manager told me she', after: 'the next day.', a: ['would'], b: ['send the report', 'send it', 'be sending the report', 'send me the report', 'send over the report'], x: ['will', 'sends', 'sent'],
    traps: [['would sent it', 'Auch im Deutschen folgt der Infinitiv („würde schicken“). Im Englischen steht die Grundform ohne to und ohne Endung.', 'After would comes the bare base form, with no to and no ending.']],
    ok: ['Teil 1: would, will wird in der indirekten Rede zu would. Teil 2: send the report, danach folgt die Grundform.', 'Part 1: would, will becomes would in reported speech. Part 2: send the report, the base form follows.'],
  },
  {
    p: 'pp.inversion', lv: 'C1', dom: 'biz',
    lead: 'As soon as the CFO sat down, the fire alarm went off.', key: 'SOONER',
    before: 'No', after: 'down than the fire alarm went off.', a: ['sooner had'], b: ['the CFO sat'], x: ['later', 'did', 'was'],
    traps: [['sooner the CFO had sat', 'Deutsch stellt ebenfalls um („Kaum hatte der CFO …“). Im Englischen wird die Umstellung nach No sooner oft vergessen.', 'After No sooner the verb comes before the subject, like in a question: had the CFO.']],
    ok: ['Teil 1: sooner had, das Hilfsverb steht vor dem Subjekt. Teil 2: the CFO sat, danach folgt than.', 'Part 1: sooner had, the auxiliary comes before the subject. Part 2: the CFO sat, then than follows.'],
  },
  // ---- used-to ----
  {
    p: 'ut.used-to', lv: 'B2', dom: 'biz',
    lead: 'Years ago we held weekly all-hands meetings, but we no longer do.', key: 'USED',
    before: 'We', after: 'weekly all-hands meetings.', a: ['used to'], b: ['hold', 'have', 'run'], x: ['use', 'were', 'would'],
    traps: [['used to holding', 'Deutsch „wir pflegten zu halten“ kennt kein -ing. Nach used to steht die Grundform; -ing gehört zu be used to.', 'After used to comes the base form; -ing belongs to be used to.']],
    ok: ['Teil 1: used to, früher so, heute nicht mehr. Teil 2: hold (Grundform), nach used to kein -ing.', 'Part 1: used to, so in the past, not any more. Part 2: hold (base form), no -ing after used to.'],
  },
  {
    p: 'ut.did-use-to', lv: 'B2+', dom: 'biz',
    lead: 'In the past, I did not like pivot tables.', key: "DIDN'T",
    before: 'I', after: 'pivot tables.', a: ["didn't use"], b: ['to like'], x: ['used', 'would', "wasn't"],
    traps: [["didn't used to like", "Nach didn't steht use ohne -d: Die Vergangenheit steckt schon in didn't.", "After didn't comes use without -d: the past is already in didn't."]],
    ok: ["Teil 1: didn't use, nach didn't verschwindet das -d. Teil 2: to like, danach to + Grundform.", "Part 1: didn't use, after didn't the -d disappears. Part 2: to like, to + base form follows."],
  },
  {
    p: 'ut.be-used-to', lv: 'B2+', dom: 'biz',
    lead: 'Handling several client calls at once is normal for me.', key: 'USED',
    before: 'I', after: 'several client calls at once.', a: ['am used to'], b: ['handling', 'taking', 'managing', 'dealing with'], x: ['use', 'handle', 'get'],
    traps: [['am used to handle', 'Das Deutsche hat „gewohnt sein zu + Infinitiv“. Nach be used to steht aber -ing, weil to hier eine Präposition ist.', 'After be used to comes -ing, because to is a preposition here.']],
    ok: ['Teil 1: am used to, „ich bin es gewohnt“. Teil 2: handling (-ing), to ist hier eine Präposition.', 'Part 1: am used to, “I am accustomed”. Part 2: handling (-ing), to is a preposition here.'],
  },
  {
    p: 'ut.get-used-to', lv: 'B2+', dom: 'biz',
    lead: 'It took me a while to adapt to working with the new CRM.', key: 'GET',
    before: 'It took me a while to', after: 'with the new CRM.', a: ['get used'], b: ['to working'], v: [{ a: ['get accustomed'], b: ['to working'] }], x: ['be used', 'got', 'getting'],
    traps: [['get used to work', 'Deutsch „sich daran gewöhnen, zu arbeiten“ nutzt zu + Infinitiv. Im Englischen ist to hier eine Präposition, also -ing.', 'German uses zu + infinitive. In English to is a preposition here, so -ing follows.']],
    ok: ['Teil 1: get used, Vorgang des Gewöhnens (nicht der Zustand: be used). Teil 2: to working, nach to steht -ing.', 'Part 1: get used, the process of getting accustomed (not the state: be used). Part 2: to working, -ing follows to.'],
  },
  // ---- c1-diplomacy ----
  {
    p: 'dip.wondering', lv: 'C1', dom: 'biz',
    lead: 'Could you confirm the venue by Friday?', key: 'WONDERING',
    before: 'I', after: 'the venue by Friday.', a: ['was wondering if', 'was wondering whether', 'am wondering if', 'am wondering whether'], b: ['you could confirm', 'you would confirm', 'you might confirm'], x: ['wonder', 'were', 'asked'],
    traps: [['was wondering if could you confirm', 'Im Nebensatz steht kein Frage-Aufbau: you could confirm, nicht could you confirm.', 'Inside the clause there is no question order: you could confirm, not could you confirm.']],
    ok: ['Teil 1: was wondering if/whether, die Vergangenheit schafft Distanz und macht die Bitte höflich. Teil 2: you could confirm, normale Satzstellung.', 'Part 1: was wondering if/whether, the past tense creates distance and makes the request polite. Part 2: you could confirm, normal word order.'],
  },
  {
    p: 'dip.hoping', lv: 'B2+', dom: 'biz',
    lead: 'We would like your feedback by the end of the day.', key: 'HOPING',
    before: 'We', after: 'your feedback by the end of the day.', a: ['were hoping', 'are hoping'], b: ['to get', 'to receive', 'to have', 'for'], x: ['hope', 'hoped', 'wishing'],
    traps: [['were hoping getting', 'Nach hoping steht to + Grundform, nie -ing. Das -ing kommt von Verben wie enjoy oder mind.', 'After hoping comes to + base form, never -ing. The -ing comes from verbs like enjoy or mind.']],
    ok: ['Teil 1: were hoping, die Vergangenheit macht den Wunsch höflicher. Teil 2: to get, danach to + Grundform.', 'Part 1: were hoping, the past tense makes the wish more polite. Part 2: to get, to + base form follows.'],
  },
  {
    p: 'dip.possible', lv: 'B2+', dom: 'biz',
    lead: 'Could you send the revised quote by Monday?', key: 'POSSIBLE',
    before: 'Would it be', after: 'the revised quote by Monday?', a: ['possible to'], b: ['send', 'forward', 'share'],
    v: [{ a: ['possible for you'], b: ['to send', 'to forward', 'to share'] }], x: ['able', 'possibly', 'that'],
    traps: [['possible that you send', 'Nach Would it be possible folgt to + Grundform, kein that-Satz. Deutsch „möglich, dass du schickst“ führt dorthin.', 'Would it be possible is followed by to + base form, not a that-clause. German “möglich, dass …” leads astray.']],
    ok: ['Teil 1: possible to, höfliche Frage nach einer Möglichkeit. Teil 2: send (Grundform), kein that-Satz.', 'Part 1: possible to, a polite question about a possibility. Part 2: send (base form), no that-clause.'],
  },
  {
    p: 'dip.understate', lv: 'B2+', dom: 'biz',
    lead: 'That deadline is a problem for our team.', key: 'TRICKY',
    before: 'That deadline could be', after: 'for our team.', a: ['a bit', 'a little', 'a little bit'], b: ['tricky'], x: ['difficult', 'very', 'slightly'],
    traps: [['a tricky bit', 'Die Reihenfolge ist a bit + Adjektiv. Deutsch „ein schwieriges Stück“ verleitet zu a tricky bit.', 'The order is a bit + adjective. German “ein schwieriges Stück” invites a tricky bit.']],
    ok: ['Teil 1: a bit, die Untertreibung macht den Einwand weich. Teil 2: tricky, ein weiches Wort statt difficult.', 'Part 1: a bit, the understatement softens the objection. Part 2: tricky, a soft word instead of difficult.'],
  },
  {
    p: 'dip.understate', lv: 'C1', dom: 'biz',
    lead: 'That plan is too ambitious for our team.', key: 'STRETCH',
    before: 'That plan could be', after: 'for our team.', a: ['a bit of', 'too much of'], b: ['a stretch'], x: ['far', 'very', 'real'],
    traps: [['a bit of stretch', 'Vor stretch fehlt der Artikel: a bit of a stretch. Deutsch „ein bisschen Anstrengung“ hat keinen Artikel.', 'The article is missing before stretch: a bit of a stretch. German has no article in this phrase.']],
    ok: ['Teil 1: a bit of, die Abschwächung vor dem Nomen. Teil 2: a stretch, höflich für „kaum machbar“.', 'Part 1: a bit of, the softener before the noun. Part 2: a stretch, polite for “hardly doable”.'],
  },
  // ---- conditionals ----
  {
    p: 'cn.first', lv: 'B2', dom: 'biz',
    lead: 'Assuming the client approves the quote today, we will start next week.', key: 'IF',
    before: '', after: 'the quote today, we will start next week.', a: ['If'], b: ['the client approves', 'the client has approved', 'the client accepts', 'the client signs off on', 'the client should approve'], x: ['When', 'will', 'unless'],
    traps: [['If the client will approve', 'Deutsch „wenn der Kunde genehmigen wird“ zieht will in den if-Satz. Bei echter Zukunft steht nach if das Präsens.', 'German “wenn … genehmigen wird” pulls will into the if-clause. For a real future the present follows if.']],
    ok: ['Teil 1: If leitet die Bedingung ein. Teil 2: the client approves (Präsens), kein will im if-Satz.', 'Part 1: If introduces the condition. Part 2: the client approves (present), no will in the if-clause.'],
  },
  {
    p: 'cn.second', lv: 'B2+', dom: 'biz',
    lead: 'We cannot expand the pilot because we have no extra budget.', key: 'MORE',
    before: 'If we', after: ', we would expand the pilot.', a: ['had more'], b: ['budget', 'money', 'funding', 'resources', 'cash'], x: ['have', 'would', 'extra'],
    traps: [['would have more', 'Das Deutsche „wenn wir mehr hätten“ klingt wie „würden … haben“. Im if-Satz steht aber die Past-Form, kein would.', 'German “wenn wir mehr hätten” is close to “würden haben”. The if-clause takes the past form, no would.']],
    ok: ['Teil 1: had more, der if-Satz steht im Past Simple (unwirkliche Gegenwart). Teil 2: budget, would gehört nur in den Hauptsatz.', 'Part 1: had more, the if-clause takes the past simple (unreal present). Part 2: budget, would belongs only in the main clause.'],
  },
  {
    p: 'cn.were', lv: 'B2+', dom: 'biz',
    lead: 'In your position, I would ask for a raise.', key: 'WERE',
    before: 'If I', after: ', I would ask for a raise.', a: ['were'], b: ['in your position', 'in your shoes', 'in your place', 'in your situation'], x: ['was', 'am', 'be'],
    traps: [['were at your place', 'At your place hieße „bei dir zu Hause“. Für die Lage heißt es in your place/position („an deiner Stelle“).', 'At your place means “at your home”. For the situation it is in your place/position.']],
    ok: ['Teil 1: were, nach if steht bei I formal were, nicht was. Teil 2: in your position, der Vergleich mit der anderen Person.', 'Part 1: were, after if with I the formal form is were, not was. Part 2: in your position, the comparison with the other person.'],
  },
  {
    p: 'cn.third', lv: 'B2+', dom: 'biz',
    lead: 'We did not run a load test, so we missed the performance problem.', key: 'HAVE',
    before: 'If we had run a load test, we', after: 'the performance problem.', a: ['would have'], b: ['caught', 'found', 'spotted', 'noticed', 'detected', 'identified'], x: ['had', 'will', 'catch'],
    traps: [['would have catch', 'Im Deutschen steckt die Vergangenheit in „hätten gefunden“. Deshalb wird im Englischen die 3. Form (caught) oft weggelassen.', 'German carries the past in “hätten gefunden”, so the past participle (caught) is often dropped in English.']],
    ok: ['Teil 1: would have, die Folge in der Vergangenheit. Teil 2: caught (3. Form), im if-Satz steht had run.', 'Part 1: would have, the result in the past. Part 2: caught (past participle), the if-clause has had run.'],
  },
  {
    p: 'cn.if-words', lv: 'B2+', dom: 'biz',
    lead: 'We will agree to a discount if you order at least 500 units.', key: 'PROVIDED',
    before: 'We will agree to a discount,', after: 'at least 500 units.', a: ['provided'], b: ['that you order', 'you order', 'that you buy', 'you buy', 'that you purchase', 'you purchase'], x: ['unless', 'providing', 'will'],
    traps: [['provided that you will order', 'Deutsch „vorausgesetzt, Sie werden bestellen“ zieht will in den Nebensatz. Nach provided that steht das Präsens.', 'German “vorausgesetzt, Sie werden bestellen” pulls will in. The present follows provided that.']],
    ok: ['Teil 1: provided, steht für „unter der Bedingung“. Teil 2: that you order (Präsens), kein will.', 'Part 1: provided, stands for “on the condition”. Part 2: that you order (present), no will.'],
  },
  // ---- cond-alt ----
  {
    p: 'ca.unless', lv: 'B2+', dom: 'biz',
    lead: 'We will ship on Monday if the client does not object.', key: 'UNLESS',
    before: 'We will ship on Monday', after: '.', a: ['unless'], b: ['the client objects', 'the client has objected', 'the client has an objection', 'the client raises an objection', 'the client says no'], x: ['if', 'not', 'without'],
    traps: [['unless the client does not object', 'Unless bedeutet schon „wenn nicht“. Eine zweite Verneinung dreht den Sinn um. Deutsch „es sei denn, … nicht“ verleitet dazu.', 'Unless already means “if not”. A second negation reverses the meaning.']],
    ok: ['Teil 1: unless, „es sei denn“. Teil 2: the client objects, positiv, weil unless das not schon enthält.', 'Part 1: unless, “except if”. Part 2: the client objects, positive, because unless already holds the not.'],
  },
  {
    p: 'ca.as-long-as', lv: 'B2+', dom: 'biz',
    lead: 'You may work remotely only if you attend the weekly sync.', key: 'LONG',
    before: 'You may work remotely', after: 'the weekly sync.', a: ['as long'], b: ['as you attend', 'as you join', 'as you go to', 'as you are attending'], v: [{ a: ['so long'], b: ['as you attend', 'as you join'] }], x: ['only', 'when', 'will'],
    traps: [['as long as you will attend', 'Nach as long as steht das Präsens, nicht will. Deutsch „solange du teilnehmen wirst“ führt zu will.', 'After as long as use the present, not will.']],
    ok: ['Teil 1: as long, die Wendung heißt „solange / unter der Bedingung“. Teil 2: as you attend (Präsens), kein will.', 'Part 1: as long, the phrase means “as long as / on condition”. Part 2: as you attend (present), no will.'],
  },
  {
    p: 'ca.otherwise', lv: 'B2+', dom: 'biz',
    lead: 'Please sign the contract today, or we cannot start the project.', key: 'OTHERWISE',
    before: 'Please sign the contract today.', after: 'start the project.', a: ['Otherwise'], b: ['we cannot', 'we can not', 'we will not', 'we will be unable to', 'we are unable to', 'we are not able to'], x: ['Or', 'But', 'Else'],
    traps: [['Otherwise we can start', 'Otherwise nennt die negative Folge. Mit can start sagt der Satz das Gegenteil des Gemeinten.', 'Otherwise names the negative result. With can start the sentence says the opposite of what is meant.']],
    ok: ['Teil 1: Otherwise, „sonst“ als eigener Satzanfang. Teil 2: we cannot, die negative Folge.', 'Part 1: Otherwise, “or else” as its own sentence opening. Part 2: we cannot, the negative consequence.'],
  },
  {
    p: 'ca.but-for', lv: 'C1', dom: 'biz',
    lead: 'The launch would have failed without your help.', key: 'BEEN',
    before: '', after: 'your help, the launch would have failed.', a: ['If it'], b: ['had not been for', 'hadn’t been for'], v: [{ a: ['Had it'], b: ['not been for'] }, { a: ['Had it not'], b: ['been for'] }], x: ['were', 'has', 'was'],
    traps: [['If it would not been for', 'Im if-Teil steht nie would: had not been for. Deutsch „wenn es nicht gewesen wäre“ legt would nahe.', 'The if-part never takes would: had not been for. German “wenn es nicht gewesen wäre” suggests would.'], ['If it had been for', 'Ohne not wäre der Sinn umgekehrt. Die Verneinung gehört in die Wendung: had not been for.', 'Without not the meaning would be reversed. The negation belongs in the phrase: had not been for.']],
    ok: ['Teil 1: If it, Einleitung der Bedingung. Teil 2: had not been for, die Vergangenheit steht im if-Teil, weil die Folge would have failed vergangen ist.', 'Part 1: If it, introduces the condition. Part 2: had not been for, the past in the if-part, because the result would have failed is past.'],
  },
  {
    p: 'ca.inversion', lv: 'C1', dom: 'biz',
    lead: 'If you have any questions, please call me.', key: 'SHOULD',
    before: '', after: 'any questions, please call me.', a: ['Should you'], b: ['have', 'ever have', 'happen to have'], nc: 1, x: ['If', 'Would', 'Do'],
    traps: [['Should you had', 'Nach Should you steht die Grundform: have. Die Inversion ersetzt if, die Zeitform bleibt Grundform.', 'After Should you comes the base form: have. The inversion replaces if, the verb stays in the base form.']],
    ok: ['Teil 1: Should you, die Inversion ersetzt if (förmlich). Teil 2: have, nach should die Grundform.', 'Part 1: Should you, inversion replaces if (formal). Part 2: have, the base form follows should.'],
  },
  // ---- mixed-cond ----
  {
    p: 'mc.wish-past', lv: 'C1', dom: 'biz',
    lead: 'I regret not asking for a written quote.', key: 'WISH',
    before: 'I', after: 'for a written quote.', a: ['wish I', 'wish that I'], b: ['had asked', 'had requested'], x: ['would', 'did', 'been'],
    traps: [['wish I would have asked', 'Deutsch „ich wünschte, ich hätte gefragt“ verleitet zu would have. Nach wish steht für die Vergangenheit had + 3. Form.', 'German “ich wünschte, ich hätte gefragt” invites would have. After wish the past takes had + past participle.']],
    ok: ['Teil 1: wish I, Bedauern. Teil 2: had asked (Past Perfect), would have gehört nicht hinter wish.', 'Part 1: wish I, regret. Part 2: had asked (past perfect), would have does not go after wish.'],
  },
  {
    p: 'mc.wish-would', lv: 'B2+', dom: 'biz',
    lead: 'It annoys me that our colleagues never update the shared calendar.', key: 'WISH',
    before: 'I', after: 'the shared calendar.', a: ['wish', 'wish that'], b: ['our colleagues would update', 'they would update'], x: ['hope', 'will', 'ever'],
    traps: [['wish our colleagues will update', 'Deutsch „ich wünschte, sie würden aktualisieren“. Nach wish steht would, nie will.', 'After wish comes would, never will.']],
    ok: ['Teil 1: wish, Ärger über eine Gewohnheit. Teil 2: our colleagues would update, wish + would + Grundform, nie will.', 'Part 1: wish, annoyance at a habit. Part 2: our colleagues would update, wish + would + base form, never will.'],
  },
  {
    p: 'mc.past-cond', lv: 'C1', dom: 'biz',
    lead: 'We did not automate the invoicing last year, so we spend a lot of time on it now.', key: 'LESS',
    before: 'If we had automated the invoicing last year, we', after: 'time on it now.', a: ['would spend'], b: ['less', 'much less', 'far less'], v: [{ a: ['would be spending'], b: ['less'] }], x: ['more', 'had', 'spent'],
    traps: [['would have spent less', 'Das Ergebnis gilt jetzt (now), nicht damals. Nach had + 3. Form im if-Teil steht would + Grundform.', 'The result applies now, not then. After had + participle in the if-part use would + base form.']],
    ok: ['Teil 1: would spend, die Folge gilt jetzt (now). Teil 2: less, weniger Zeit als jetzt.', 'Part 1: would spend, the result applies now. Part 2: less, less time than now.'],
  },
  {
    p: 'mc.present-cond', lv: 'C1', dom: 'biz',
    lead: 'We did not win the bid because our team is too small.', key: 'ENOUGH',
    before: 'If our team', after: ', we would have won the bid.', a: ['were', 'was'], b: ['big enough', 'large enough'], v: [{ a: ['had been'], b: ['big enough', 'large enough'] }], x: ['is', 'are', 'too'],
    traps: [['would be big enough', 'Im if-Teil steht kein would. Deutsch „wenn unser Team groß genug wäre“ klingt nach would.', 'The if-part takes no would. German “wenn … wäre” sounds like would.']],
    ok: ['Teil 1: were, Zustand jetzt im if-Teil. Teil 2: big enough, die Folge would have won liegt in der Vergangenheit.', 'Part 1: were, the state now in the if-part. Part 2: big enough, the result would have won lies in the past.'],
  },
];
